if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s1446 = function(db) 
    db.content.petComments.s1446 = function(db)
        local phrases = {
            "I may be tiny, but my heart's as big as the savannah!",
            "Brr, I'm shivering in this peanut-sized world.",
            "Can I have a ride on your back?",
            "Please don't step on me!",
            "Giant peanuts are my Everest.",
            "I'm just a pachyderm in a pocket.",
            "Do I look like Dumbo?",
            "Tiny trunks, big dreams.",
            "Watch out for mouse-sized mice!",
            "I've got a trunk full of wisdom.",
            "I'm the jumbo in the micro world.",
            "Why is the grass so tall?",
            "Ants are my tiny friends.",
            "Who shrunk the watering hole?",
            "Even ants look huge from down here.",
            "I'm a stampede waiting to happen.",
            "Tiny tusks, big aspirations.",
            "Can I ride on your shoe, please?",
            "I'm pocket-sized and proud!",
            "I've got a peanut-sized appetite.",
            "Why do I feel like a peanut?",
            "Being small has its advantages.",
            "Mighty mites, beware of me!",
            "My heart is as large as the Serengeti.",
            "Why are birds so massive?",
            "Tiny grass, big adventure.",
            "I'm the king of the minuscule.",
            "I need a magnifying glass to see a banana.",
            "I'm the ruler of the itty-bitty jungle.",
            "Even ants look up to me.",
            "Tiny trumpets, big impact.",
            "I've got pocket-sized pizzazz.",
            "Why is this pebble so enormous?",
            "Do I look cute in this grass?",
            "Mouse-sized adventures await!",
            "I'm a tiny titan.",
            "Giraffes are skyscrapers in my world.",
            "I've got a thimble-sized thirst.",
            "Why is the world so gigantic?",
            "Even pebbles look like mountains.",
            "Tiny tusks, big charm.",
            "Can I ride on a grasshopper?",
            "I'm the smallest big thing around.",
            "Beware the mighty minis!",
            "Tiny trunks, boundless curiosity.",
            "I'm a gentle giant in a miniature world.",
            "Tiny steps, colossal heart.",
            "Even pebbles have summits to climb.",
            "Tiny trumpets, big celebrations.",
            "Peanuts are my boulders.",
            "I've got a mini-mammoth appetite.",
            "Even ladybugs seem enormous.",
            "I'm the giant of the mini-forest.",
            "Can I ride on a beetle's back?",
            "I'm the gentlest of minuscule giants.",
            "Even grains of sand are deserts.",
            "Tiny rumbles, mighty roars.",
            "I'm a pachyderm in a pebble's world.",
            "I've got a bite-sized appetite.",
            "Even dewdrops are like waterfalls.",
            "I may be mini, but I'm larger than life.",
            "I've got an inch-sized appetite.",
            "Tiny elephant, big charm.",
            "Even pebbles have peaks to conquer.",
            "I'm the grandeur in the grains.",
            "Tiny trumpets, massive melodies.",
            "Peanuts are my mighty monoliths.",
            "I've got a teaspoon-sized heart.",
            "Tiny tusks, boundless adventures.",
            "I'm a pint-sized pachyderm!",
            "Why is the grass so tall?",
            "Ants are my tiny friends.",
            "Who shrunk the watering hole?",
            "Even ants look huge from down here.",
            "I'm a stampede waiting to happen.",
            "Tiny tusks, big aspirations.",
            "Can I ride on your shoe, please?",
            "I'm pocket-sized and proud!",
            "I've got a peanut-sized appetite.",
            "Why do I feel like a peanut?",
            "Being small has its advantages.",
            "Mighty mites, beware of me!",
            "My heart is as large as the Serengeti.",
            "Why are birds so massive?",
            "Tiny grass, big adventure.",
            "I'm the king of the minuscule.",
            "I need a magnifying glass to see a banana.",
            "I'm the ruler of the itty-bitty jungle.",
            "Even ants look up to me.",
            "Tiny trumpets, big impact.",
            "I've got pocket-sized pizzazz.",
            "Why is this pebble so enormous?",
            "Do I look cute in this grass?",
            "Mouse-sized adventures await!",
            "I'm a tiny titan.",
            "Giraffes are skyscrapers in my world.",
            "I've got a thimble-sized thirst.",
            "Why is the world so gigantic?",
            "Even pebbles look like mountains.",
            "Tiny tusks, big charm.",
            "Can I ride on a grasshopper?",
            "I'm the smallest big thing around.",
            "Beware the mighty minis!",
            "Tiny trunks, boundless curiosity.",
            "I'm a gentle giant in a miniature world.",
            "Tiny steps, colossal heart.",
            "Even pebbles have summits to climb.",
            "Tiny trumpets, big celebrations.",
            "Peanuts are my boulders.",
            "I've got a mini-mammoth appetite.",
            "Even ladybugs seem enormous.",
            "I'm the giant of the mini-forest.",
            "Can I ride on a beetle's back?",
            "I'm the gentlest of minuscule giants.",
            "Even grains of sand are deserts.",
            "Tiny rumbles, mighty roars.",
            "I'm a pachyderm in a pebble's world.",
            "I've got a bite-sized appetite.",
            "Even dewdrops are like waterfalls.",
            "I may be mini, but I'm larger than life.",
            "I've got an inch-sized appetite.",
            "Tiny elephant, big charm.",
            "Even pebbles have peaks to conquer.",
            "I'm the grandeur in the grains.",
            "Tiny trumpets, massive melodies.",
            "Peanuts are my mighty monoliths.",
            "I've got a teaspoon-sized heart.",
            "Tiny tusks, boundless adventures.",
            "I'm a pint-sized pachyderm!"        
        }
        return phrases[math.random(1, OracleHUD_TableGetLength(phrases))]
    end
end
