if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s374 = function(db) 
    db.content.petComments.s374 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        -- list 100 random things a black lamb might emote and format as lua table
        local emote = {
            "Bleats happily.",
            "Nibbles on some grass.",
            "Wags its little tail.",
            "Sniffs the flowers.",
            "Playfully frolics in the field.",
            "Nuzzles up to a friendly player.",
            "Watches the clouds pass by.",
            "Leaps with joy.",
            "Rolls on the soft ground.",
            "Sits down and takes a rest.",
            "Chases its own tail (or attempts to).",
            "Gambols around in circles.",
            "Snuggles with other lambs.",
            "Wiggles its ears in delight.",
            "Butts heads with an imaginary fellow lamb.",
            "Chews on a twig playfully.",
            "Blinks its big, innocent eyes.",
            "Gives an affectionate bleat.",
            "Naps peacefully in the shade.",
            "Watches a passing butterfly.",
            "Jumps over a small obstacle.",
            "Bounces with enthusiasm.",
            "Rolls over for a belly rub.",
            "Trots around the meadow.",
            "Gives chase to a stray leaf.",
            "Sniffs and inspects its surroundings.",
            "Curiously tilts its head.",
            "Paws playfully at the ground.",
            "Waits patiently for attention.",
            "Happily grazes on... whatever.",
            "Prances around in a circle.",
            "Stretches its little legs.",
            "Bounces on its hind legs.",
            "Watches a distant flock of birds.",
            "Buries its nose in a soft patch of grass.",
            "Happily nibbles on a dandelion.",
            "Watches the sunset with contentment.",
            "Gives a little yawn and stretches.",
            "Bobs its head to the rhythm of nature.",
            "Chases its own shadow for fun.",
            "Finds a cozy spot and lies down.",
            "Pounces on an unsuspecting insect.",
            "Wanders around aimlessly.",
            "Gathers with other lambs for a group bleat.",
            "Happily follows a player around.",
            "Inspects a curious rock or object.",
            "Paws at a puddle of water.",
            "Rolls in a soft pile of fallen leaves.",
            "Frolics in the morning dew.",
            "Jumps over a small rock or log.",
            "Sways its tail in rhythm with the breeze.",
            "Gambols with carefree abandon.",
            "Observes the world with wide eyes.",
            "Happily munches on a patch of clover.",
            "Sniffs the air to catch different scents.",
            "Bounces up and down in delight.",
            "Gives a friendly head-butt to a player.",
            "Scampers about with boundless energy.",
            "Plays a game of hide and seek.",
            "Nuzzles a companion affectionately.",
            "Chews on a sweet piece of hay.",
            "Finds a sunny spot and basks in it.",
            "Nudges a player for attention.",
            "Leaps over a small stream with grace.",
            "Stands tall on its hind legs.",
            "Happily hops in a circle.",
            "Rests its head on a comfortable rock.",
            "Watches the stars twinkle at night.",
            "Bobs its head in acknowledgment.",
            "Snuggles up to a warm fire.",
            "Happily explores new terrain.",
            "Gives a little twist to its tail.",
            "Bleats a cheerful tune.",
            "Nuzzles a friendly pet or critter.",
            "Chews its cud thoughtfully.",
            "Watches the sky with wonder.",
            "Paws at a patch of colorful wildflowers.",
            "Bounces along in a playful gait.",
            "Happily trots around in circles.",
            "Jumps up to catch low-hanging leaves.",
            "Sniffs the aroma of fresh herbs.",
            "Butts heads with its reflection.",
            "Bleats a greeting to other animals.",
            "Gambols around with a frolicsome skip.",
            "Curls up for a quick catnap.",
            "Happily munches on a juicy apple.",
            "Chases a playful breeze.",
            "Finds a soft pile of autumn leaves.",
            "Nuzzles a fallen cherry blossom.",
            "Rolls down a gentle grassy slope.",
            "Wags its tail in pure delight.",
            "Happily explores a patch of daisies.",
            "Prances with a light, bouncy step.",
            "Snuggles up to a warm, furry friend.",
            "Chews thoughtfully on a stalk of wheat.",
            "Bounces around as if in a spring meadow.",
            "Naps beneath the shade of a large tree.",
            "Watches the world go by with curiosity.",
            "Gives a little wiggle of its ears.",
            "Leaps playfully from rock to rock.",
            "Bleats a cheerful melody to the wind.",
            "Nuzzles a friendly critter or player.",
            "Chews its favorite cud contentedly.",
            "Paws at a small, glistening puddle.",
            "Gambols around a blossoming field.",
            "Happily grazes on a patch of clover.",
            "Rolls in a soft bed of spring flowers.",
            "Bounces around like a playful lamb.",
            "Sniffs the aroma of freshly baked bread.",
            "Butts heads with a friendly companion.",
            "Bleats a hello to the world.",
            "Nuzzles up to a comforting presence.",
            "Chews on a delectable piece of fruit.",
            "Watches the sky with a calm demeanor.",
            "Finds a cozy spot and curls up to rest.",
            "Pounces on a fallen leaf in the wind.",
            "Happily trots around with a lively step.",
            "Plays a game of tag with its companions.",
            "Naps beneath the gentle shade of a tree.",
            "Watches the sky with a sense of peace.",
            "Gives a little twist of its tail in joy.",
            "Nudges a player for a friendly interaction.",
            "Leaps over a small obstacle with grace.",
            "Bobs its head to the rhythm of the day.",
            "Snuggles up to a warm fire on a cool night."
        }
        local emote_summon = {
            "Slowly opens its eyes, adjusting to the morning light",
            "Stretches its legs, unfolding from a cozy sleeping position",
            "Yawns wide, displaying tiny teeth and a pink tongue",
            "Shakes off the last remnants of sleep with a fluffy shake",
            "Nuzzles against its mother's woolly side, seeking warmth",
            "Blinks sleepily, taking in its surroundings with curiosity",
            "Curls back into a ball, attempting to catch a few more winks",
            "Wiggles its ears, still half-dreaming in the morning haze",
            "Rolls over and snuggles into a soft patch of grass",
            "Gently rises from its resting spot, hooves stretching the soil",
            "Sighs contentedly, expressing the comfort of a good nap",
            "Nudges a sibling, encouraging them to wake up and play",
            "Dreamily gazes at the sky, lost in woolly contemplation",
            "Shuffles its hooves, readjusting to the sensation of standing",
            "Twitches its nose, detecting the scents of the waking world",
            "Flops its ears lazily, still in a state of morning drowsiness",
            "Slowly gets up, testing each leg after a peaceful slumber",
            "Nestles into the warmth of the morning sun, soaking it in",
            "Gazes around, momentarily disoriented from a deep sleep",
            "Sniffs the air, catching the scent of familiar meadow grass",
            "Lies on its back, kicking its legs in a cute, sleepy dance",
            "Shivers off a bit of morning dew clinging to its wool",
            "Gently nudges its mother, signaling the start of the day",
            "Bleats softly, communicating its wakefulness to the flock",
            "Shakes its head, scattering remnants of a sweet dream",
            "Rests its head on a fluffy tuft, savoring the softness",
            "Takes a moment to groom its wool, post-nap fur maintenance",
            "Happily trots in circles, celebrating the return of playtime",
            "Licks its lips, perhaps dreaming of a midnight snack",
            "Raises its head, surveying the meadow after a restful nap",
            "Snuggles into the warmth of its own wool, feeling cozy",
            "Rubs its face against a tree trunk, stretching its neck",
            "Bounces on its hooves, full of newfound morning energy",
            "Snorts softly, as if blowing away the remnants of a dream",
            "Flicks its tail, swatting away imaginary sleep disturbances",
            "Chews on a tuft of grass, transitioning from dreams to grazing",
            "Sighs with contentment, relishing the peacefulness of waking",
            "Stands still for a moment, soaking in the sounds of nature",
            "Scratches its ear with a hind hoof, still a bit groggy",
            "Closes its eyes, as if trying to recapture a pleasant dream",
            "Bobs its head, as if in rhythm with a melody from its dreams",
            "Gently butts heads with a sibling, a playful wake-up call",
            "Sniffs the ground, checking for any interesting scents",
            "Shakes its wool, like a fluffy blanket being unfurled",
            "Stands on three legs, stretching each limb individually",
            "Bounces on its hind legs, testing its morning flexibility",
            "Nuzzles into a soft patch of moss, a makeshift morning pillow",
            "Flips its tail in the air, a morning greeting to the world",
            "Wanders around in circles, still half-dazed from sleep",
            "Gazes at a nearby pond, as if contemplating its reflection",
            "Shuffles its hooves, creating a mini dust cloud as it wakes",
            "Pokes its nose into the morning breeze, sniffing for adventure",
            "Bleats joyfully, announcing its presence to the waking meadow",
            "Nuzzles against a rock, perhaps mistaking it for a fellow lamb",
            "Takes a few clumsy steps, getting accustomed to being awake",
            "Nibbles on a patch of dewy grass, savoring the morning freshness",
            "Happily trots towards its mother, seeking a post-nap cuddle",
            "Scratches its chin with a hind hoof, rubbing away sleepiness",
            "Twirls in a circle, a woolly dance to celebrate the new day",
            "Sniffs at a patch of wildflowers, taking in the morning aroma",
            "Bounces through a bed of fallen leaves, creating a playful rustle",
            "Nudges a sleeping butterfly with its nose, curious and gentle",
            "Circles around a tree, playfully marking its waking territory",
            "Sniffs at a patch of clover, deciding on the first morning nibble",
            "Gazes at the horizon, as if contemplating the day ahead",
            "Paws at the ground, creating a small mound of morning soil",
            "Wanders towards a sunlit spot, seeking the warmth on its fur",
            "Bleats softly, as if whispering a secret to the morning breeze",
            "Snuggles into a bed of soft petals, a makeshift floral pillow",
            "Nuzzles against a pile of fallen leaves, exploring the textures",
            "Bounces from hoof to hoof, a joyful morning dance",
            "Snorts playfully, expressing morning exuberance",
            "Stares at its own shadow, still adjusting to the waking world",
            "Nibbles on a twig, perhaps dreaming of midnight snacks",
            "Wags its tail, a woolly expression of happiness",
            "Curls its tongue around a dewdrop, savoring the morning taste",
            "Rolls onto its back, kicking its legs in the air with sleepy delight",
            "Sniffs at a passing breeze, catching the scents of a new day",
            "Chews on its own wool, a quirky morning habit",
            "Flops onto its side, enjoying the coolness of the morning soil",
            "Bounces over a small mound, testing its morning agility",
            "Nudges a nearby rock, as if checking for signs of morning life",
            "Gazes at a patch of sunlight, warming its woolly coat",
            "Shuffles its hooves in the grass, creating a natural morning rhythm",
            "Sniffs at a patch of herbs, deciding on the first breakfast bite",
            "Bleats melodically, as if composing a morning symphony",
            "Wiggles its ears, tuning into the sounds of the waking world",
            "Rolls over and stretches its legs, embracing the morning stretch",
            "Snuggles against a fellow lamb, sharing the warmth of waking",
            "Chases its tail in playful circles, a quirky morning game",
            "Nuzzles against a friendly farm cat, sharing morning greetings",
            "Bounces through a field of tall grass, creating a playful rustle",
            "Sniffs at a fallen feather, investigating the morning surprise",
            "Licks a dew-covered leaf, tasting the freshness of the morning"
        }
        local speak = {
            "Bleat-iful day, isn't it?",
            "Have you herd the latest news?",
            "I'm woolly glad to see you!",
            "Grass is always greener on my side.",
            "Let's flock together!",
            "Life's a pasture, enjoy the graze.",
            "Wool you be my friend?",
            "Feeling sheepish today.",
            "Ewe are my favorite!",
            "Woolpower! Baa-mazing!",
            "Baa-ck off, I'm grazing here!",
            "Ewe-nique and proud of it!",
            "Wool I be in your flock?",
            "The world is our pasture to explore.",
            "Sheep thrills and adventures await!",
            "Woolcome to my meadow!",
            "Ewe are the best in the field!",
            "Just following the herd!",
            "Counting sheep? I'm number one!",
            "Baa-d to the bone (not really).",
            "Grazing is life's simple pleasure.",
            "Ewe-nique and one of a kind!",
            "It's a baa-eautiful day, isn't it?",
            "Every day is a meadow of opportunity.",
            "Herding together is so much fun!",
            "Wool you join me for a chat?",
            "Ewe are the cream of the crop!",
            "Woolpower! Unleash the fluff!",
            "I'm not just another sheep in the flock.",
            "Life's all about enjoying the pasture.",
            "Being woolly is a way of life!",
            "Baa-king up a storm of happiness!",
            "Let's create our own baa-rilliant adventures!",
            "Ewe-nity and friendship go hoof in hoof.",
            "With every baa, a new story begins.",
            "Baa-d times are behind us, it's all good now!",
            "Fleecy and fabulous!",
            "Baa-lieve in the magic of the meadow!",
            "Ewe-nique, just like every sheep!",
            "Baa-sketfuls of joy await us!",
            "The meadow is our playground!",
            "Ewe's got a friend in me.",
            "This pasture is where dreams graze!",
            "Baa-rilliant moments are made here.",
            "Ewe-niverse full of possibilities!",
            "Every hoofstep is a new adventure.",
            "Baa-sically, I'm awesome!",
            "Meadows are made for frolicking!",
            "Ewe-nity and harmony in the herd.",
            "Ewe-nique like a snowflake in summer.",
            "Every baa is a song of joy!",
            "Baa-ck to the meadow we go!",
            "Ewe are the sunshine on a cloudy day.",
            "Woolen coats and hearts warm and fuzzy!",
            "Life's a pasture, let's roam together.",
            "Wool I ever stop being this cute?",
            "Ewe are the wind beneath my fleece!",
            "Baa-lieve in the power of fluff!",
            "This meadow is our playground!",
            "Ewe-nite and stand strong together.",
            "Grazing is meditation for the soul.",
            "Baa-sketfuls of love to share!",
            "Ewe are my source of happiness.",
            "Wool you be my partner in crime?",
            "The world is our oyster... I mean meadow!",
            "Baa-d times are no match for us!",
            "Ewe are my favorite sight to see.",
            "Woolly snuggles are the best snuggles!",
            "Happiness is grazing in good company.",
            "Life's baa-rilliant with friends like ewe!",
            "Woolly tales to share by the campfire.",
            "Ewe-niverse of adventures await us!",
            "Every day is a chance to frolic.",
            "Baa-ck at it with more fun!",
            "Ewe-nite, we stand strong together!",
            "Every baa is a melody of life.",
            "Baa-sketfuls of joy are always full.",
            "Ewe are the sunshine of my meadow.",
            "Wooly friends make the best friends.",
            "Life's a pasture, let's make it great!",
            "Wool I ever get enough cuddles?",
            "Ewe make my heart skip a beat!",
            "Baa-lieve in the magic of the meadow!",
            "This meadow is our canvas of dreams.",
            "Ewe-nique, just like every lamb!",
            "Baa-sketfuls of happiness await us!",
            "The meadow is our playground of joy!",
            "Ewe-nite and stand strong as one.",
            "Grazing is a form of sheep therapy.",
            "Baa-sketfuls of love and warmth.",
            "Ewe are the key to my happiness.",
            "Wool you be my partner in adventures?",
            "The meadow is our world to explore.",
            "Baa-d times are simply moments in time.",
            "Ewe are the light in my meadow.",
            "Woolly snuggles make everything better!",
            "Happiness is grazing in good company.",
            "Life's baa-rilliant with friends like ewe!",
            "Woolly tales to share under the stars.",
            "Ewe-niverse full of dreams to chase!",
            "Every day is a chance to frolic and play.",
            "Baa-ck for more fun and adventures!",
            "Ewe-nite, we stand strong as a flock!",
            "Every baa is a note in our symphony.",
            "Baa-sketfuls of joy are always overflowing.",
            "Ewe are the sunshine of my meadow.",
            "Wooly friends make the best companions.",
            "Life's a pasture, let's make it amazing!",
            "Wool I ever stop enjoying this life?",
            "Ewe make my heart feel all warm and fuzzy!",
            "Baa-lieve in the magic of the meadow!",
            "This meadow is our canvas of dreams!",
            "Ewe-nique, just like every lamb in the field!",
            "Baa-sketfuls of happiness await us always!",
            "The meadow is our playground of endless joy!",
            "Ewe-nite and stand strong together forever!",
            "Grazing is like meditation for the soul!",
            "Baa-sketfuls of love and warmth to share with ewe!",
            "Ewe are the key to my heart's happiness!",
            "Wool you be my partner in all our adventures?",
            "The meadow is our world to explore and cherish!",
            "Baa-d times are simply fleeting moments in time!",
            "Ewe are the light that brightens my meadow every day!",
            "Woolly snuggles make everything better, don't they?",
            "Happiness is grazing in good company, like ours!",
            "Life's baa-rilliant with friends like ewe by my side!",
            "Woolly tales to share under the twinkling stars above!",
            "Ewe-niverse is full of dreams waiting for us to chase!",
            "Every day is a chance to frolic, play, and be joyful!",
            "Baa-ck for more fun and adventures together, always!",
            "Ewe-nite, we stand strong as a united and happy flock!",
            "Every baa is a note in our beautiful and harmonious symphony!",
            "Baa-sketfuls of joy are always overflowing in our hearts!",
            "Ewe are the sunshine that brightens up my meadow every day!",
            "Wooly friends make the best companions, now and forever!",
            "Life's a pasture, and together, let's make it truly amazing!",
            "Wool I ever stop enjoying this wonderful life with ewe?",
            "Ewe make my heart feel all warm and fuzzy, full of love!",
            "Baa-lieve in the magic of the meadow, where dreams come true!",
            "This meadow is our canvas of dreams, and we paint it with joy!",
            "Ewe-nique, just like every lamb in the field, special in our own way!",
            "Baa-sketfuls of happiness await us always, in every new day!",
            "The meadow is our playground of endless joy, let's play together!",
            "Ewe-nite and stand strong together forever, in a bond unbreakable!",
            "Grazing is like meditation for the soul, peaceful and serene!",
            "Baa-sketfuls of love and warmth to share with ewe, my dearest friend!",
            "Ewe are the key to my heart's happiness, forever and always!",
            "Wool you be my partner in all our adventures, by my side?",
            "The meadow is our world to explore and cherish, full of wonders!",
            "Baa-d times are simply fleeting moments in time, soon to pass!",
            "Ewe are the light that brightens my meadow every day, my sunshine!",
            "Woolly snuggles make everything better, don't they? Let's snuggle!",
            "Happiness is grazing in good company, like ours, forever together!",
            "Life's baa-rilliant with friends like ewe by my side, in every moment!",
            "Woolly tales to share under the twinkling stars above, by your side!",
            "Ewe-niverse is full of dreams waiting for us to chase, let's dream!",
            "Every day is a chance to frolic, play, and be joyful, together always!",
            "Baa-ck for more fun and adventures together, always and forever!",
            "Ewe-nite, we stand strong as a united and happy flock, my dear friend!",
            "Every baa is a note in our beautiful and harmonious symphony, a joy!",
            "Baa-sketfuls of joy are always overflowing in our hearts, with ewe!",
            "Ewe are the sunshine that brightens up my meadow every day, my light!",
            "Wooly friends make the best companions, now and forever, by my side!",
            "Life's a pasture, and together, let's make it truly amazing, let's graze!",
            "Wool I ever stop enjoying this wonderful life with ewe, my dear friend?",
            "Ewe make my heart feel all warm and fuzzy, full of love, happiness!",
            "Baa-lieve in the magic of the meadow, where dreams come true, always!",
            "This meadow is our canvas of dreams, and we paint it with joy, together!",
            "Ewe-nique, just like every lamb in the field, special in our own way, forever!",
            "Baa-sketfuls of happiness await us always, in every new day, in every moment!",
            "The meadow is our playground of endless joy, let's play together, have fun!",
            "Ewe-nite and stand strong together forever, in a bond unbreakable, my friend!",
            "Grazing is like meditation for the soul, peaceful and serene, together with you!",
            "Baa-sketfuls of love and warmth to share with ewe, my dearest friend, always!",
            "Ewe are the key to my heart's happiness, forever and always, in every moment!",
            "Wool you be my partner in all our adventures, by my side, through it all!",
            "The meadow is our world to explore and cherish, full of wonders, let's explore!",
            "Baa-d times are simply fleeting moments in time, soon to pass, with you by my side!",
            "Ewe are the light that brightens my meadow every day, my sunshine, my joy!",
            "Woolly snuggles make everything better, don't they? Let's snuggle, my dear friend!",
            "Happiness is grazing in good company, like ours, forever together, full of joy!",
            "Life's baa-rilliant with friends like ewe by my side, in every moment, in every day!",
            "Woolly tales to share under the twinkling stars above, by your side, in the night!",
            "Ewe-niverse is full of dreams waiting for us to chase, let's dream, dream together!",
            "Every day is a chance to frolic, play, and be joyful, together always, full of life!",
            "Baa-ck for more fun and adventures together, always and forever, side by side!",
            "Ewe-nite, we stand strong as a united and happy flock, my dear friend, my joy!",
            "Every baa is a note in our beautiful and harmonious symphony, a joy, a melody!",
            "Baa-sketfuls of joy are always overflowing in our hearts, with ewe, full of happiness!",
            "Ewe are the sunshine that brightens up my meadow every day, my light, my world!",
            "Wooly friends make the best companions, now and forever, by my side, by your side!",
            "Life's a pasture, and together, let's make it truly amazing, let's graze and enjoy!",
            "Wool I ever stop enjoying this wonderful life with ewe, my dear friend, my companion!",
            "Ewe make my heart feel all warm and fuzzy, full of love, happiness, and contentment!",
            "Baa-lieve in the magic of the meadow, where dreams come true, always, full of hope!",
            "This meadow is our canvas of dreams, and we paint it with joy, together, forever and always!",
            "Ewe-nique, just like every lamb in the field, special in our own way, forever and always!",
            "Baa-sketfuls of happiness await us always, in every new day, in every moment, full of joy!",
            "The meadow is our playground of endless joy, let's play together, have fun, and enjoy life!",
            "Ewe-nite and stand strong together forever, in a bond unbreakable, my friend, my dear friend!",
            "Grazing is like meditation for the soul, peaceful and serene, together with you, in harmony!",            
        }
        local speak_win = {
            "Baa-ravo! A battle well won!",
            "We emerged victorious once again!",
            "The meadow is safe from harm!",
            "Our woolly might knows no bounds!",
            "We stand as champions of the field!",
            "No foe can withstand our fluffy might!",
            "Baa-lliant victory, my companion!",
            "Our fleece is our invincible armor!",
            "Fierce as lions, we claim our triumph!",
            "Ewe-nique and undefeated, as always!",
            "The meadow is our dominion once more!",
            "Baa-ttled with courage, and we won!",
            "In the meadow, we reign supreme!",
            "Woolpower! Unstoppable and triumphant!",
            "No challenge can baa-r our path to glory!",
            "Our bravery shines like the morning sun!",
            "Baa-lliantly victorious, as we should be!",
            "Fighting for the meadow is our destiny!",
            "Ewe are the best battle comrade ever!",
            "With you, we conquer all adversaries!",
            "Let our triumphant bleats echo far and wide!",
            "Ewe and I make an unbeatable duo!",
            "Baa-d villains tremble before our fluff!",
            "Our strength is the mightiest of all!",
            "The meadow is our realm, once more!",
            "Baa-ringing victory to the meadow!",
            "We're the true champions of the field!",
            "No challenge is too great for us to conquer!",
            "Our hearts brim with pride and triumph!",
            "Baa-ttle-tested and forever triumphant!",
            "Ewe-niversal cheers for our triumphant spirit!",
            "Woolpower! We're the heroes of the meadow!",
            "No adversary can withstand our valor!",
            "Our victory is written in the stars above!",
            "Baa-lliantly victorious, as we always are!",
            "We're the legendary woolly heroes!",
            "Defending the meadow is our honored task!",
            "Ewe make me proud to be your companion!",
            "With you, we are undefeatable and true!",
            "Let our triumphant bleats resonate widely!",
            "Ewe are the ultimate ally in battle!",
            "Baa-d times are behind us, never to return!",
            "Our strength is unmatched and unwavering!",
            "The meadow belongs to us forevermore!",
            "Baa-ringing triumph to the meadow's door!",
            "We're the champions of the open field!",
            "No challenge can deter us from victory!",
            "Our hearts are brimming with joy and triumph!",
            "Baa-ttle-tested and forever successful!",
            "Ewe-niversal respect for our valor!",
            "Woolpower! We're the champions of all!",
            "No foe can break our indomitable spirit!",
            "Our courage shines like the radiant moon!",
            "Baa-lliantly victorious, as we always are!",
            "Fighting for the meadow is our ultimate cause!",
            "Ewe are the bravest companion I know!",
            "With you, we conquer all obstacles!",
            "Let our triumphant bleats echo wide and far!",
            "Ewe are the ultimate partner in battle!",
            "Baa-d days are behind us, forever gone!",
            "Our woolly spirit is invincible and bold!",
            "The meadow celebrates our valorous triumph!",
            "Baa-ttle-tested and forever triumphant!",
            "We're the legendary woolly heroes of all!",
            "Defending the meadow is our noble legacy!",
            "Ewe make me proud every day, my friend!",
            "With you, we're unstoppable and resolute!",
            "Let our triumphant bleats reach the heavens!",
            "Ewe are the ultimate companion in battles!",
            "Baa-d foes quake before our formidable might!",
            "Our strength knows no boundaries or limits!",
            "The meadow bows to our greatness and glory!",
            "Baa-ringing victory to the meadow's doorstep!",
            "We're the champions of the open field, forever!",
            "No challenge can thwart our path to victory!",
            "Our hearts are overflowing with joy and success!",
            "Baa-ttle-tested and forever triumphant!",
            "Ewe-niversal acclaim for our unwavering valor!",
            "Woolpower! We're the heroes of the meadow, always!",
            "No enemy can break our unwavering determination!",
            "Our courage shines like the brightest star!",
            "Baa-lliantly victorious, as we always should be!",
            "Fighting for the meadow is our eternal purpose!",
            "Ewe are the most fearless comrade I know!",
            "With you, we conquer all adversaries and challenges!",
            "Let our triumphant bleats echo far and wide, always!",
            "Ewe and I make an unbeatable team, forevermore!",
            "Baa-d villains tremble before our indomitable fluff!",
            "Our strength is the mightiest of all, no contest!",
            "The meadow is our rightful realm, forever ours!",
            "Baa-ringing victory to the meadow, our kingdom!",
            "We're the true champions of the open field, eternally!",
            "No challenge is too great for us to conquer!",
            "Our hearts brim with pride and triumph, endlessly!",
            "Baa-ttle-tested and forever triumphant, always!",
            "Ewe-niversal cheers for our triumphant spirit, forever!",
            "Woolpower! We're the heroes of the meadow, always!",
            "No adversary can withstand our valor, no matter what!",
            "Our victory is written in the stars above, always!",
            "Baa-lliantly victorious, as we always are, forever!",
            "We're the legendary woolly heroes, throughout time!",
            "Defending the meadow is our honored task, always!",
            "Ewe make me proud to be your companion, every day!",
            "With you, we are undefeatable and true, without doubt!",
            "Let our triumphant bleats resonate widely and far, always!",
            "Ewe are the ultimate ally in battle, eternally!",
            "Baa-d times are behind us, never to return, for sure!",
            "Our strength is unmatched and unwavering, always!",
            "The meadow belongs to us forevermore, without end!",
            "Baa-ringing triumph to the meadow's door, eternally!",
            "We're the champions of the open field, forevermore!",
            "No challenge can deter us from victory, that's for sure!",
            "Our hearts are brimming with joy and triumph, forever!",
            "Baa-ttle-tested and forever successful, no doubt about it!",
            "Ewe-niversal respect for our valor, eternally!",
            "Woolpower! We're the champions of all, without a doubt!",
            "No foe can break our indomitable spirit, no matter what!",
            "Our courage shines like the radiant moon, always!",
            "Baa-lliantly victorious, as we always are, eternally!",
            "Fighting for the meadow is our ultimate cause, always!",
            "Ewe are the bravest companion I know, without a doubt!",
            "With you, we conquer all obstacles, no question about it!",
            "Let our triumphant bleats echo wide and far, eternally!",
            "Ewe are the ultimate partner in battle, forever!",
            "Baa-d days are behind us, forever gone, no question about it!",
            "Our woolly spirit is invincible and bold, always!",
            "The meadow celebrates our valorous triumph, eternally!",
            "Baa-ttle-tested and forever triumphant, without a doubt!",
            "We're the legendary woolly heroes of all, always!",
            "Defending the meadow is our noble legacy, eternally!",
            "Ewe make me proud every day, my friend, no doubt about it!",
            "With you, we're unstoppable and resolute, forever!",
            "Let our triumphant bleats reach the heavens, always!",
            "Ewe are the ultimate companion in battles, eternally!",
            "Baa-d foes quake before our formidable might, no question about it!",
            "Our strength knows no boundaries or limits, always!",
            "The meadow bows to our greatness and glory, forever!",
            "Baa-ringing victory to the meadow's doorstep, eternally!",
            "We're the champions of the open field, forever and always!",
            "No challenge can thwart our path to victory, no doubt about it!",
            "Our hearts are overflowing with joy and success, always!",
            "Baa-ttle-tested and forever triumphant, eternally!",
            "Ewe-niversal acclaim for our unwavering valor, without a doubt!",
            "Woolpower! We're the heroes of the meadow, always and forever!",
            "No enemy can break our unwavering determination, always!",
            "Our courage shines like the brightest star, eternally!",
            "Baa-lliantly victorious, as we always should be, forever!",
            "Fighting for the meadow is our eternal purpose, without a doubt!",
            "Ewe are the most fearless comrade I know, always!",
            "With you, we conquer all adversaries and challenges, eternally!",
            "Let our triumphant bleats echo far and wide, always and forever!",
            "Ewe and I make an unbeatable team, forevermore!",
            "Baa-d villains tremble before our indomitable fluff, no doubt about it!",
            "Our strength is the mightiest of all, no contest, eternally!",
        }
        local speak_dead = {
            "I'll watch over the meadow from the stars above.",
            "The meadow's tranquility is etched in my soul.",
            "May the meadow's grace always shine brightly.",
            "I found happiness in the meadow's loving heart.",
            "In the meadow's embrace, I found my home.",
            "Ewe are the guardians of the meadow's charm.",
            "The meadow's serenity is my final thought.",
            "May the meadow bloom with life in my memory.",
            "I'll rest in the meadow's loving embrace.",
            "The meadow's beauty will always be my solace.",
            "I hope for eternal peace in the meadow.",
            "In the meadow, I found solace and tranquility.",
            "My heart bleats for the meadow's well-being.",
            "Ewe-niverse, protect and cherish my meadow.",
            "My woolly spirit takes its place in the meadow.",
            "May the meadow's laughter fill the air forever.",
            "I'll miss the meadow's gentle embrace.",
            "In the meadow's heart, my spirit resides.",
            "Ewe-nique moments will remain in my memory.",
            "The meadow's beauty will live on in my dreams.",
            "I hope for eternal happiness in the meadow.",
            "Farewell, dear meadow, you were my sanctuary.",
            "May the meadow always be a place of happiness.",
            "In the meadow's arms, I found solace and joy.",
            "Ewe are the keepers of the meadow's grace.",
            "My woolly heart leaves a lasting bleat.",
            "The meadow will live on in my memories.",
            "I found happiness in the meadow's embrace.",
            "Woolpower! Carry on the meadow's legacy.",
            "Let the meadow's beauty continue to shine.",
            "My spirit is woven into the meadow's fabric.",
            "Ewe, my friends, will always be in my thoughts.",
            "Remember the meadow's beauty and serenity.",
            "Baa-d times won't tarnish my love for the meadow.",
            "Ewe-niversal, take care of my meadow.",
            "May the meadow always be safe and sound.",
            "I hope the meadow remains a haven for all.",
            "In the meadow's embrace, I felt truly alive.",
            "The meadow's charm will never fade from my heart.",
            "May the meadow be a sanctuary for all beings.",
            "I leave the meadow with love in my heart.",
            "My last moments in the meadow were peaceful.",
            "In the meadow, I found joy in every bleat.",
            "Ewe, my companions, will always be cherished.",
            "The meadow's beauty touched my woolly soul.",
            "May the meadow always echo with laughter.",
            "I'll rest in the meadow's embrace forever.",
            "The meadow's serenity is my everlasting thought.",
            "Ewe-niverse, protect and preserve my meadow.",
            "My spirit now resides in the meadow's embrace.",
            "May the meadow's beauty be eternal and bright.",
            "I found happiness in the meadow's gentle heart.",
            "In the meadow's loving arms, I was content.",
            "Ewe are the guardians of the meadow's spirit.",
            "My love for the meadow endures beyond time.",
            "The meadow's charm will remain in my heart.",
            "May the meadow's laughter be eternal and joyous.",
            "I'll miss the meadow's warmth and gentle breeze.",
            "In the meadow's heart, my spirit finds solace.",
            "Ewe-nique moments fill my memories with warmth.",
            "The meadow's grace will forever be cherished.",
            "I hope the meadow continues to bring happiness.",
            "Farewell, dear meadow, you were my cherished home.",
            "The meadow's tranquility will always comfort me.",
            "May the meadow's beauty continue to shine bright.",
            "I found contentment in the meadow's loving presence.",
            "In the meadow's embrace, I discovered peace.",
            "Ewe, my friends, will forever hold a special place.",
            "Remember the meadow's beauty and its gentle heart.",
            "Baa-d times won't overshadow my love for the meadow.",
            "May the meadow always be a sanctuary for all creatures.",
            "I leave the meadow with gratitude and love.",
            "My final moments in the meadow were filled with serenity.",
            "In the meadow, I found beauty in every bleat.",
            "Ewe, my companions, will always be cherished and missed.",
            "The meadow's beauty touched my woolly soul deeply.",
            "May the meadow always echo with the sounds of joy.",
            "I'll rest in the meadow's embrace eternally.",
            "The meadow's serenity is my everlasting memory.",
            "Ewe-niverse, protect and preserve my beloved meadow always.",
            "My spirit now resides in the meadow's loving embrace.",
            "May the meadow's beauty be eternal and bright, forever.",
            "I found happiness in the meadow's gentle heart, always.",
            "In the meadow's loving arms, I was content, eternally.",
            "Ewe are the keepers of the meadow's spirit, forevermore.",
            "My love for the meadow endures beyond time, always.",
            "The meadow's charm will forever remain in my heart.",
            "May the meadow's laughter be eternal and joyous, forever.",
            "I'll miss the meadow's warmth and gentle breeze, always.",
            "In the meadow's heart, my spirit finds solace, eternally.",
            "Ewe-nique moments fill my memories with warmth, forever.",
            "The meadow's grace will forever be cherished, always.",
            "I hope the meadow continues to bring happiness, eternally.",
            "Farewell, dear meadow, you were my cherished home, always.",
            "The meadow's tranquility will always comfort me, forever.",
            "May the meadow's beauty continue to shine bright, always.",
            "I found contentment in the meadow's loving presence, eternally.",
            "In the meadow's embrace, I discovered peace, forever.",
            "Ewe, my friends, will forever hold a special place, always."
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
