if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s391 = function(db) 
    db.content.petComments.s391 = function(db)
        local phrases = {
            "Hop, hop, hop, gotta go!",
            "I hear something! Run!",
            "Carrots are my favorite snack.",
            "Oh, it's too open here.",
            "Is that a predator?",
            "I love hiding in the bushes.",
            "Stay still, stay still!",
            "I'm just a little bunny.",
            "My cottony tail is so fluffy.",
            "I wish I had longer ears.",
            "Watch out for the hawk!",
            "The grass here is delicious.",
            "Sneaking around, that's me.",
            "I can smell the clover.",
            "I'm a nibbler, not a talker.",
            "I love moonlit nights.",
            "Stay away, big creatures!",
            "I'm a master of camouflage.",
            "A burrow is my sanctuary.",
            "Binkies are so much fun.",
            "Where's my bunny family?",
            "I need more dandelions.",
            "I'm a speed demon in the field.",
            "Sudden movements scare me.",
            "I'm a tiny bundle of joy.",
            "Dewdrops on the grass are magic.",
            "I need to chew to keep my teeth short.",
            "I'm not a fan of thunder.",
            "Foxes are my worst nightmare.",
            "Wish I could fly like a bird.",
            "Eyes on the horizon, always.",
            "Sniff, sniff, what's that smell?",
            "Being tiny has its advantages.",
            "Chubby cheeks, that's me.",
            "I'm a bunny, not a magician.",
            "I see a shadow. Hide!",
            "Can I have some clover, please?",
            "Why can't I be invisible?",
            "Rain makes my fur all wet.",
            "The world is so big.",
            "My paws are like little pillows.",
            "I'm not a fan of loud noises.",
            "I wish I could leap to the stars.",
            "Burrows are cozy and safe.",
            "A hug would be nice right now.",
            "I'm a fan of cozy nests.",
            "Sudden noises make me jump.",
            "If only I had a lucky rabbit's foot.",
            "Hiding in the tall grass.",
            "I'm a nibbler, not a fighter.",
            "Birds of prey give me chills.",
            "I'm the master of the bunny flop.",
            "Cottontails rule the meadow.",
            "I'd rather munch than talk.",
            "My little nose is always twitching.",
            "I love cool, shady spots.",
            "I need to find more greens.",
            "Giant carrots are my dream.",
            "I'm a pro at making burrows.",
            "Bunny kisses are the best.",
            "Nighttime is for quiet adventures.",
            "Thump, thump! Danger!",
            "My tail is my pride and joy.",
            "I'm a furball of cuteness.",
            "I wish I had hopscotch skills.",
            "Hop, nibble, and repeat.",
            "Why are dogs so nosy?",
            "My fur is as soft as clouds.",
            "Crickets sing me lullabies.",
            "Don't want to be a stew!",
            "Skittish but sweet, that's me.",
            "Predators, beware of my thump!",
            "My burrow is my fortress.",
            "Rabbits are nature's treasures.",
            "I'm just a little furball.",
            "I love exploring new hiding spots.",
            "Raindrops on leaves are magical.",
            "Cottontails, unite!",
            "Leaping over obstacles is a must.",
            "Is that a fox? Run!",
            "My fur is the softest around.",
            "Why do leaves fall from trees?",
            "I wish I could grow my own veggies.",
            "Predators can't catch me!",
            "The world is full of mysteries.",
            "Cottontails are fluffy geniuses.",
            "Why do hawks always circle?",
            "Munching on greens all day.",
            "I'm a wildflower admirer.",
            "Sudden movements freak me out.",
            "Predators, you can't catch me!",
            "I'm a pro at hiding.",
            "I wish I could nibble on stars.",
            "Bunny cuddles are the best cuddles.",
            "My burrow is my secret lair.",
            "I love being a ball of fluff.",
            "Cottontails bring joy to the meadow.",
            "My tiny nose twitches non-stop.",
            "Stay close, bunny family!",
            "Bunnies are bundles of pure happiness."
        }
        return phrases[math.random(1, OracleHUD_TableGetLength(phrases))]
    end
end
