if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s412 = function(db) 
    db.content.petComments.s412 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "weaves an intricate web in the moonlight.",
            "dances gracefully on eight nimble legs.",
            "senses vibrations in the air with acute perception.",
            "sprays silk to create a hidden sanctuary.",
            "grooms its delicate silk with meticulous care.",
            "balances on a single strand, defying gravity.",
            "casts a silken line to explore the surroundings.",
            "whispers softly in the language of the arachnids.",
            "curls up in a hidden nook to rest.",
            "extends its silk, creating a delicate bridge.",
            "performs a mesmerizing leg dance in the moonlight.",
            "spins a silk hammock for a peaceful slumber.",
            "pauses to feel the gentle caress of the night breeze.",
            "flicks its silk to sense changes in the environment.",
            "creates a silk tapestry adorned with dewdrops.",
            "weaves a silk cocoon around a captured prey.",
            "uses silk as a lifeline to explore vertical spaces.",
            "taps its legs in a rhythmic pattern, communicating with others.",
            "wraps silk around its body, creating a protective layer.",
            "stands still, blending seamlessly with its surroundings.",
            "waves its front legs in a gesture of greeting.",
            "releases a silk thread, marking its territory.",
            "inspects its silk for any imperfections.",
            "rolls a silk ball, playfully batting it around.",
            "spins a quick web to capture unsuspecting prey.",
            "raises its front legs in a defensive stance.",
            "performs an intricate mating dance with a fellow spider.",
            "weaves a spiral pattern in its silk masterpiece.",
            "sends gentle vibrations through its silk to communicate.",
            "scuttles sideways with swift and nimble movements.",
            "creates a silk trap with meticulous precision.",
            "stands on tiptoe, reaching the highest point in its web.",
            "spins silk into a seamless patchwork of intricate patterns.",
            "taps its silk strands to create a melodic rhythm.",
            "wraps silk around its body, camouflaging with the environment.",
            "crafts a silk shelter for protection from the elements.",
            "extends silk threads to create a makeshift ladder.",
            "licks its silk to reinforce its adhesive properties.",
            "weaves a message into its silk using subtle patterns.",
            "balances on the edge of its web, scanning for vibrations.",
            "pulls silk from its spinnerets with methodical precision.",
            "spins a silk spiral, drawing patterns in the moonlit air.",
            "releases silk to create a floating parachute for controlled descent.",
            "combs its silk with specialized bristles on its legs.",
            "spins a silk cocoon around its body for safety during sleep.",
            "retracts its silk rapidly, creating a protective barrier.",
            "weaves a silk shield to deflect potential threats.",
            "pulses silk in a rhythm that mimics the heartbeat of the night.",
            "dangles upside-down, inspecting the world below.",
            "spins a silk thread with remarkable speed and agility.",
            "extends silk outward, creating a sensory net.",
            "performs a graceful aerial dance, suspended by silk threads.",
            "gathers silk from its spinnerets to create a dense barrier.",
            "weaves a delicate silk scarf, fluttering in the breeze.",
            "releases silk strands to create a safety line while exploring.",
            "rolls a silk ball to engage in a game of catch.",
            "spins silk around a prey item, immobilizing it with precision.",
            "balances on a single silk strand, swaying with the breeze.",
            "weaves a silk mat for comfort during rest.",
            "releases silk to create a trail, marking its path.",
            "spins silk into a fine thread for delicate tasks.",
            "wraps silk around its body like a cloak for warmth.",
            "creates a silk pouch to carry small items.",
            "extends silk in a spiral pattern, creating a decorative masterpiece.",
            "flicks silk to create a dazzling display of shimmering threads.",
            "weaves a complex geometric pattern with intricate symmetry.",
            "releases silk to form a temporary bridge over a gap.",
            "spins a silk net, casting it with precision to catch prey.",
            "balances on multiple silk strands, showcasing incredible agility.",
            "weaves a delicate silk veil, creating an ethereal atmosphere.",
            "retracts silk swiftly, creating a retractable lifeline.",
            "spins a silk trampoline for acrobatic leaps and jumps.",
            "extends silk threads to create a protective barrier around its nest.",
            "weaves a silk garland, adorning its surroundings with delicate strands.",
            "releases silk to create a shimmering curtain, concealing its presence.",
            "spins a silk cloak, concealing itself from prying eyes.",
            "balances on a silk tightrope, showcasing remarkable balance.",
            "weaves a spiral staircase of silk for easy navigation.",
            "retracts silk rapidly, creating a defensive cocoon.",
            "spins silk into a circular frame, creating a portal-like structure.",
            "extends silk threads to create a delicate chandelier, shimmering in the moonlight.",
            "weaves a silk hammock between two points for a cozy rest.",
            "releases silk strands to create a web-based map of its surroundings.",
            "spins silk into a series of loops, creating a playful obstacle course.",
            "balances on a single strand, swaying gently like a spiderly pendulum."
        }
        local emote_summon = {
            "stretches its legs, slowly awakening from slumber.",
            "grooms its silk, ensuring it's pristine after a restful sleep.",
            "yawns, revealing its impressive fangs in the morning light.",
            "vibrates its body, shaking off the drowsiness of the night.",
            "flexes its pedipalps, preparing for the activities of the day.",
            "senses the first rays of sunlight, signaling the start of a new cycle.",
            "slowly uncurls from a tucked position, unfolding its legs.",
            "awakens with a gentle rustle of silk, as if whispering to the dawn.",
            "opens multiple eyes, adjusting to the brightness of the waking world.",
            "stirs in its silk bed, ready to face the challenges ahead.",
            "twists its body, ensuring all eight legs are fully functional.",
            "taps its front legs rhythmically, a morning arachnid ritual.",
            "releases a contented hum, a harmonious greeting to the day.",
            "feels the morning dew on its silk, a refreshing sensation.",
            "scans the surroundings, assessing potential prey and dangers.",
            "sips morning dew from silk strands, quenching its thirst.",
            "senses the temperature change, adapting to the new day's climate.",
            "tests its silk threads, ensuring they're strong and resilient.",
            "shivers its body, shaking off the coolness of the night.",
            "wiggles its pedipalps, a morning warm-up for sensory acuity.",
            "sniffs the air, detecting scents carried by the morning breeze.",
            "engages in a series of leg stretches, flexing its joints.",
            "rolls over onto its back, basking in the warmth of the morning sun.",
            "twitches its spinnerets, preparing for a day of silk production.",
            "creates a subtle hum, harmonizing with the natural sounds of dawn.",
            "snuggles into its silk nest, savoring the residual warmth.",
            "checks its surroundings with careful, calculated movements.",
            "vibrates its abdomen, a gentle wake-up call to nearby arachnids.",
            "scratches its head with a pedipalp, a cute morning gesture.",
            "shakes off any leftover dreamlike sensations from its sleep.",
            "engages in a slow, deliberate leg stretch, testing its flexibility.",
            "gazes at the morning sky, contemplating the day ahead.",
            "licks its chelicerae, ensuring they're clean and ready for action.",
            "scans the web for any signs of disturbances during the night.",
            "weaves a delicate morning dew-catching silk trap for hydration.",
            "raises and lowers its body, a morning calisthenics routine.",
            "sniffs its silk bed, familiarizing itself with its own scent.",
            "gathers any leftover night-time prey caught in its web for breakfast.",
            "arches its body in a graceful stretch, awakening its senses.",
            "creates a gentle rustling of silk, announcing its return to the world.",
            "gazes at the sunrise, absorbing the warmth on its exoskeleton.",
            "vibrates its spinnerets, fine-tuning its silk production readiness.",
            "twists its body in a series of elegant movements, like a dancer.",
            "engages in a slow, synchronized leg movement, a spiderly morning yoga.",
            "wipes its eyes with a front leg, clearing any sleep residue.",
            "twitches its antenniform legs, checking for signs of life in its surroundings.",
            "creates a symphony of vibrations, announcing its morning presence.",
            "licks its pedipalps, a subtle self-cleaning ritual after waking up.",
            "scans the web with precision, evaluating the integrity of its silk.",
            "vibrates its entire body, a morning shake-off to increase alertness.",
            "grooms its fangs meticulously, preparing them for the day's activities.",
            "stirs up the air with a few flaps of its legs, dispelling the morning chill.",
            "sensitively taps its legs on the ground, gauging the terrain.",
            "releases a faint silk scent, marking its territory for the new day.",
            "engages in a slow, rhythmic tapping, a spiderly morning percussion.",
            "licks its chelicerae with precision, ensuring they're clean and functional.",
            "stretches its cephalothorax upwards, reaching for the first sunlight.",
            "vibrates its entire body in a synchronized rhythm with the waking world.",
            "spins a small silk circle, a morning ritual to connect with its surroundings.",
            "senses the morning breeze, gauging the weather for the day.",
            "releases a gentle hum, a spiderly morning mantra.",
            "opens and closes its book lungs, adjusting to the fresh morning air.",
            "taps its legs in a pattern, creating a soft morning melody.",
            "gazes at the dew-kissed world, appreciating the beauty of the morning.",
            "sniffs its silk strands, recognizing the familiar scent of its home.",
            "engages in a slow leg wave, a spiderly morning wave to the world.",
            "vibrates its spinnerets in a delicate dance, preparing for silk production.",
            "twitches its sensory hairs, collecting information about its environment.",
            "creates a gentle rustling of silk, a morning symphony in the breeze.",
            "grooms its pedipalps, ensuring they're free of any silk residue.",
            "licks its front legs, a morning ritual to cleanse and refresh.",
            "stirs the air with its legs, clearing away the last traces of night.",
            "rolls its eyes, a cute morning gesture signaling full alertness.",
            "taps its pedipalps on the ground, a morning drumbeat in nature's orchestra.",
            "releases a delicate hum, resonating with the energy of the morning.",
            "senses the morning vibrations, attuning itself to the pulse of the day.",
            "twists its body in a circular motion, aligning itself with the sun's path.",
            "grooms its spinnerets meticulously, ensuring smooth silk production.",
            "licks its pedipalps, a morning gesture of self-affection.",
            "scans the surroundings with a watchful gaze, alert to potential threats.",
            "vibrates its entire body in a silent morning celebration of life.",
            "twists its pedipalps in an intricate dance, expressing morning vitality."
        }        
        local speak = {
            "Greetings, fellow web-dweller!",
            "The silk whispers secrets of the night.",
            "In the tapestry of life, we are but threads.",
            "Did you feel the vibrations in the air?",
            "Eight legs carry the weight of wisdom.",
            "Behold the intricacies of my silk artistry.",
            "The moonlight guides my nocturnal endeavors.",
            "Do you dance with your spinnerets under the stars?",
            "A spider's web is a masterpiece of design.",
            "Silk is the language of the arachnids.",
            "In every dewdrop, a world is reflected.",
            "The night sky is our eternal canvas.",
            "A spider's gaze sees beyond the visible.",
            "In the shadows, secrets are woven.",
            "The moonlit dance is a symphony of silk.",
            "Greetings, fellow spinner of dreams!",
            "The night air carries tales of unseen wonders.",
            "Feel the silk, and you'll understand my world.",
            "Do you sense the whispers of the moonlit breeze?",
            "Behold the intricacies of my silk tapestry.",
            "Our legs move in harmony with the dance of the cosmos.",
            "Silk strands weave the stories of the night.",
            "The moon is our lantern in the nocturnal realm.",
            "A spider's world is spun from dreams and silk.",
            "In the silk, echoes of the night linger.",
            "The night sky holds the map to endless adventures.",
            "Eight eyes see the beauty in the shadows.",
            "Behold the celestial ballet of the night.",
            "Silk is the bridge between earth and the moon.",
            "In the moon's embrace, we find solace.",
            "The night is a tapestry, and we are its weavers.",
            "Greetings, kindred spirit of the nocturnal realm!",
            "Silk is the embodiment of patience and precision.",
            "Do you feel the silk's gentle caress on your soul?",
            "A spider's silk is a testament to resilience.",
            "In the tapestry of time, we leave our mark.",
            "Moonlight is the ink with which we write our tales.",
            "Silk threads bind us to the heart of the night.",
            "The dance of silk is a language of its own.",
            "Greetings, traveler of the moonlit pathways!",
            "The night sky is a canvas painted with stardust.",
            "In the embrace of silk, dreams take flight.",
            "Do you hear the melody of the night breeze?",
            "Behold the moonlit symphony of eight-legged grace.",
            "Silk is the bridge that connects us to the cosmos.",
            "The night's secrets are written in the silk strands.",
            "A spider's world is spun from the threads of destiny.",
            "In the moonlit dance, we find our true selves.",
            "Greetings, seeker of the hidden realms!",
            "Silk strands catch the whispers of the night.",
            "Do you dance with the shadows under the moon's gaze?",
            "Behold the magic woven into every silk fiber.",
            "The moon is our guide through the labyrinth of dreams.",
            "Eight legs move in harmony with the cosmic rhythm.",
            "Silk is the language that binds us together.",
            "The night is a blank canvas waiting for silk strokes.",
            "Greetings, wanderer of the night's embrace!",
            "In the tapestry of existence, we are but threads.",
            "Do you feel the heartbeat of the nocturnal world?",
            "Behold the beauty woven into the fabric of the night.",
            "Silk strands carry the weight of countless stories.",
            "The moon is a silent witness to our nightly endeavors.",
            "A spider's web is a testament to artistry and precision.",
            "In the dance of silk, we find our rhythm.",
            "Greetings, fellow dreamweaver of the night!",
            "Silk is the medium through which we communicate.",
            "Do you see the constellations woven into my silk?",
            "Behold the delicate architecture of the nocturnal realm.",
            "The moon's glow illuminates the path of the silk dancer.",
            "Eight eyes see the world in shades of moonlight.",
            "Silk is the canvas upon which dreams are painted.",
            "The night sky is our gallery of celestial wonders.",
            "Greetings, kin of the moonlit tapestry!",
            "In the silk, the stories of the night are written.",
            "Do you feel the gentle touch of the nocturnal breeze?",
            "Behold the silent poetry of the spider's dance.",
            "The moon is a lantern guiding us through the night's labyrinth.",
            "A spider's silk is a reflection of patience and artistry.",
            "In the dance of the cosmos, we find our place."
        }
        local speak_win = {
            "The defeated tremble in the shadow of my silk!",
            "In the symphony of triumph, my silk strands resonate!",
            "Silk-woven banners of victory flutter in the night!",
            "The defeated insects tell tales of my indomitable spirit!",
            "Behold the silk tapestry of triumph that I have woven!",
            "The dance of conquest is a celebration of destiny!",
            "Silk threads of triumph span the breadth of existence!",
            "The defeated crawl in the echo of my triumphant dance!",
            "In the aftermath of battle, my silk is unblemished!",
            "Silk strands of triumph weave through the tapestry of fate!",
            "The dance of victory is a ballet in the moonlit night!",
            "Silk-woven trophies of triumph shine in the moonlit sky!",
            "The defeated insects echo the song of my dominance!",
            "Our silk is an emblem of indomitable will!",
            "The dance of triumph is a celebration of destiny!",
            "Silk threads of conquest span the breadth of existence!",
            "The defeated insects scatter like petals in the breeze!",
            "In the symphony of victory, my silk is the crescendo!",
            "Silk-woven crowns of triumph rest upon my fangs!",
            "The defeated insects are but echoes in the web of fate!",
            "Our silk is a tapestry woven with the threads of victory!",
            "The dance of conquest is a ballet in the moonlight!",
            "Silk strands of triumph are the signatures of my triumph!",
            "The defeated insects crawl in the shadow of my silk!",
            "In the tapestry of victory, my silk is the central motif!",
            "Silk threads of conquest shimmer in the moonlit breeze!",
            "The defeated insects tremble at the might of my silk!",
            "Our silk is a beacon that guides us to triumph!",
            "The dance of silk is the dance of triumphant hearts!",
            "Silk-woven banners of victory flutter in the night!",
            "The defeated insects sing songs of my conquest!",
            "In the aftermath of battle, my silk is unblemished!",
            "Silk strands of triumph weave through the tapestry of fate!",
            "The defeated insects crawl in the echo of my triumph!",
            "Our silk is a testament to the strength of our will!",
            "The dance of victory is a ballet in the moonlit night!",
            "Silk threads of conquest bind us to the heart of glory!",
            "The defeated insects tell tales of my indomitable spirit!",
            "In the symphony of victory, every silk strand resonates!",
            "Silk-woven trophies of triumph shine in the moonlit sky!",
            "The defeated insects echo the song of my dominance!",
            "Our silk is an emblem of indomitable will!",
            "The dance of triumph is a celebration of destiny!",
            "Silk threads of conquest span the breadth of existence!",
            "The defeated insects scatter like petals in the breeze!",
            "In the symphony of victory, my silk is the crescendo!",
            "Silk-woven crowns of triumph rest upon my fangs!",
            "The defeated insects are but echoes in the web of fate!",
            "Our silk is a tapestry woven with the threads of victory!",
            "The dance of conquest is a ballet in the moonlight!",
            "Silk strands of triumph are the signatures of my triumph!",
            "The defeated insects crawl in the shadow of my silk!",
            "In the tapestry of victory, my silk is the central motif!",
            "Silk threads of conquest shimmer in the moonlit breeze!",
            "The defeated insects tremble at the might of my silk!",
            "Our silk is a beacon that guides us to triumph!",
            "The dance of silk is the dance of triumphant hearts!",
            "Silk-woven banners of victory flutter in the night!",
            "The defeated insects sing songs of my conquest!",
            "In the aftermath of battle, my silk is unblemished!",
            "Silk strands of triumph weave through the tapestry of fate!",
            "The defeated insects crawl in the echo of my triumph!",
            "Our silk is a testament to the strength of our will!",
            "The dance of victory is a ballet in the moonlit night!",
            "Silk threads of conquest bind us to the heart of glory!",
            "The defeated insects tell tales of my indomitable spirit!",
            "In the symphony of victory, every silk strand resonates!",
            "Silk-woven trophies of triumph shine in the moonlit sky!",
            "The defeated insects echo the song of my dominance!",
            "Our silk is an emblem of indomitable will!",
            "The dance of triumph is a celebration of destiny!",
            "Silk threads of conquest span the breadth of existence!",
            "The defeated insects scatter like petals in the breeze!",
            "In the symphony of victory, my silk is the crescendo!",
            "Silk-woven crowns of triumph rest upon my fangs!",
            "The defeated insects are but echoes in the web of fate!",
            "Our silk is a tapestry woven with the threads of victory!",
            "The dance of conquest is a ballet in the moonlight!",
            "Silk strands of triumph are the signatures of my triumph!",
            "The defeated insects crawl in the shadow of my silk!",
            "In the tapestry of victory, my silk is the central motif!",
            "Silk threads of conquest shimmer in the moonlit breeze!",
            "The defeated insects tremble at the might of my silk!",
            "Our silk is a beacon that guides us to triumph!",
            "The dance of silk is the dance of triumphant hearts!",
            "Silk-woven banners of victory flutter in the night!",
            "The defeated insects sing songs of my conquest!",
            "In the aftermath of battle, my silk is unblemished!",
            "Silk strands of triumph weave through the tapestry of fate!",
            "The defeated insects crawl in the echo of my triumph!",
            "Our silk is a testament to the strength of our will!",
            "The dance of victory is a ballet in the moonlit night!",
            "Silk threads of conquest bind us to the heart of glory!",
            "The defeated insects tell tales of my indomitable spirit!",
            "In the symphony of victory, every silk strand resonates!",
            "Silk-woven trophies of triumph shine in the moonlit sky!",
            "The defeated insects echo the song of my dominance!",
            "Our silk is an emblem of indomitable will!",
            "The dance of triumph is a celebration of destiny!",
            "Silk threads of conquest span the breadth of existence!",
            "The defeated insects scatter like petals in the breeze!",
            "In the symphony of victory, my silk is the crescendo!",
            "Silk-woven crowns of triumph rest upon my fangs!",
            "The defeated insects are but echoes in the web of fate!",
            "Our silk is a tapestry woven with the threads of victory!",
            "The dance of conquest is a ballet in the moonlight!",
            "Silk strands of triumph are the signatures of my triumph!",
            "The defeated insects crawl in the shadow of my silk!",
            "In the tapestry of victory, my silk is the central motif!",
            "Silk threads of conquest shimmer in the moonlit breeze!",
            "The defeated insects tremble at the might of my silk!",
            "Our silk is a beacon that guides us to triumph!",
            "The dance of silk is the dance of triumphant hearts!",
            "Silk-woven banners of victory flutter in the night!",
            "The defeated insects sing songs of my conquest!"
        }
        local speak_dead = {
            "In the threads of life, my time has come to an end.",
            "As I depart, may my silk memories linger in the night.",
            "In the embrace of the shadows, I bid farewell.",
            "As my silk fades, let the memories weave a tapestry of remembrance.",
            "In the moonlit realm, my journey comes to a gentle close.",
            "As my legs grow still, may the night cradle my essence.",
            "In the silk of time, my presence unravels like delicate threads.",
            "As I rest in the darkness, let the stars be my guide.",
            "In the silent web, my spirit weaves into the night's canvas.",
            "As my silk fades, may the echoes of my dance endure.",
            "In the dance of existence, my steps softly fade away.",
            "As my spinnerets still, may the memories weave a graceful elegy.",
            "In the moonlit dance, my silhouette vanishes into the night.",
            "As I leave this realm, let the shadows embrace my departure.",
            "In the hushed night, my farewell is a whispered breeze.",
            "As my legs grow weary, let the moon carry my essence.",
            "In the web of time, my threads become echoes of the past.",
            "As my silk unravels, may the night hold my final sigh.",
            "In the tapestry of life, my presence becomes a subtle pattern.",
            "As I fade, let the stars twinkle in remembrance.",
            "In the quiet shadows, my departure is a gentle rustle.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps.",
            "In the moonlit tapestry, my threads dissolve into memories.",
            "As I depart, may the night sky be my eternal canvas.",
            "In the soft moonlight, my silhouette waltzes into eternity.",
            "As my legs still, let the night cradle my silent essence.",
            "In the delicate threads of time, my presence fades away.",
            "As my silk vanishes, may the night breeze carry my essence.",
            "In the dance of shadows, my steps echo into the night.",
            "As I depart, let the stars be witnesses to my final waltz.",
            "In the moonlit ballet, my silhouette becomes stardust.",
            "As my spinnerets rest, may the night weave my final lullaby.",
            "In the web of existence, my threads dissolve into the unknown.",
            "As my silk frays, let the night hold my delicate remains.",
            "In the hushed darkness, my departure is a quiet symphony.",
            "As I fade away, may the night sky become my eternal resting place.",
            "In the moonlit waltz, my steps echo softly into eternity.",
            "As my legs grow still, let the night be my silent witness.",
            "In the gentle night, my farewell is a whispered melody.",
            "As my silk unravels, may the night embrace my final sigh.",
            "In the tapestry of shadows, my presence becomes a subtle whisper.",
            "As I depart, let the moonlight cradle my fleeting essence.",
            "In the dance of time, my steps dissolve into the night's embrace.",
            "As my spinnerets cease, may the night keep my secrets.",
            "In the moon's glow, my final dance is a silent ballet.",
            "As my silk withers, let the night remember my intricate steps."
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
