if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s41 = function(db) 
    db.content.petComments.s41 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "Gracefully leaps onto a high perch, surveying the surroundings with feline elegance.",
            "Chirps playfully, inviting others to join in the dance of feline merriment.",
            "Nuzzles against a companion, sharing warmth and affection in the language of cats.",
            "Curves its back, presenting the sleek silhouette of a contented Cornish Rex.",
            "Pounces on an imaginary prey, a swift and agile hunter in the realms of imagination.",
            "Grooms its fur meticulously, a display of the Cornish Rex's natural elegance.",
            "Bats at a dangling toy, eyes focused with playful determination.",
            "Purrs softly, a soothing melody that resonates with feline tranquility.",
            "Stretches each limb gracefully, a balletic display of feline flexibility.",
            "Sniffs the air delicately, deciphering the scents that weave the tapestry of the world.",
            "Wags its tail with excitement, a feline semaphore signaling pure joy.",
            "Rolls onto its back, paws in the air, inviting others to join in the whimsical revelry.",
            "Chases a beam of sunlight, a playful pursuit of the elusive morning rays.",
            "Nudges against a hand for a gentle petting, a feline request for affection.",
            "Curls into a cozy nook, eyes half-closed, reveling in the bliss of a perfect resting spot.",
            "Paws at a mysterious shadow, a curious explorer venturing into the unknown.",
            "Bounces from surface to surface, a dynamic dance that echoes the playful heart of a cat.",
            "Gazes into the distance, eyes filled with the wonder of a world seen through feline eyes.",
            "Snuggles into a plush cushion, a contented sigh echoing the comfort of the moment.",
            "Chirrs in contentment, a harmonious melody that encapsulates the joy of being a cat.",
            "Leaps gracefully over obstacles, a demonstration of the Cornish Rex's agile prowess.",
            "Nibbles at a favorite treat, savoring the delectable flavors with feline delight.",
            "Wiggles its tail with anticipation, a feline semaphore expressing eagerness.",
            "Lies in a sunbeam, eyes half-closed, basking in the warmth of feline radiance.",
            "Pounces on a toy mouse, a playful reenactment of the eternal battle between cat and prey.",
            "Grooms a fellow feline, a shared moment of camaraderie in the feline brotherhood.",
            "Stares at its reflection, a moment of self-appreciation in the mirror of cat vanity.",
            "Chirps a greeting to passersby, a feline salutation to friends old and new.",
            "Nuzzles against a leg, seeking connection in the gentle touch of a feline companion.",
            "Curls around a favored human, a gesture of love and trust in the warmth of friendship.",
            "Paws at a feathered toy, engaging in a mesmerizing dance with the whimsical contraption.",
            "Rolls onto its belly, inviting belly rubs with a display of vulnerability and trust.",
            "Bounces on its hind legs, a playful dance that defies gravity with feline finesse.",
            "Gazes at the moon, eyes reflecting the mysterious allure of the nocturnal sky.",
            "Purrs louder, a deep rumble of satisfaction that echoes the heart of contentment.",
            "Sniffs at a flower, exploring the scents that nature weaves into the air.",
            "Leaps onto a perch, a feline ascent into the elevated realms of the cat kingdom.",
            "Bats at falling leaves, a whimsical interaction with the changing seasons.",
            "Chirps at a passing bird, engaging in a conversation with the feathered passerby.",
            "Nuzzles against a cheek, a feline kiss that speaks volumes in the language of cats.",
            "Curls into a tight ball, eyes closed, embodying the epitome of feline relaxation.",
            "Paws at a ball of yarn, entangled in a playful game of feline mischief.",
            "Rolls onto its side, legs splayed out, a carefree surrender to the whims of the moment.",
            "Bounces off the walls, a burst of exuberance that reverberates through the room.",
            "Grooms a paw delicately, a refined display of feline cleanliness and grace.",
            "Stares at a distant insect, eyes following the intricate flight patterns with feline fascination.",
            "Chirrs in response to a gentle touch, a musical exchange in the language of affection.",
            "Nudges against a closed door, a persistent plea to explore the mysteries beyond.",
            "Wags its tail in irritation, a feline semaphore signaling mild displeasure.",
            "Leaps onto a bookshelf, a scholarly ascent into the realms of feline wisdom.",
            "Nibbles on a catnip-infused toy, succumbing to the euphoria of feline indulgence.",
            "Snuggles into a cozy blanket fort, a fortress of warmth and security.",
            "Chases its own tail in circles, an eternal pursuit of the elusive appendage.",
            "Paws at a water bowl, engaging in a playful splash that defies feline logic.",
            "Rolls on the ground, back and forth, a dynamic dance that defies explanation.",
            "Bounces on a scratching post, a feline acrobat mastering the art of balance.",
            "Gazes at the stars through a window, eyes reflecting the cosmic mysteries of the night.",
            "Purrs in the company of a trusted human, a harmonic symphony of mutual affection.",
            "Sniffs at a new arrival, a feline investigation into the scents of the unknown.",
            "Leaps onto a bed, a regal descent into the realms of feline slumber.",
            "Nuzzles against a favored toy, a sentimental gesture in the language of play.",
            "Curls around a human's shoulders, a feline scarf providing warmth and companionship.",
            "Bats at a curtain, engaging in a dramatic play with the fabric of feline theatrics.",
            "Wiggles its ears with curiosity, a feline semaphore expressing inquisitiveness.",
            "Paws at a reflection in a mirror, a playful interaction with the enigma of self.",
            "Rolls in a patch of sunlight, a blissful ritual of absorbing the day's warmth.",
            "Bounces on a window ledge, a vigilant guardian overseeing the feline domain.",
            "Chirps at a passing breeze, a feline conversation with the whispers of the wind.",
            "Nuzzles against a hand for a gentle scratch, a feline request for tactile pleasure.",
            "Curls into a crescent moon shape, a celestial pose in the cosmic dance of sleep.",
            "Purrs in the lap of a human, a comforting serenade that transcends the language barrier.",
            "Sniffs at a freshly opened book, exploring the scents that words carry in the air.",
            "Leaps onto a tabletop, a daring adventure into the elevated realms of exploration.",
            "Bounces on a bedspread, a feline trampoline of joyous exuberance.",
            "Grooms a fellow feline, a shared moment of post-play bonding.",
            "Stares into a fishbowl, eyes following the aquatic ballet with feline fascination.",
            "Chirrs in the presence of a fellow cat, a harmonic exchange in the language of camaraderie.",
            "Nudges against a closed door, a persistent plea for the mysteries beyond.",
            "Wags its tail with excitement, a feline semaphore signaling pure joy.",
            "Leaps onto a windowsill, eyes captivated by the outside world's panorama.",
            "Nibbles on a tasty morsel, savoring the flavors with the discernment of a feline gourmet.",
            "Snuggles into a cozy nook, eyes half-closed, reveling in the bliss of a perfect resting spot.",
            "Chirps at a fluttering butterfly, a feline conversation with the ephemeral beauty.",
            "Paws at a crinkly toy, an auditory exploration that delights the feline senses.",
            "Rolls onto its side, legs splayed out, a carefree surrender to the whims of the moment.",
            "Bounces off the walls, a burst of exuberance that reverberates through the room.",
            "Grooms a paw delicately, a refined display of feline cleanliness and grace.",
            "Stares at a distant insect, eyes following the intricate flight patterns with feline fascination.",
            "Chirrs in response to a gentle touch, a musical exchange in the language of affection.",
            "Nudges against a closed door, a persistent plea to explore the mysteries beyond.",
            "Wags its tail in irritation, a feline semaphore signaling mild displeasure.",
            "Leaps onto a bookshelf, a scholarly ascent into the realms of feline wisdom.",
            "Nibbles on a catnip-infused toy, succumbing to the euphoria of feline indulgence.",
            "Snuggles into a cozy blanket fort, a fortress of warmth and security.",
            "Chases its own tail in circles, an eternal pursuit of the elusive appendage.",
            "Paws at a water bowl, engaging in a playful splash that defies feline logic.",
            "Rolls on the ground, back and forth, a dynamic dance that defies explanation.",
            "Bounces on a scratching post, a feline acrobat mastering the art of balance.",
            "Gazes at the stars through a window, eyes reflecting the cosmic mysteries of the night.",
            "Purrs in the company of a trusted human, a harmonic symphony of mutual affection.",
            "Sniffs at a new arrival, a feline investigation into the scents of the unknown.",
            "Leaps onto a bed, a regal descent into the realms of feline slumber.",
            "Nuzzles against a favored toy, a sentimental gesture in the language of play.",
            "Curls around a human's shoulders, a feline scarf providing warmth and companionship.",
            "Bats at a curtain, engaging in a dramatic play with the fabric of feline theatrics.",
            "Wiggles its ears with curiosity, a feline semaphore expressing inquisitiveness.",
            "Paws at a reflection in a mirror, a playful interaction with the enigma of self.",
            "Rolls in a patch of sunlight, a blissful ritual of absorbing the day's warmth.",
            "Bounces on a window ledge, a vigilant guardian overseeing the feline domain.",
            "Chirps at a passing breeze, a feline conversation with the whispers of the wind.",
            "Nuzzles against a hand for a gentle scratch, a feline request for tactile pleasure.",
            "Curls into a crescent moon shape, a celestial pose in the cosmic dance of sleep.",
            "Purrs in the lap of a human, a comforting serenade that transcends the language barrier.",
            "Sniffs at a freshly opened book, exploring the scents that words carry in the air.",
            "Leaps onto a tabletop, a daring adventure into the elevated realms of exploration.",
            "Bounces on a bedspread, a feline trampoline of joyous exuberance.",
            "Grooms a fellow feline, a shared moment of post-play bonding.",
            "Stares into a fishbowl, eyes following the aquatic ballet with feline fascination.",
            "Chirrs in the presence of a fellow cat, a harmonic exchange in the language of camaraderie."
        }  
        local emote_summon = {
            "Stretches each limb gracefully, a feline ballet of awakening.",
            "Yawns delicately, a dainty opening of the Cornish Rex's sleepy maw.",
            "Blinks with sleepy eyes, adjusting to the light in the delicate way only a cat can.",
            "Flexes its paws, kneading an imaginary cushion in the afterglow of dreams.",
            "Curves its back, an elegant arching of the Cornish Rex's waking form.",
            "Shakes its fur lightly, a dance of morning dewdrops on the Cornish Rex's coat.",
            "Grooms with precision, a meticulous post-sleep beauty routine.",
            "Nuzzles its favorite sleeping spot, a gentle acknowledgment of restful dreams.",
            "Sniffs the air delicately, savoring the scents of a new day.",
            "Bounces with newfound energy, a playful leap into the waking world.",
            "Chirps a morning melody, a feline song celebrating the dawn.",
            "Licks its whiskers clean, a grooming ritual to start the day fresh.",
            "Wiggles its tail with excitement, a feline semaphore signaling the beginning.",
            "Purrs softly, a contented hum that resonates with the peace of waking.",
            "Nudges a nearby human, a gentle reminder that it's time to rise and shine.",
            "Twirls in a circle, a feline dance of greeting to the day.",
            "Fluffs its fur, a luxurious shake to awaken every strand.",
            "Snuggles against a companion, seeking warmth and connection in the waking hour.",
            "Bats at imaginary creatures, a playful swat at dreams lingering in the air.",
            "Sits with eyes half-closed, a serene moment of morning meditation.",
            "Stares into the distance, lost in the transitional magic between sleep and wakefulness.",
            "Curls its tail around its body, a self-hug in the waking embrace of the day.",
            "Paws at the bedcovers, a gentle attempt to tuck in the remnants of slumber.",
            "Wags its tail gently, a feline wag of greeting to the world.",
            "Lies in a sunbeam, absorbing the morning rays with blissful contentment.",
            "Sniffs its own paws, a curious investigation into the scent of sleep.",
            "Rolls onto its back, exposing the soft underbelly to the new day.",
            "Gazes out the window, eyes filled with the wonder of the waking world.",
            "Stalks invisible prey, a morning hunt in the realms of dreams.",
            "Nuzzles a nearby toy, a feline reunion with a playful companion.",
            "Paws at a blanket, a gentle kneading to keep the dreams close.",
            "Bounces off the walls, an exuberant burst of morning energy.",
            "Chases its tail, a dizzying dance of morning playfulness.",
            "Sniffs at the food bowl, savoring the promise of breakfast.",
            "Curls around a human's legs, a morning greeting wrapped in feline affection.",
            "Leaps onto a perch, a feline ascent into the waking kingdom.",
            "Pounces on an imaginary creature, a playful ambush on the borders of dreams.",
            "Grooms a fellow feline, a shared moment of post-sleep bonding.",
            "Stretches its neck gracefully, reaching for the full height of feline awakening.",
            "Blinks at the sunrise, eyes adjusting to the golden hues of a new day.",
            "Washes its face, a meticulous cleansing to start the day with pristine elegance.",
            "Lies on its back, legs in the air, a carefree surrender to the morning.",
            "Snuggles into a cozy blanket, a last embrace of the night's warmth.",
            "Sways its tail rhythmically, a feline dance to the morning symphony.",
            "Nibbles at a food bowl, a delicate breakfast ritual of the Cornish Rex.",
            "Purrs in a human's ear, a gentle wake-up call with a feline serenade.",
            "Nuzzles a sleeping companion, sharing the secrets of the night's adventures.",
            "Bounces from surface to surface, a morning exploration of the waking world.",
            "Chirps at the birds outside, a feline conversation with the early risers.",
            "Grooms a human's hand, a gesture of gratitude for the night's peaceful slumber.",
            "Stares into space, lost in the dreamy remnants of the feline subconscious.",
            "Lies in a sunbeam, eyes half-closed, a meditative bask in the morning glow.",
            "Sniffs the morning air through an open window, savoring the scents of the day.",
            "Rolls on the floor, a feline cartwheel celebrating the joy of waking.",
            "Bats at the curtains, a playful interaction with the fabric of dreams.",
            "Chirps at its reflection, a morning acknowledgment of its own feline charm.",
            "Waits by the door, eager for the adventures that await in the waking world.",
            "Snuggles into a pile of cushions, a soft landing from the heights of dreams.",
            "Sways its tail with anticipation, a feline semaphore signaling the start of a new day.",
            "Paws at a sleepy companion, encouraging them to join in the waking festivities.",
            "Nudges a human's face gently, a feline reminder that it's time to rise.",
            "Bounces on the bed, a morning trampoline of feline exuberance.",
            "Chirps a morning greeting to the household, a feline announcement of the day's arrival.",
            "Grooms a fellow feline, a shared moment of post-sleep bonding.",
            "Stretches its neck gracefully, reaching for the full height of feline awakening.",
            "Blinks at the sunrise, eyes adjusting to the golden hues of a new day.",
            "Washes its face, a meticulous cleansing to start the day with pristine elegance.",
            "Lies on its back, legs in the air, a carefree surrender to the morning.",
            "Snuggles into a cozy blanket, a last embrace of the night's warmth.",
            "Sways its tail rhythmically, a feline dance to the morning symphony.",
            "Nibbles at a food bowl, a delicate breakfast ritual of the Cornish Rex.",
            "Purrs in a human's ear, a gentle wake-up call with a feline serenade.",
            "Nuzzles a sleeping companion, sharing the secrets of the night's adventures.",
            "Bounces from surface to surface, a morning exploration of the waking world.",
            "Chirps at the birds outside, a feline conversation with the early risers.",
            "Grooms a human's hand, a gesture of gratitude for the night's peaceful slumber.",
            "Stares into space, lost in the dreamy remnants of the feline subconscious.",
            "Lies in a sunbeam, eyes half-closed, a meditative bask in the morning glow.",
            "Sniffs the morning air through an open window, savoring the scents of the day.",
            "Rolls on the floor, a feline cartwheel celebrating the joy of waking.",
            "Bats at the curtains, a playful interaction with the fabric of dreams.",
            "Chirps at its reflection, a morning acknowledgment of its own feline charm.",
            "Waits by the door, eager for the adventures that await in the waking world.",
            "Snuggles into a pile of cushions, a soft landing from the heights of dreams.",
            "Sways its tail with anticipation, a feline semaphore signaling the start of a new day.",
            "Paws at a sleepy companion, encouraging them to join in the waking festivities.",
            "Nudges a human's face gently, a feline reminder that it's time to rise.",
            "Bounces on the bed, a morning trampoline of feline exuberance.",
            "Chirps a morning greeting to the household, a feline announcement of the day's arrival."
        }
        local speak = {
            "Purrs with contentment, a melody of feline satisfaction.",
            "Chirps a friendly greeting, a cat's hello to the world.",
            "Nuzzles with affection, a gentle touch of feline warmth.",
            "Bounces with energy, a playful rhythm pulsating through agile limbs.",
            "Grooms with precision, maintaining the elegance of Cornish Rex grace.",
            "Whisks its tail with flair, a feline semaphore of mood and emotion.",
            "Curls in a cozy spot, the epitome of comfort in feline form.",
            "Leaps with agility, defying gravity in the dance of the Cornish Rex.",
            "Chirrs in bliss, a symphony of feline happiness filling the air.",
            "Gazes with curiosity, eyes reflecting the wonder of the feline explorer.",
            "Purrs in the language of love, a tender melody for those it cherishes.",
            "Nuzzles a companion, a gesture of friendship in the feline kingdom.",
            "Bounces with excitement, a rhythmic dance in the joy of the moment.",
            "Whisks its tail in anticipation, a feline banner signaling playful intent.",
            "Curls around a sunbeam, basking in the warmth of feline radiance.",
            "Grooms with affection, a cat's touch expressing love and care.",
            "Chirps a lullaby, a soothing melody for the peaceful feline nap.",
            "Leaps onto a perch, a regal elevation in the kingdom of Cornish Rex.",
            "Nuzzles a favorite toy, a feline friendship immortalized in play.",
            "Bounces with joy, a feline celebration of life's delightful moments.",
            "Purrs with gratitude, a thankful symphony echoing through the heart.",
            "Gazes into the distance, eyes filled with dreams of feline exploration.",
            "Chirrs in conversation, a feline dialogue in the secret language of cats.",
            "Whisks its tail in approval, a feline gesture of agreement.",
            "Curls around a lap, the epitome of feline coziness and companionship.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Grooms with finesse, a display of the elegant Cornish Rex grooming ritual.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life.",
            "Nuzzles a familiar scent, a memory etched in the heart of the Cornish Rex.",
            "Bounces with anticipation, a playful dance in the joy of the moment.",
            "Purrs with affection, a gentle melody of love that resonates deeply.",
            "Grooms with care, a meticulous display of the Cornish Rex's elegant beauty.",
            "Chirps a goodnight, a feline lullaby bidding farewell to the day.",
            "Whisks its tail in contentment, a feline semaphore of peace and harmony.",
            "Curls around a cherished possession, a guardian of feline treasures.",
            "Nuzzles a soft touch, a gentle connection in the quiet language of cats.",
            "Bounces with playfulness, a rhythmic dance in the delight of games.",
            "Gazes with wisdom, eyes reflecting the depth of feline intuition.",
            "Purrs with serenity, a calming symphony in the midst of life's storms.",
            "Chirps with curiosity, a feline inquiry into the mysteries of the world.",
            "Whisks its tail in greeting, a friendly feline semaphore welcoming all.",
            "Curls in a sunbeam, absorbing the warmth of the feline spotlight.",
            "Leaps onto a favorite perch, a feline throne in the kingdom of comfort.",
            "Nuzzles a comforting presence, seeking solace in the warmth of connection.",
            "Bounces with enthusiasm, a feline dance in the rhythm of excitement.",
            "Purrs in the twilight, a serenade to the stars in the feline night.",
            "Chirps with charm, a feline charisma that captivates the heart.",
            "Whisks its tail in delight, a feline semaphore expressing pure joy.",
            "Curls in a crescent moon, a celestial embrace in the realm of dreams.",
            "Leaps onto a perch, a feline throne in the grand tapestry of life."
        }
        local speak_win = {
            "Purrs triumphantly, the melody of victory echoing in the air.",
            "Nuzzles its victorious whiskers, claiming the spoils of battle.",
            "Leaps into a celebratory dance, a feline jig of triumphant joy.",
            "Chirps in victorious chatter, sharing the tales of the epic conquest.",
            "Whisks its tail in a victory swirl, a cat's banner unfurled in glory.",
            "Curls its body in a triumphant pose, the embodiment of feline success.",
            "Gazes with pride, victorious eyes reflecting the glory of the conquest.",
            "Purrs in the rhythm of victory, a melody of conquering achievement.",
            "Nuzzles a victorious paw, a gentle touch acknowledging the triumph.",
            "Bounces with joy, a victorious leap in the aftermath of battle.",
            "Chirrs in triumph, a cat's cheer resonating through the victorious arena.",
            "Whisks its tail high, a feline standard raised in the celebration.",
            "Curls around the conquered territory, a cat's claim marked with delight.",
            "Groomes with victorious precision, maintaining the elegance of triumph.",
            "Purrs in the language of victory, a feline proclamation to the world.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air.",
            "Whisks its tail with flair, a feline maestro conducting the victory dance.",
            "Curls in a triumphant nap, the sweet dreams of a conquering cat.",
            "Groomes with victorious finesse, a cat's regal upkeep after the triumph.",
            "Purrs with satisfaction, a melody of triumph reverberating through the soul.",
            "Nuzzles the conquered terrain, a feline explorer savoring the victory.",
            "Leaps onto a throne of victory, a feline ruler basking in the conquest.",
            "Chirps a victorious ballad, a feline minstrel celebrating the epic tale.",
            "Whisks its tail in victory's breeze, a feline standard proudly displayed.",
            "Curls with contentment, a victorious rest after the battle's success.",
            "Groomes with victorious precision, a feline's regal appearance in triumph.",
            "Purrs in the language of victory, a feline anthem sung to the moon.",
            "Nuzzles a fallen foe, a gesture of respect in the aftermath of triumph.",
            "Bounces with jubilation, a victorious dance in the heart of conquest.",
            "Chirrs in harmonious celebration, a feline choir rejoicing in triumph.",
            "Whisks its tail in triumphant waves, a feline semaphore of victory.",
            "Curls around a trophy, a feline champion claiming its laurels.",
            "Groomes with victorious elegance, a cat's graceful post-victory ritual.",
            "Purrs in the afterglow of conquest, a soothing melody of triumphant joy.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air.",
            "Whisks its tail with flair, a feline maestro conducting the victory dance.",
            "Curls in a triumphant nap, the sweet dreams of a conquering cat.",
            "Groomes with victorious finesse, a cat's regal upkeep after the triumph.",
            "Purrs with satisfaction, a melody of triumph reverberating through the soul.",
            "Nuzzles the conquered terrain, a feline explorer savoring the victory.",
            "Leaps onto a throne of victory, a feline ruler basking in the conquest.",
            "Chirps a victorious ballad, a feline minstrel celebrating the epic tale.",
            "Whisks its tail in victory's breeze, a feline standard proudly displayed.",
            "Curls with contentment, a victorious rest after the battle's success.",
            "Groomes with victorious precision, a feline's regal appearance in triumph.",
            "Purrs in the language of victory, a feline anthem sung to the moon.",
            "Nuzzles a fallen foe, a gesture of respect in the aftermath of triumph.",
            "Bounces with jubilation, a victorious dance in the heart of conquest.",
            "Chirrs in harmonious celebration, a feline choir rejoicing in triumph.",
            "Whisks its tail in triumphant waves, a feline semaphore of victory.",
            "Curls around a trophy, a feline champion claiming its laurels.",
            "Groomes with victorious elegance, a cat's graceful post-victory ritual.",
            "Purrs in the afterglow of conquest, a soothing melody of triumphant joy.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air.",
            "Whisks its tail with flair, a feline maestro conducting the victory dance.",
            "Curls in a triumphant nap, the sweet dreams of a conquering cat.",
            "Groomes with victorious finesse, a cat's regal upkeep after the triumph.",
            "Purrs with satisfaction, a melody of triumph reverberating through the soul.",
            "Nuzzles the conquered terrain, a feline explorer savoring the victory.",
            "Leaps onto a throne of victory, a feline ruler basking in the conquest.",
            "Chirps a victorious ballad, a feline minstrel celebrating the epic tale.",
            "Whisks its tail in victory's breeze, a feline standard proudly displayed.",
            "Curls with contentment, a victorious rest after the battle's success.",
            "Groomes with victorious precision, a feline's regal appearance in triumph.",
            "Purrs in the language of victory, a feline anthem sung to the moon.",
            "Nuzzles a fallen foe, a gesture of respect in the aftermath of triumph.",
            "Bounces with jubilation, a victorious dance in the heart of conquest.",
            "Chirrs in harmonious celebration, a feline choir rejoicing in triumph.",
            "Whisks its tail in triumphant waves, a feline semaphore of victory.",
            "Curls around a trophy, a feline champion claiming its laurels.",
            "Groomes with victorious elegance, a cat's graceful post-victory ritual.",
            "Purrs in the afterglow of conquest, a soothing melody of triumphant joy.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air.",
            "Whisks its tail with flair, a feline maestro conducting the victory dance.",
            "Curls in a triumphant nap, the sweet dreams of a conquering cat.",
            "Groomes with victorious finesse, a cat's regal upkeep after the triumph.",
            "Purrs with satisfaction, a melody of triumph reverberating through the soul.",
            "Nuzzles the conquered terrain, a feline explorer savoring the victory.",
            "Leaps onto a throne of victory, a feline ruler basking in the conquest.",
            "Chirps a victorious ballad, a feline minstrel celebrating the epic tale.",
            "Whisks its tail in victory's breeze, a feline standard proudly displayed.",
            "Curls with contentment, a victorious rest after the battle's success.",
            "Groomes with victorious precision, a feline's regal appearance in triumph.",
            "Purrs in the language of victory, a feline anthem sung to the moon.",
            "Nuzzles a fallen foe, a gesture of respect in the aftermath of triumph.",
            "Bounces with jubilation, a victorious dance in the heart of conquest.",
            "Chirrs in harmonious celebration, a feline choir rejoicing in triumph.",
            "Whisks its tail in triumphant waves, a feline semaphore of victory.",
            "Curls around a trophy, a feline champion claiming its laurels.",
            "Groomes with victorious elegance, a cat's graceful post-victory ritual.",
            "Purrs in the afterglow of conquest, a soothing melody of triumphant joy.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air.",
            "Whisks its tail with flair, a feline maestro conducting the victory dance.",
            "Curls in a triumphant nap, the sweet dreams of a conquering cat.",
            "Groomes with victorious finesse, a cat's regal upkeep after the triumph.",
            "Purrs with satisfaction, a melody of triumph reverberating through the soul.",
            "Nuzzles the conquered terrain, a feline explorer savoring the victory.",
            "Leaps onto a throne of victory, a feline ruler basking in the conquest.",
            "Chirps a victorious ballad, a feline minstrel celebrating the epic tale.",
            "Whisks its tail in victory's breeze, a feline standard proudly displayed.",
            "Curls with contentment, a victorious rest after the battle's success.",
            "Groomes with victorious precision, a feline's regal appearance in triumph.",
            "Purrs in the language of victory, a feline anthem sung to the moon.",
            "Nuzzles a fallen foe, a gesture of respect in the aftermath of triumph.",
            "Bounces with jubilation, a victorious dance in the heart of conquest.",
            "Chirrs in harmonious celebration, a feline choir rejoicing in triumph.",
            "Whisks its tail in triumphant waves, a feline semaphore of victory.",
            "Curls around a trophy, a feline champion claiming its laurels.",
            "Groomes with victorious elegance, a cat's graceful post-victory ritual.",
            "Purrs in the afterglow of conquest, a soothing melody of triumphant joy.",
            "Nuzzles a fellow warrior, sharing the warmth of victorious camaraderie.",
            "Leaps onto a perch, a victorious elevation in the feline kingdom.",
            "Chirps a triumphant melody, a song of victory sung to the stars.",
            "Whisks its tail in victorious semaphore, signaling the triumph to all.",
            "Curls around the spoils of battle, a feline guardian of the conquered treasures.",
            "Gazes into the distance, victorious eyes envisioning future conquests.",
            "Purrs in the afterglow of victory, a soothing symphony of triumphant purring.",
            "Nuzzles a conquered toy, a feline conqueror claiming its prize.",
            "Bounces with energy, a victorious rhythm pulsating through agile limbs.",
            "Chirrs in celebration, a feline chorus of triumph filling the air."
        }
        local speak_dead = {
            "Bows its head in solemn remembrance of a life well-lived.",
            "Whispers a farewell, leaving behind a legacy of purrs and warmth.",
            "Nuzzles its favorite toy, a final embrace in the realm of memories.",
            "Curls up in a peaceful slumber, a forever nap after a life of play.",
            "Gazes with soulful eyes, a silent goodbye etched in feline expression.",
            "Leaves a paw print on the heart, a token of love imprinted forever.",
            "Rests in a sunbeam, basking in eternal warmth and tranquility.",
            "Purrs softly, the melody of a cat's spirit echoing in the air.",
            "Takes a final stretch, reaching for the stars in the cosmic expanse.",
            "Nuzzles the air, sending gentle purrs to those who remember.",
            "Whisks away on a moonlit night, leaving behind a trail of stardust.",
            "Curls its tail in serenity, a feline comet traversing the universe.",
            "Sleeps peacefully, cradled in the arms of everlasting dreams.",
            "Whispers a silent meow, a message carried by the cosmic winds.",
            "Flicks its ears in angelic repose, a guardian spirit in the afterlife.",
            "Basks in the eternal glow, a celestial kitty in the cosmic tapestry.",
            "Purrs in the starlight, a lullaby for the hearts left behind.",
            "Treads softly on the clouds, leaving paw prints in the sky.",
            "Rests among the constellations, a feline constellation in the night sky.",
            "Nuzzles the rainbow bridge, a bridge to eternal feline paradise.",
            "Leaves a paw print on the canvas of time, a masterpiece of love.",
            "Purrs in the realm of dreams, a melody that echoes through the ages.",
            "Curls around a memory, a furry embrace lingering in the heart.",
            "Whispers in the wind, a cat's message carried to the heavens.",
            "Rests in a moonlit meadow, a peaceful slumber under the celestial gaze.",
            "Purrs in the midnight breeze, a gentle zephyr of feline affection.",
            "Nuzzles a star, a celestial kiss on the tapestry of the night.",
            "Curls in a crescent moon, a feline guardian watching from above.",
            "Leaves paw prints on the stars, a constellation of eternal love.",
            "Purrs in the cosmic silence, a lullaby for the universe to hear.",
            "Treads lightly on the Milky Way, a cat's journey through celestial seas.",
            "Nuzzles the afterlife, a gentle greeting to feline kindred spirits.",
            "Curls around a memory, a cozy recollection in the cosmic storybook.",
            "Rests in a field of wishes, a whiskered wish upon a star.",
            "Purrs in the starry night, a serenade for the cosmic audience.",
            "Whispers in the aurora, a cat's voice in the northern lights' dance.",
            "Leaves a paw print on the horizon, a sunset of feline farewell.",
            "Nuzzles the dawn, a new beginning in the tapestry of existence.",
            "Curls around the sun, a solar cat basking in eternal radiance.",
            "Purrs in the morning light, a gentle melody in the waking world.",
            "Treads softly on the clouds, a celestial ballet in the sky.",
            "Rests in the embrace of time, a forever moment in the feline chronicle.",
            "Nuzzles the universe, a feline explorer in the cosmic expanse.",
            "Curls around a comet's tail, a celestial journey through space.",
            "Purrs in the stardust, a lullaby for the celestial nursery.",
            "Whispers in the zephyr, a cat's message carried on the cosmic breeze.",
            "Leaves paw prints on the astral plane, a dance of feline energy.",
            "Nuzzles the cosmos, a feline companion to the stars.",
            "Curls in the galaxy's arms, a celestial embrace in the infinite void.",
            "Purrs in the star clusters, a melody woven into the cosmic quilt.",
            "Treads softly on the nebulae, a cat's journey through celestial clouds.",
            "Rests in the glow of the planets, a feline sojourner in the cosmic system.",
            "Nuzzles the comet's tail, a feline voyage through the celestial tapestry.",
            "Curls around the Big Dipper, a cosmic dip into eternal slumber.",
            "Purrs in the cosmic breeze, a cat's song carried to distant galaxies.",
            "Whispers in the meteor shower, a feline blessing upon falling stars.",
            "Leaves paw prints on the celestial canvas, a masterpiece of cosmic art.",
            "Nuzzles the cosmic waves, a feline surfer on the shores of eternity.",
            "Curls around the universe, a celestial cat in the grand design.",
            "Purrs in the cosmic symphony, a melody played by the stars.",
            "Treads softly on the interstellar highway, a cat's journey through the cosmos.",
            "Rests in the cosmic cradle, a feline babe in the arms of the universe.",
            "Nuzzles the black hole's edge, a daring explorer in the cosmic abyss.",
            "Curls around a quasar, a feline beacon in the cosmic darkness.",
            "Purrs in the supernova's glow, a celestial dance in the explosive finale.",
            "Whispers in the cosmic silence, a cat's voice in the void of eternity.",
            "Leaves paw prints on the event horizon, a mark of feline presence.",
            "Nuzzles the antimatter, a curious cat in the cosmic enigma.",
            "Curls around the dark matter, a feline mystery in the cosmic puzzle.",
            "Purrs in the quantum realm, a melody resonating through subatomic whispers.",
            "Treads softly on the strings of existence, a cat's dance in the cosmic orchestra.",
            "Rests in the singularity, a feline essence woven into the fabric of reality.",
            "Nuzzles the multiverse, a feline traveler through infinite possibilities.",
            "Curls around parallel dimensions, a cosmic cat in the tapestry of existence.",
            "Purrs in the quantum fluctuation, a melody echoing in the cosmic background.",
            "Whispers in the chaos theory, a cat's secret in the cosmic unpredictability.",
            "Leaves paw prints on the alternate realities, a feline explorer in the cosmic maze.",
            "Nuzzles the cosmic void, a companion to the emptiness of eternity."
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
