if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s43 = function(db) 
    db.content.petComments.s43 = function(db, type)
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "Purrs contentedly",
            "Stretches lazily",
            "Curiously investigates a new object",
            "Nuzzles against your hand for attention",
            "Chases after a feather toy",
            "Paws at a ball of yarn",
            "Curls up into a cozy ball",
            "Grooms its fur meticulously",
            "Playfully pounces on a moving shadow",
            "Watches birds outside with fascination",
            "Kneads its paws on a soft surface",
            "Sniffs a fragrant flower",
            "Wags its tail in excitement",
            "Lies in a sunbeam to soak up warmth",
            "Gives you a slow blink of affection",
            "Hunts imaginary prey with intense focus",
            "Licks its lips after a tasty meal",
            "Sits regally with a proud posture",
            "Rubbing its head against furniture",
            "Chirps or chatters at birds through a window",
            "Rolls over, inviting belly rubs",
            "Paws at a shoelace, thinking it's prey",
            "Climbs to a high perch to survey the room",
            "Bats at a dangling toy",
            "Snuggles up in your lap",
            "Naps peacefully with a gentle snore",
            "Chirrups in greeting when you come home",
            "Darts around in a playful frenzy",
            "Stares at a laser pointer dot on the wall",
            "Pounces on a moving target",
            "Expresses interest in a crinkling paper bag",
            "Buries its waste in the litter box",
            "Glares with a narrowed gaze when annoyed",
            "Lies on its back to showcase its belly",
            "Grooms its face with its paw",
            "Perches on a windowsill to watch the world",
            "Licks a paw and cleans behind its ears",
            "Stares intently at a bug on the floor",
            "Curls its tail around your leg",
            "Sniffs and explores a new scent",
            "Climbs into a cardboard box to investigate",
            "Kneads a soft blanket before lying down",
            "Closes its eyes in a sleepy, content manner",
            "Paws at a door to be let in or out",
            "Hunts and carries a toy mouse triumphantly",
            "Sniffs the air with curiosity",
            "Scratches a scratching post",
            "Sits with an attentive ear twitch",
            "Engages in a playful game of hide and seek",
            "Nuzzles a fellow feline companion",
            "Paws at an insect on the floor",
            "Bumps its head against your hand for pets",
            "Lies in a sunspot to bask in warmth",
            "Curls its tail around your wrist",
            "Chases a reflected light spot on the wall",
            "Gives a demanding meow for food",
            "Paws at a doorknob to open a door",
            "Nuzzles against your face affectionately",
            "Climbs onto your shoulder for attention",
            "Curls its body into an elegant arch",
            "Hunts and captures a toy with precision",
            "Scratches its ear with its hind leg",
            "Stares out the window with a thoughtful gaze",
            "Sniffs and investigates a new piece of furniture",
            "Chases a string pulled across the floor",
            "Stretches out with a long, luxurious yawn",
            "Naps with its tail wrapped around its body",
            "Lies in a cozy bed with eyes half-closed",
            "Snuggles up against another cat companion",
            "Paws at a dangling curtain tassel",
            "Chases a bouncing ball with enthusiasm",
            "Rolls playfully on the floor",
            "Watches the flickering flame of a candle",
            "Curls its body into a tight ball when scared",
            "Sits with an expectant look during mealtime",
            "Gives an inquisitive head tilt",
            "Bats at a moth fluttering around a lamp",
            "Paws at the bottom of a closed door",
            "Expresses curiosity about a visitor",
            "Hides in a cozy nook for a private moment",
            "Sniffs and explores a new bag or backpack",
            "Nuzzles against your leg for attention",
            "Climbs a tree to observe the surroundings",
            "Watches a fish swimming in a tank with fascination",
            "Lies on a soft blanket with a satisfied sigh",
            "Grooms a fellow cat's head affectionately",
            "Playfully wrestles with a sibling",
            "Paws at a piece of string dangling from a table",
            "Curls up with a favorite toy in its paws",
            "Chirps at a distant bird in the yard",
            "Pounces on a crumpled paper ball",
            "Stares at its reflection in a mirror with curiosity",
            "Lies beside you in bed, providing warmth",
            "Wags its tail in a happy greeting",
            "Sits with a contemplative, distant gaze",
            "Snuggles with a plush toy or cushion",
            "Cuddles up against your neck when held",
            "Naps in a hidden, cozy spot",
            "Paws at a window to be let in or out",
            "Chirrups and kneads your lap before settling",
            "Hunts and captures a small insect on the floor"            
        }
        local emote_summon = {
            "Flexes its claws.",
            "Sharpens its fangs.",
            "Stretches its muscles.",
            "Archs its back.",
            "Puffs up its fur.",
            "Raises its tail high.",
            "Pounces in place.",
            "Locks onto its target.",
            "Glowers with determination.",
            "Hones its battle instincts.",
            "Hisses in warning.",
            "Crouches low to the ground.",
            "Circles its opponent.",
            "Fixes a steely gaze.",
            "Practicing stealthy steps.",
            "Studies the enemy's moves.",
            "Flicks its tail like a whip.",
            "Charges forward with energy.",
            "Shows its battle scars.",
            "Lets out a battle cry.",
            "Flexes its back muscles.",
            "Hones its battle senses.",
            "Scans the battlefield.",
            "Snarls with ferocity.",
            "Flares its whiskers.",
            "Raises its hackles.",
            "Practices ambush tactics.",
            "Focuses on the enemy's weaknesses.",
            "Unsheathes its claws.",
            "Lunges at the enemy.",
            "Sprints with agility.",
            "Shows its battle-ready stance.",
            "Sizes up its adversary.",
            "Sneaks silently like a ninja.",
            "Thumps its tail with impatience.",
            "Displays a fierce glare.",
            "Leaps into the action.",
            "Strikes with precision.",
            "Huddles low for stealth.",
            "Casts an intimidating shadow.",
            "Sniffs out the competition.",
            "Crouches and waits.",
            "Sprints into battle mode.",
            "Flexes its battle paws.",
            "Growls with authority.",
            "Positions for the attack.",
            "Practices swift maneuvers.",
            "Stalks its prey with intent.",
            "Unleashes a powerful jump.",
            "Pounces with a battle cry.",
            "Bolts forward with force.",
            "Demonstrates fierce agility.",
            "Scratches with determination.",
            "Eyes its target with focus.",
            "Shows off its warrior spirit.",
            "Launches a surprise attack.",
            "Stretches and readies itself.",
            "Hones its battle strategies.",
            "Snarls and hisses fiercely.",
            "Flexes its battle muscles.",
            "Scans the battlefield terrain.",
            "Lowers itself into a crouch.",
            "Darts forward with swiftness.",
            "Shows its tactical prowess.",
            "Hides with cunning stealth.",
            "Roars like a mighty lion.",
            "Initiates a cat-a-pult attack.",
            "Strikes like a silent hunter.",
            "Nods with battle readiness.",
            "Prowls with menacing intent.",
            "Confronts the enemy head-on.",
            "Charges with undying valor.",
            "Practices synchronized leaps.",
            "Bares its teeth with power.",
            "Glows with a fierce determination.",
            "Prepares for a sneak attack.",
            "Hisses with a warning growl.",
            "Showcases its battle claws.",
            "Jumps into action mode.",
            "Strikes with calculated precision.",
            "Flexes and tenses its muscles.",
            "Roars with fearless courage.",
            "Sniffs the scent of battle.",
            "Unleashes its inner warrior.",
            "Positions for a tactical assault.",
            "Hides in the shadows.",
            "Pounces into the fray.",
            "Hisses and bares its teeth.",
            "Stalks with silent intention.",
            "Stands tall with confidence.",
            "Sizes up the battle plan.",
            "Attacks with fearless valor.",
            "Sneaks up on the enemy.",
            "Initiates a surprise strike.",
            "Unsheathes its claw-sword.",
            "Crouches for the perfect moment.",
            "Nods with a knowing look.",
            "Surges forward like a warrior.",
            "Flexes its tail with pride.",
            "Roars like a battle champion."
        }
        local speak = {
            "Meow, it's breakfast time!",
            "Purrfect day for a catnap.",
            "Chasing my tail in circles.",
            "Why is that red dot so elusive?",
            "Scratch me behind the ears, please!",
            "Climbing to the highest point again.",
            "I'm the king of the windowsill.",
            "Feather toys are my arch-enemy!",
            "I demand chin scratches now.",
            "Zooming around like a tiny tornado.",
            "Is that a can opener I hear?",
            "Hunting invisible prey at 3 AM.",
            "Paws and whiskers, that's my style.",
            "I've claimed this box as mine!",
            "Keeping watch over my domain.",
            "Napping in a sunbeam's warm embrace.",
            "Who moved my favorite blanket?",
            "I'll catch that pesky laser pointer!",
            "Catnip? Yes, please!",
            "I've got a fluffy tail and I'm not afraid to use it.",
            "The couch is my royal throne.",
            "Time for a midday catnap.",
            "Purring my way into your heart.",
            "Why is there a cucumber behind me?",
            "Climbing to new heights of curiosity.",
            "Intruder alert! (It's just a leaf.)",
            "Bring me all the treats!",
            "Zig-zagging through the house for fun.",
            "I'm the stealthy ninja of the house.",
            "Napping on your keyboard because I can.",
            "Licking my paws with sophistication.",
            "Grooming to keep my fur impeccable.",
            "Cuddles and chin rubs, please!",
            "I love my scratching post!",
            "Waking you up at 5 AM because I can.",
            "Curled up in a cozy ball of fluff.",
            "Chasing my tail, just for kicks.",
            "Exploring the great unknown (the backyard).",
            "Paws that can open any door.",
            "I see birds outside and want to be one.",
            "Taking over your bed, one nap at a time.",
            "My purr can melt your heart.",
            "I'm the guardian of the cardboard castle.",
            "Napping, napping, and more napping.",
            "Why are you still working? It's playtime!",
            "Climbing the curtains, the ultimate adventure.",
            "Chasing the elusive red dot.",
            "Time for a snack, or two, or three.",
            "I'm the ultimate paperweight on your desk.",
            "Exploring the depths of the laundry basket.",
            "Lazing in a sunbeam's warm embrace.",
            "Paws of curiosity and mischief.",
            "Can't resist batting at dangling strings.",
            "Napping, then waking up for more napping.",
            "Pouncing on toy mice with precision.",
            "I'm the connoisseur of cardboard boxes.",
            "Climbing to unreachable heights.",
            "Paws that knead with love.",
            "I've got the fluffiest fur in town.",
            "Why is there a spot on the wall?",
            "Chasing imaginary prey in the dark.",
            "Time for a head-butt of affection.",
            "I demand a cat treat tribuete!",
            "I'm the furry acrobat on the bookshelf.",
            "Napping on your freshly folded laundry.",
            "Why is that feather so tantalizing?",
            "Climbing onto your lap for snuggles.",
            "Pouncing on unsuspecting toes.",
            "I'm the ruler of the paper kingdom.",
            "Paws that leave adorable paw prints.",
            "I've got a purr that soothes your soul.",
            "Why is there an empty box here?",
            "Chasing my tail in endless circles.",
            "Exploring the cardboard jungle gym.",
            "Lazing on the softest cushions.",
            "Paws that stretch in all directions.",
            "I'm the master of the cardboard box fort.",
            "Demanding to be petted at all times.",
            "Napping in cozy hideaway spots.",
            "Why is there a laser dot on the wall?",
            "Climbing onto your shoulders for a better view.",
            "I see birds outside and want to catch them.",
            "Pouncing on shadows and dust motes.",
            "I'm the cat who's never too far from your side.",
            "Paws that make the world my playground.",
            "Why is that pesky tail so intriguing?",
            "Chasing after the elusive red dot.",
            "Exploring every nook and cranny.",
            "Lazing in the warmth of the sun.",
            "Paws that knead, telling you I love you.",
            "I'm the ruler of the sunny spot on the bed.",
            "Why is there a mouse toy in my food bowl?",
            "Climbing up the curtains for fun.",
            "Demanding your attention with a meow.",
            "Napping in the sun's gentle rays.",
            "Why is that shadow moving on the wall?",
            "Chasing feather toys with grace.",
            "I'm the guardian of the windowsill.",
            "Paws that tap out a beat of curiosity.",
            "I've got a tail that's as expressive as me.",
            "Why is there a cardboard tube on the floor?",
            "Chasing my own tail, the best game ever!",
            "Exploring the mysteries of empty boxes.",
            "Lazing in the radiance of the morning sun.",
            "Paws that softly tread on silent hunts.",
            "I'm the expert at hiding in plain sight.",
            "Why is that bag so fascinating?",
            "Climbing into the highest perch for a view.",
            "Demanding affection with gentle headbutts.",
            "Napping in the comfiest spots I can find.",
            "Why is there a plant I'm not supposed to eat?",
            "Chasing my own reflection in the mirror.",
            "I'm the fluffiest ball of joy in your life."
        }
        local speak_dead = {
            "That didn't go as planned.",
            "I'll get them next time.",
            "It was a tough opponent.",
            "I need some TLC now.",
            "A little beaten but not broken.",
            "They had a mean left hook!",
            "I underestimated them.",
            "My pride is hurt more than anything.",
            "I'll lick my wounds and bounce back.",
            "A tough battle, for sure.",
            "I wasn't at my best today.",
            "I'll come back stronger.",
            "It's all part of the game.",
            "I need a catnap and a snack.",
            "I've had better days.",
            "Let's call it a draw.",
            "I'll recover and regroup.",
            "That was a feisty opponent.",
            "I'll get my revenge soon.",
            "I'll show them next time.",
            "I'm not giving up.",
            "I'll heal and come back fighting.",
            "I'm still a fierce feline.",
            "It's just a minor setback.",
            "I'll train harder.",
            "Sometimes you win, sometimes you lose.",
            "I'll heal and come back fighting.",
            "I'm still the king of the jungle.",
            "I fought valiantly.",
            "I'll stay humble and hungry.",
            "I have more lives to live.",
            "I'm not defeated, just tired.",
            "A tough opponent, for sure.",
            "I'm not giving in.",
            "I'll bounce back in no time.",
            "I'll keep my claws sharp.",
            "I'll get my revenge someday.",
            "A fighter never backs down.",
            "I'll have a comeback story.",
            "I'm still a force to be reckoned with.",
            "I need some comfort right now.",
            "I'll rise again.",
            "I'll take this loss in stride.",
            "I'm not one to quit.",
            "It's not the end of the world.",
            "I'll recover my honor.",
            "A good cat always learns.",
            "I'm not down for the count.",
            "I'll live to fight another day.",
            "I need a little pampering.",
            "It's a fierce world out there.",
            "I won't let this defeat define me.",
            "I'll come back with a vengeance.",
            "I've still got my spirit.",
            "I'm not done chasing my dreams.",
            "I'll regroup and come back stronger.",
            "I'll always give it my all.",
            "I'll need some extra snacks to recover.",
            "I'm still a tough cookie.",
            "A little bruised but not broken.",
            "I'll be back on top soon.",
            "I'll find my inner strength.",
            "I'm still the king of the jungle.",
            "I'll show them who's boss next time.",
            "I'll heal and come back roaring.",
            "I'll be back in the ring.",
            "A fighter never gives up.",
            "I'm not backing down.",
            "I'll reclaim my territory.",
            "I'll keep my chin up.",
            "I'll be a champion again.",
            "I won't let this keep me down.",
            "I'll rise from the ashes.",
            "I'll dust myself off.",
            "I'm not ready to retire.",
            "I'll come back with a vengeance.",
            "I'll fight for what's mine.",
            "I'll keep my claws sharp.",
            "I'm not finished yet.",
            "I'll emerge victorious next time.",
            "I'll make a triumphant return.",
            "I'll need some extra pampering.",
            "I'm not going quietly.",
            "I'll regain my feline dignity.",
            "I'll be back on the prowl.",
            "I'll conquer the world.",
            "I'm still a fierce contender.",
            "I'll get back on my feet.",
            "I'll turn this setback into a comeback.",
            "I'll keep my spirit alive.",
            "I'm not one to surrender.",
            "I'll train harder for the next battle.",
            "I'll find my inner warrior.",
            "I'll prove my worth once more.",
            "I'm not giving up on my dreams.",
            "I'll come back as a champion.",
            "I'll heal and come back stronger.",
            "I'll always strive for victory.",
            "I'm still a fighter at heart.",
            "I'll never lose my determination."            
        }
        local speak_win = {
            "I am the champion!",
            "I'm on top of the world!",
            "A purr-fect victory!",
            "Roar of triumph!",
            "I rule the kingdom!",
            "I've got the eye of the tiger!",
            "The mightiest cat in town!",
            "No one can defeat me!",
            "A victorious tail held high!",
            "I am invincible!",
            "The battle was fierce, but I prevailed!",
            "Paws of power!",
            "I've defended my territory!",
            "I fought with all my heart!",
            "A cat of great valor!",
            "The battleground is mine!",
            "My claws are unstoppable!",
            "I'm the top cat in town!",
            "A warrior of epic proportions!",
            "Victory tastes so sweet!",
            "I'm the alpha cat!",
            "I've vanquished all foes!",
            "My purr-sistence paid off!",
            "The battleground bows to me!",
            "The mightiest roar!",
            "I am the true ruler!",
            "I've claimed my victory!",
            "A battle well-fought!",
            "My fangs are sharp and true!",
            "I'm the cat of the hour!",
            "I've left my mark!",
            "A true battle cat!",
            "I've got the heart of a lion!",
            "A legendary victory!",
            "Purr-fectly triumphant!",
            "My purr-sistence is unmatched!",
            "A triumphant roar echoes!",
            "I've seized the day!",
            "I'm a force of nature!",
            "I've outwitted my foes!",
            "The battleground is mine to roam!",
            "A victorious leap into the sun!",
            "I've conquered the impossible!",
            "My whiskers quiver with success!",
            "A roar of jubilation!",
            "I've got the courage of a lion!",
            "I am the king of the jungle!",
            "I've won the day!",
            "A tail of triumph!",
            "I am the hero of the hour!",
            "I've triumphed over adversity!",
            "My courage knows no bounds!",
            "I'm the undefeated champion!",
            "A roar that shakes the world!",
            "I've shown my true colors!",
            "The battle belongs to me!",
            "I'm the conqueror of all!",
            "I've faced all challenges!",
            "My victory is legendary!",
            "I am the stuff of legends!",
            "I've defended my realm!",
            "A tale of triumph and valor!",
            "I'm the cat of destiny!",
            "I've clawed my way to victory!",
            "I'm the bravest of them all!",
            "I've conquered the uncharted!",
            "A battle cat without equal!",
            "I am the heart of the storm!",
            "I've faced the fiercest foes!",
            "I'm the cat who defies all odds!",
            "I've claimed my victory with pride!",
            "I'm the cat who never gives up!",
            "I've seized the day with gusto!",
            "A warrior who's second to none!",
            "I am the lord of the battleground!",
            "I've left my pawprints in history!",
            "I'm the purr-sence of power!",
            "I've stood tall and victorious!",
            "A roar that shakes the heavens!",
            "I am the fearless one!",
            "I've conquered the unconquerable!",
            "I'm the cat who knows no defeat!",
            "I've won the ultimate battle!",
            "A tale of epic battles!",
            "I am the indomitable one!",
            "I've defended my honor with might!",
            "I'm the cat of incredible courage!",
            "I've outshone all rivals!",
            "I am the legend of the realm!",
            "I've emerged victorious and proud!",
            "I'm the cat who rises above all!",
            "I've conquered the insurmountable!",
            "A roar heard 'round the world!",
            "I am the warrior of the ages!",
            "I've claimed the ultimate prize!",
            "I'm the cat who defies all odds!",
            "I've triumphed with honor!",
            "A legendary feline conqueror!",
            "I am the ruler of the land!",
            "I've emerged as the greatest of all!",
            "I'm the fearless guardian of the realm!",
            "I've faced all challengers with valor!",
            "A victorious paw in the air!",
            "I am the one and only!",
            "I've shown my true colors with pride!",
            "I'm the cat of unparalleled bravery!",
            "I've achieved the impossible!"            
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
