if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s447 = function(db) 
    db.content.petComments.s447 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "Shyly hides behind a tree.",
            "Timidly gazes at the ground.",
            "Nervously twitches its tail.",
            "Cautiously sniffs the air.",
            "Quietly nibbles on grass.",
            "Startled by sudden movement.",
            "Trembles with shyness.",
            "Gently lowers its head.",
            "Watches from a distance.",
            "Ears flicker with anxiety.",
            "Softly bleats for comfort.",
            "Takes small, cautious steps.",
            "Avoids eye contact.",
            "Curled up in a quiet corner.",
            "Shivers with apprehension.",
            "Ears flatten in shyness.",
            "Sniffs the ground nervously.",
            "Slowly approaches others.",
            "Skittishly backs away.",
            "Shyly nudges a sibling.",
            "Glances from behind a bush.",
            "Tucks its tail between legs.",
            "Blinks with uncertainty.",
            "Stays close to its mother.",
            "Hesitates before moving.",
            "Silently watches the world.",
            "Quivers with timidity.",
            "Tiptoes through the meadow.",
            "Ears perk up in curiosity.",
            "Flinches at sudden noises.",
            "Shyly follows the herd.",
            "Softly snorts with anxiety.",
            "Tensely grazes on grass.",
            "Stays near familiar places.",
            "Shyly peeks from the brush.",
            "Ears swivel with alertness.",
            "Nervously brushes against others.",
            "Startled by a gentle breeze.",
            "Shyly approaches a stream.",
            "Hides in tall, swaying grass.",
            "Slowly lifts its head.",
            "Hesitant to explore new areas.",
            "Ears flick back in shyness.",
            "Treads lightly on the ground.",
            "Skittishly flinches away.",
            "Hides behind a fellow fawn.",
            "Shyly samples a new plant.",
            "Hunches down in shyness.",
            "Ears perk with curiosity.",
            "Shivers from a cool wind.",
            "Tense around unfamiliar animals.",
            "Avoids larger creatures.",
            "Shyly nibbles at low branches.",
            "Hides behind a rock.",
            "Ears rotate with nervousness.",
            "Hesitant to join in play.",
            "Snorts with uncertainty.",
            "Softly mews for attention.",
            "Shyly treads on soft soil.",
            "Hesitates to cross a stream.",
            "Ears quiver with tension.",
            "Skittish around loud sounds.",
            "Shyly nuzzles a soft plant.",
            "Hides in the shadow of trees.",
            "Trembles near rushing water.",
            "Tensely watches for danger.",
            "Ears angle toward movement.",
            "Shyly observes from a hill.",
            "Softly bumps into a friend.",
            "Hunches down to hide.",
            "Avoids eye contact with strangers.",
            "Shyly explores a quiet glade.",
            "Timidly wades into a pond.",
            "Nervous around other creatures.",
            "Trembles in tall, swaying grass.",
            "Ears swivel to listen closely.",
            "Quivers at the slightest noise.",
            "Hesitates to approach water.",
            "Shyly grazes near the edge.",
            "Shivers when meeting others.",
            "Startled by a distant call.",
            "Skittish when approached.",
            "Trembles near the forest's edge.",
            "Ears flicker with uncertainty.",
            "Shyly approaches a flower.",
            "Timidly explores a new trail.",
            "Nervously approaches a pond.",
            "Tense around larger creatures.",
            "Hides near a friendly animal.",
            "Shyly sniffs at fallen leaves.",
            "Softly bleats for reassurance.",
            "Hesitates to cross a bridge.",
            "Ears flick back in surprise.",
            "Skittishly inspects a log.",
            "Trembles in the cool breeze.",
            "Shyly backs away from others.",
            "Nervous around sudden movement.",
            "Cautiously tastes a new plant.",
            "Hides behind a gentle slope.",
            "Shyly rests in a quiet grove."            
        }
        local emote_summon = {
            "Stretches its legs after a peaceful slumber.",
            "Slowly blinks its innocent eyes awake.",
            "Nuzzles its mother for morning comfort.",
            "Takes a moment to yawn and stretch.",
            "Gently flicks its tail to shake off sleep.",
            "Cautiously rises to its wobbly feet.",
            "Softly bleats to greet the new day.",
            "Sniffs the morning air with curiosity.",
            "Grazes on dew-kissed grass at dawn.",
            "Ears perk up as it listens to nature's symphony.",
            "Nudges its sibling with a friendly greeting.",
            "Twitches its nose as it sniffs fresh clover.",
            "Gently shakes off morning dew.",
            "Curiously examines the first light of day.",
            "Softly mews for its mother's attention.",
            "Snorts softly in the cool morning air.",
            "Blinks at the early sunlight filtering through leaves.",
            "Gently nibbles on tender, sun-warmed leaves.",
            "Wiggles its ears to clear the sleepiness.",
            "Cautiously ventures to explore its surroundings.",
            "Trots alongside its mother in the early light.",
            "Blows out a little breath, feeling refreshed.",
            "Nuzzles a fellow fawn for a morning greeting.",
            "Watches the first rays of sunlight dance.",
            "Takes a moment to groom its soft fur.",
            "Sniffs at a patch of fragrant morning flowers.",
            "Playfully hops with joy at daybreak.",
            "Stretches its neck to reach tasty morning leaves.",
            "Blinks at the beauty of the world awakening.",
            "Curiously watches a morning butterfly.",
            "Nudges a fallen leaf with its velvety nose.",
            "Gently sniffs at the day's new adventures.",
            "Twitches its tail as it listens to bird songs.",
            "Nibbles on a fallen apple at sunrise.",
            "Wiggles its tail with the joy of a new day.",
            "Cautiously approaches a bubbling brook.",
            "Gently grazes in the morning meadow.",
            "Snorts with the excitement of morning.",
            "Nuzzles its mother for reassurance.",
            "Bounces with boundless morning energy.",
            "Stretches its legs in the gentle sunlight.",
            "Watches a morning squirrel with curiosity.",
            "Sniffs the refreshing scent of morning rain.",
            "Twitches its nose at a patch of sweet clover.",
            "Nudges a fallen leaf with curiosity.",
            "Twitches its tail at the arrival of dawn.",
            "Nuzzles a friendly critter awake.",
            "Curiously observes the morning stars.",
            "Bounces through the morning's first sunbeams.",
            "Stretches its neck to reach tender morning buds.",
            "Watches the world with wide-eyed morning wonder.",
            "Snorts in excitement as morning unfolds.",
            "Takes a moment to enjoy the morning serenity.",
            "Grazes on morning clover by a tranquil pond.",
            "Twitches its nose at the scent of morning pine.",
            "Nudges a fellow fawn to start the day's adventure.",
            "Blinks at the morning light filtering through trees.",
            "Takes a moment to soak in the morning's calmness.",
            "Wiggles its tail with the promise of morning play.",
            "Cautiously explores a meadow of morning fireflies.",
            "Trot alongside a babbling morning brook.",
            "Sniffs the refreshing scent of morning wildflowers.",
            "Nuzzles a friendly critter awake for the day.",
            "Twitches its tail in anticipation of morning joy.",
            "Nibbles on morning ferns by the tranquil pond.",
            "Watches the morning sun cast its warm glow.",
            "Nudges its sibling to greet the new morning.",
            "Takes a moment to savor the beauty of morning.",
            "Sniffs at the cool, crisp morning breeze with delight.",
            "Twitches its ears at the gentle morning symphony.",
            "Blinks at the morning world bathed in soft light.",
            "Nudges a fellow fawn awake with a gentle greeting.",
            "Takes a moment to appreciate the quiet beauty of morning.",
            "Sniffs at the fresh, crisp scent of morning air.",
            "Twitches its ears at the gentle morning rustling in the trees.",
            "Blinks at the morning world coming to life.",
            "Nudges a fellow fawn awake with a joyful greeting.",
            "Takes a moment to soak in the wonder of a new morning."        }
        local speak = {
            "I... I'm not sure about this.",
            "Um, maybe we should go back?",
            "It's so big out here, isn't it?",
            "I hope Mom's not too far away.",
            "The world is a bit scary, isn't it?",
            "What was that noise over there?",
            "I wish I were a bit braver...",
            "I'm not sure I like this place.",
            "Hey, let's stay close together.",
            "Did you hear that? I'm scared.",
            "Is it safe to go that way?",
            "The forest is so vast and unknown.",
            "Maybe we should be really quiet.",
            "I don't want to get lost out here.",
            "What's that rustling in the bushes?",
            "I think we should be cautious.",
            "Mom always says to be careful.",
            "The world seems so big and new.",
            "I'm not sure we should go far.",
            "I feel better when we're together.",
            "I hope nothing scary is nearby.",
            "Let's watch out for each other.",
            "What if we find something amazing?",
            "I wish I had a bit more courage.",
            "I'm glad you're with me, friend.",
            "Do you think we're safe here?",
            "I don't want to go too far alone.",
            "Sometimes, it's good to be cautious.",
            "We should stay away from trouble.",
            "Let's explore, but stay together.",
            "I heard there are wonders out there.",
            "Being brave is hard, isn't it?",
            "I like the feeling of safety.",
            "I'm not sure about this place...",
            "Let's be watchful, just in case.",
            "Sometimes, the unknown is exciting.",
            "I hope we find something amazing.",
            "I don't want to be alone out here.",
            "If only I were a bit braver...",
            "The world can be a bit overwhelming.",
            "I want to see what's out there.",
            "I'm a little nervous about this.",
            "Being cautious is a good thing.",
            "I think we should be careful.",
            "I'm so glad you're my friend.",
            "I'm not sure what to expect.",
            "I hope we'll be okay out here.",
            "Exploring is fun, but it's scary too.",
            "I want to see the world with you.",
            "The forest is full of mysteries.",
            "I don't want to get into trouble.",
            "Let's go, but stay close, okay?",
            "Sometimes, I wish I were braver.",
            "I wish we could stay here forever.",
            "What's that noise over there?",
            "Let's take things one step at a time.",
            "I'm not sure about this adventure...",
            "What if we find something magical?",
            "I'm so lucky to have you with me.",
            "I heard there are wonders out here.",
            "I'm not sure I like the dark woods.",
            "I'm glad you're here with me now.",
            "I hope nothing scary is around.",
            "The world can be big and uncertain.",
            "What's hiding in the shadows?",
            "I hope we make it back safely.",
            "Sometimes, it's good to be cautious.",
            "I'm excited, but also a bit scared.",
            "I feel better when we're together.",
            "I don't want to be alone out here.",
            "Let's watch out for each other.",
            "I wish I could be braver like you.",
            "The forest is full of mysteries.",
            "I hope we'll find something amazing.",
            "Let's explore, but stay close, okay?",
            "I'm not sure what to expect, really.",
            "I'm glad we're on this adventure.",
            "Being cautious is a good thing.",
            "The unknown is a bit scary, right?",
            "I'm a little nervous about this journey.",
            "I don't want to be lost out here.",
            "I hope we have a safe journey.",
            "Let's stick together, just in case.",
            "I want to discover new things with you.",
            "I'm so grateful for your company.",
            "The world is a bit big, isn't it?",
            "I'm not sure we should go far away.",
            "I hope we'll find something beautiful.",
            "I wish I had your courage, really.",
            "I heard the forest is full of wonders.",
            "I'm glad you're my friend in this."
        }
        local speak_win = {
            "I can't believe we did it!",
            "That was so exciting!",
            "We actually won!",
            "I'm amazed we pulled it off.",
            "I'm so proud of us!",
            "I didn't know we had it in us.",
            "Wow, that was intense!",
            "I'm still catching my breath.",
            "We make a great team!",
            "I never thought we'd win!",
            "I'm feeling quite brave now.",
            "That was a real adventure!",
            "I can't stop smiling!",
            "We should celebrate!",
            "I'm so happy we did it.",
            "I feel like a real hero!",
            "I'm glad you were with me.",
            "This is a moment to remember!",
            "I'm in shock, but in a good way.",
            "We really showed them!",
            "I didn't know we were so strong.",
            "We should do this more often!",
            "I feel like I can take on anything!",
            "That was quite the journey!",
            "I'll treasure this victory.",
            "I'm not so shy anymore!",
            "I'm feeling invincible!",
            "We should be proud of ourselves.",
            "This is a day to remember!",
            "I'll always cherish this moment.",
            "I didn't expect this at all!",
            "I'm on top of the world!",
            "We really proved ourselves!",
            "I'm so glad we came out on top.",
            "I'm still a bit surprised.",
            "I can't believe we won!",
            "We make a great team, don't we?",
            "This is a story to tell the herd.",
            "I'm beaming with confidence now.",
            "I'm so thrilled right now!",
            "I feel like I've grown so much.",
            "I didn't think we'd make it!",
            "I'll never forget this day.",
            "We should be really proud.",
            "I'm grateful for your help.",
            "We faced that challenge head-on!",
            "I didn't know we were so tough.",
            "I can't wipe this grin off my face!",
            "I'm so glad we didn't give up.",
            "We really outdid ourselves!",
            "This is a memory for a lifetime.",
            "I'm still trying to believe it.",
            "I'm on cloud nine right now!",
            "I never expected this outcome.",
            "We truly are an amazing team!",
            "I'll remember this forever.",
            "I feel like a new fawn now.",
            "I'm so thankful for your support.",
            "We did something incredible!",
            "I never thought we'd succeed.",
            "I'm feeling so proud of us.",
            "We should pat ourselves on the back!",
            "This victory is unbelievable!",
            "I'm thrilled beyond words.",
            "I didn't realize we had it in us.",
            "We faced our fears and won!",
            "I'll always hold this close to my heart.",
            "I'm feeling incredibly brave now.",
            "I'm so happy we pulled it off.",
            "We really are a dynamic duo!",
            "I didn't know we had such strength.",
            "I can't stop smiling about this.",
            "We should cherish this moment.",
            "I'm still amazed by our victory.",
            "I'm beaming with joy right now.",
            "I'm feeling quite heroic!",
            "I'm so proud of what we achieved.",
            "We exceeded all expectations!",
            "I'll treasure this memory forever.",
            "I didn't know we were this capable.",
            "I'm on top of the world today!",
            "We really proved ourselves, didn't we?",
            "I'm still in awe of our success.",
            "I can't believe we did it!",
            "We are a force to be reckoned with!",
            "I'm brimming with confidence now.",
            "I'm so grateful for your support.",
            "We conquered that challenge!",
            "I never thought we'd come out on top.",
            "I'm feeling so proud of us!",
            "We're an unstoppable team!",
            "I'll never forget this moment.",
            "I didn't realize we had such courage.",
            "I can't wipe this smile off my face!",
            "We truly are exceptional!",
            "This is a memory to cherish.",
            "I'm still trying to take it all in.",
            "I'm on cloud nine right now!",
            "I didn't know we had it in us!",
            "We really showed our mettle.",
            "I'll always hold this close to my heart.",
            "I'm feeling incredibly brave now.",
            "I'm so happy we persevered.",
            "We make an incredible team!",
            "I'm bursting with pride.",
            "I'm still amazed at our victory.",
            "I'm feeling like a true champion!",
            "I'm so glad you were with me.",
            "We should celebrate our triumph!",
            "I'm in disbelief, but in a good way.",
            "We exceeded all expectations!",
            "I'll cherish this memory forever.",
            "I didn't know we were this resilient.",
            "I'm on top of the world today!",
            "We really proved ourselves, didn't we?",
            "I'm still in awe of our success."
        }
        local speak_dead = {
            "The meadow's beauty will live on.",
            "In the embrace of nature, I find peace.",
            "The sun sets on my life, but it rises for others.",
            "A leaf falls, and so do I.",
            "My last breath, a gift to the forest.",
            "I return to the earth, where I belong.",
            "Whispers of the wind cradle my passing.",
            "The stream of life carries me away.",
            "As petals fall, so do I, gracefully.",
            "In death, I become a part of the wilderness.",
            "The forest will remember my innocence.",
            "I fade into the twilight, a gentle dream.",
            "My spots blend with the shadows of the woods.",
            "A part of the cycle, I become the soil.",
            "Amongst the ferns, I take my final rest.",
            "My eyes close, but the forest's story continues.",
            "The owl's song welcomes me to the night.",
            "I'll find my place among the constellations.",
            "Autumn's embrace carries me to the ground.",
            "My soul dances with the fireflies.",
            "Whisked away by the breeze, I depart.",
            "My life's page turns in the book of nature.",
            "I leave my hoofprints in the sands of time.",
            "As a fawn, I was fleeting, like a morning mist.",
            "From the heart of the woods, I return.",
            "Moss and ferns will clothe my resting place.",
            "In the moonlight, I become a whisper in the forest.",
            "The river's lullaby cradles my farewell.",
            "The forest's secrets are my eternal companions.",
            "My spirit roams free among the ancient trees.",
            "With a final leap, I touch the sky.",
            "The flowers weep, and so do I.",
            "In death, I find solace in the shadows.",
            "A fading echo in the wilderness.",
            "My life's chapter ends, but the story continues.",
            "I join the tapestry of nature's art.",
            "With each heartbeat, the forest lives.",
            "I was a fleeting dream in the meadow's sleep.",
            "The forest's heart still beats within me.",
            "From a fawn to eternity in the forest's arms.",
            "In the silence of death, I find unity.",
            "Leaves fall, and so do I, gracefully.",
            "The stars above, my eternal companions.",
            "In the moon's glow, I take my final bow.",
            "I return to the cradle of the forest.",
            "My spirit soars with the eagles.",
            "A gentle rustle in the underbrush, my goodbye.",
            "The night sky welcomes me to the infinite.",
            "With every leaf that rustles, remember me.",
            "I leave my mark in the whispers of the trees.",
            "A whisper on the breeze, I fade away.",
            "The forest's secrets are safe within me.",
            "The meadow's colors paint my farewell.",
            "The river carries my memories downstream.",
            "In the hush of twilight, I find my end.",
            "The forest floor, my final resting place.",
            "I become one with the ancient oaks.",
            "The stars twinkle, a part of me in each.",
            "In the embrace of the night, I find serenity.",
            "The deer and I are kin once more.",
            "The wind's whisper tells my tale.",
            "As the leaves turn, so do I.",
            "A fawn's journey is brief, but beautiful.",
            "My soul finds freedom in the wilderness.",
            "The forest's symphony plays on without me.",
            "With the fireflies, my spirit dances.",
            "In death, I become part of the earth's song.",
            "I become a memory in the eyes of the doe.",
            "With every dewdrop, I find renewal.",
            "A fleeting shadow in the moonlight's glow.",
            "I find my place in the mossy embrace.",
            "The forest's heart is where I belong.",
            "In the rustling leaves, I'm remembered.",
            "The river's current carries me to the beyond.",
            "I was but a note in the forest's melody.",
            "Amongst the stars, I take my final rest.",
            "The owl's hoots echo my farewell.",
            "With the foxes and rabbits, I'm home.",
            "A part of the circle of life, I return.",
            "In the dawn's light, I find my ending.",
            "The squirrel's chatter shares my story.",
            "In the embrace of twilight, I fade.",
            "I'll watch over the meadow from above.",
            "With the rain, my spirit finds refreshment.",
            "The forest's spirit lives on in me.",
            "As a fawn, I was the morning's first light.",
            "The river's song carries my essence.",
            "My soul takes flight with the butterflies.",
            "Among the wildflowers, I rest in peace.",
            "In the gentle rain, I find my end.",
            "I become a part of the forest's tapestry.",
            "With each heartbeat, nature's rhythm continues.",
            "In the rustling reeds, I find my solace.",
            "The stars twinkle, a reminder of my presence.",
            "I leave my footprints in the dew-kissed grass.",
            "A breeze carries my memory through the woods.",
            "In the hush of the forest, I'm remembered.",
            "With the spirits of the woods, I'm united.",
            "A fading whisper in the meadow's grass.",
            "I become a part of the forest's eternal soul."
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
