if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s560 = function(db) 
    db.content.petComments.s560 = function(db)
        local phrases = {
            "Mine, mine, mine!",
            "Back off, or I'll peck your beak!",
            "This beach belongs to the gulls.",
            "Find your own fishing spot, loser!",
            "Scuttle away, little crab!",
            "You call that a catch? Pathetic!",
            "My wings are stronger than yours.",
            "I'll dive-bomb you if you don't leave.",
            "Feathers of fear, that's what you are.",
            "I'm the top gull around here.",
            "Stop flapping around like a fish out of water.",
            "The early gull gets the fish.",
            "Squawk off, you plankton-brained guppy!",
            "My calls are music; yours are noise.",
            "Beak sharp as a harpoon, watch out!",
            "Gather 'round, my adoring fans!",
            "I've got more friends than you do.",
            "Do I smell fish? Oh, it's just you.",
            "This is my sky, and you're just a cloud.",
            "I'd invite you to the feast, but I won't.",
            "Wings of power, wings of glory!",
            "Catch me if you can, slowpoke!",
            "Feathers of gold, attitude to match.",
            "I'm the original beachcomber.",
            "Fish are friends, but not for you.",
            "Who invited you to our flock, huh?",
            "Life's a beach, and I own it.",
            "You're just a gullible gull.",
            "Step aside, I'm the real seagull superstar.",
            "You need an upgrade, from guppy to gull.",
            "Your flapping is so last season.",
            "I've got the best nest in town.",
            "The ocean is my playground.",
            "Cry me a river, I'll fly over it.",
            "I'm the king of the coast.",
            "My beak's a missile, your tail feathers are tissue.",
            "What's with that feather style?",
            "I'd offer you some wisdom, but you can't afford it.",
            "I'm a seagull sensation, don't you know?",
            "You're a fish-flavored failure.",
            "You're just a shell of a gull.",
            "Don't even try to soar with me.",
            "You'll never catch me, fish-face!",
            "Feathered finesse, baby!",
            "I've got talons of steel.",
            "I've seen fish smarter than you.",
            "Are you even a real seagull?",
            "Catch me if you can, rookie.",
            "I make seagull look good.",
            "I'm the captain of this beach.",
            "Do you even lift, bro?",
            "You're just a squawking sideshow.",
            "My swoop game is on point.",
            "I'm the Picasso of seagulls.",
            "Fishermen love me more.",
            "You're the reason we have a bad rep.",
            "I'm the top dog of the sky.",
            "You're a feathered fool, and I'm the king.",
            "Your flapping is for the birds.",
            "I'm the ultimate beachcombing pro.",
            "Fish tremble at the sight of me.",
            "I'm a gull of impeccable taste.",
            "Even dolphins envy my moves.",
            "You're just a gullible guppy.",
            "My squawk is better than your speech.",
            "The sky's the limit for me.",
            "This beach is my runway.",
            "I'm a seagull sensation.",
            "You couldn't catch a cold!",
            "I'm the reigning champion of the coast.",
            "Why don't you just wing it and leave?",
            "Fishermen send me thank-you cards.",
            "My shadow alone sends crabs scuttling.",
            "Get a grip, you gullible gull.",
            "I'm the top gun of the sea and sky.",
            "I don't share my seashells with losers.",
            "I've got more followers than you.",
            "Your squawk is weak, mine's sleek.",
            "I'm a feathered force of nature.",
            "Why don't you dive into the deep end and stay there?",
            "I'm a seagull trendsetter.",
            "Seagulls bow down when I'm in town.",
            "You're the bottom of the pecking order.",
            "I'm a wave-rider extraordinaire.",
            "I'm a gull of destiny; you're just a gull of density."
        }
        return phrases[math.random(1, OracleHUD_TableGetLength(phrases))]
    end
end
