if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s646 = function(db) 
    db.content.petComments.s646 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "Clucks in a high-pitched tone",
            "Struts like a runway model",
            "Attempts to dance the chicken dance",
            "Tries to lay a square egg",
            "Wears a tiny top hat and struts around",
            "Pretends to be a chicken superhero",
            "Flops on its back and pretends to sunbathe",
            "Tries to do a moonwalk",
            "Wears oversized sunglasses and acts cool",
            "Dresses up in a feather boa",
            "Attempts to juggle imaginary eggs",
            "Has a pretend tea party with feathers as guests",
            "Pretends to be a chicken astronaut",
            "Practices its stand-up comedy routine",
            "Tries to play a tiny air guitar",
            "Pretends to be a chicken pirate searching for 'treasure'",
            "Wears a miniature detective hat and investigates",
            "Has a staring contest with a garden gnome",
            "Sings 'Cluck Karaoke' with imaginary microphone",
            "Attempts to skateboard on a tiny ramp",
            "Pretends to be a chicken chef with a feathered apron",
            "Takes a 'chicken selfie' with an invisible smartphone",
            "Acts like a chicken news reporter",
            "Pretends to be a chicken ninja with stealthy moves",
            "Performs a 'chicken magic' show with imaginary tricks",
            "Tries to breakdance like a pro",
            "Has a 'chicken spa day' with imaginary treatments",
            "Pretends to be a chicken superhero fighting crime",
            "Wears a chicken-sized bowtie and acts dapper",
            "Attempts to do 'chicken yoga' poses",
            "Dresses up as a chicken rockstar with feathered hair",
            "Has a 'chicken picnic' with invisible snacks",
            "Pretends to be a chicken doctor with a toy stethoscope",
            "Tries to do a 'chicken conga line'",
            "Acts like a 'chicken professor' with imaginary lectures",
            "Attempts to moonwalk like Michael Jackson",
            "Pretends to be a chicken firefighter with a toy hose",
            "Wears a feathered tiara and pretends to be a princess",
            "Acts like a 'chicken superhero sidekick'",
            "Tries to 'chicken break' dance",
            "Has a 'chicken tea party' with imaginary tea and cookies",
            "Pretends to be a chicken construction worker",
            "Wears a 'chicken disco' outfit and dances wildly",
            "Tries to imitate famous chicken characters from movies",
            "Acts like a 'chicken cowboy' with a tiny hat and lasso",
            "Pretends to be a chicken scientist with invisible experiments",
            "Wears a chicken-sized tuxedo and acts formal",
            "Attempts a 'chicken limbo' with an imaginary pole",
            "Has a 'chicken carnival' with make-believe rides",
            "Pretends to be a 'chicken detective' solving mysteries",
            "Tries to do 'chicken acrobatics'",
            "Wears a 'chicken disco ball' costume and dances",
            "Acts like a 'chicken tour guide' with invisible tourists",
            "Pretends to be a chicken artist with a feathered paintbrush",
            "Tries to 'chicken moonwalk' like Michael Jackson",
            "Has a 'chicken parade' with imaginary floats",
            "Wears a chicken-sized crown and pretends to be a king",
            "Acts like a 'chicken explorer' in search of hidden treasures",
            "Pretends to be a 'chicken race car driver'",
            "Tries to do 'chicken ballet'",
            "Wears a feathered beret and acts like an artist",
            "Has a 'chicken puppet show' with invisible puppets",
            "Pretends to be a 'chicken lifeguard' at the beach",
            "Tries to 'chicken skateboard' on a tiny ramp",
            "Acts like a 'chicken magician' with disappearing acts",
            "Wears a chicken-sized bowler hat and acts fancy",
            "Pretends to be a 'chicken chef' cooking a gourmet meal",
            "Tries to 'chicken karate' with imaginary moves",
            "Has a 'chicken spa day' with invisible facials",
            "Wears a feathered party hat and celebrates a 'chicken party'",
            "Acts like a 'chicken astronaut' exploring space",
            "Pretends to be a 'chicken comedian' with funny jokes",
            "Tries to 'chicken rock' with air guitar solos",
            "Has a 'chicken selfie contest' with other chickens",
            "Wears a chicken-sized detective coat and solves mysteries",
            "Acts like a 'chicken ninja' with stealthy moves",
            "Pretends to be a 'chicken superhero' fighting crime",
            "Tries to do 'chicken breakdance moves'",
            "Has a 'chicken tea party' with invisible tea and cupcakes",
            "Wears a feathered cowboy hat and acts like a rodeo star",
            "Pretends to be a 'chicken professor' giving imaginary lectures",
            "Tries to 'chicken moonwalk' like Michael Jackson",
            "Acts like a 'chicken firefighter' with a toy hose",
            "Wears a feathered tiara and pretends to be a princess",
            "Pretends to be a 'chicken superhero sidekick'",
            "Tries to 'chicken break' dance",
            "Has a 'chicken picnic' with invisible sandwiches",
            "Pretends to be a 'chicken doctor' with a toy stethoscope",
            "Wears a feathered top hat and acts dapper",
            "Acts like a 'chicken tour guide' with invisible tourists",
            "Tries to do a 'chicken limbo' with an imaginary pole",
            "Has a 'chicken carnival' with make-believe games",
            "Pretends to be a 'chicken detective' solving mysteries",
            "Tries to do 'chicken acrobatics'",
            "Wears a 'chicken disco ball' costume and dances wildly",
            "Acts like a 'chicken explorer' in search of hidden treasures",
            "Pretends to be a 'chicken race car driver'",
            "Tries to do 'chicken ballet'",
            "Wears a feathered beret and acts like an artist",
            "Has a 'chicken puppet show' with invisible puppets",
            "Pretends to be a 'chicken lifeguard' at the beach",
            "Tries to 'chicken skateboard' on an imaginary ramp",
            "Acts like a 'chicken magician' with disappearing acts",
            "Wears a chicken-sized bowler hat and acts fancy",
            "Pretends to be a 'chicken chef' cooking a gourmet meal",
            "Tries to 'chicken karate' with imaginary moves",
            "Has a 'chicken spa day' with invisible facials",
            "Wears a feathered party hat and celebrates a 'chicken party'",
            "Acts like a 'chicken astronaut' exploring space",
            "Pretends to be a 'chicken comedian' with funny jokes",
            "Tries to 'chicken rock' with air guitar solos",
            "Has a 'chicken selfie contest' with other chickens",
            "Wears a chicken-sized detective coat and solves mysteries",
            "Acts like a 'chicken ninja' with stealthy moves",
            "Pretends to be a 'chicken superhero' fighting crime"
        }
        local emote_summon = {
            "Struts in like it owns the place",
            "Clucks assertively with authority",
            "Flaps wings to show off its power",
            "Performs a 'chicken dominance dance'",
            "Stands tall and puffs out its chest",
            "Fluffs up feathers to appear formidable",
            "Paces in a dominant manner",
            "Crows loudly to establish control",
            "Pokes beak at challengers with vigor",
            "Stares down others with unwavering confidence",
            "Performs a 'chicken alpha pose'",
            "Holds its head high like a ruler",
            "Flaps wings like a 'chicken conqueror'",
            "Doubles in size with 'chicken supremacy'",
            "Struts with a 'chicken dictator' attitude",
            "Commands with 'chicken mightiness'",
            "Preening with exaggerated dominance",
            "Does a 'chicken victory parade'",
            "Pokes beak at the sky with authority",
            "Waddles in with 'chicken swagger'",
            "Performs a 'chicken superhero landing'",
            "Flaps wings with 'chicken mastery'",
            "Hops around with 'chicken grandeur'",
            "Scatters 'chicken dominance' dramatically",
            "Paces with 'chicken authority'",
            "Struts in slow motion with 'chicken power'",
            "Crows with 'chicken rulership'",
            "Stands tall like a 'chicken monarch'",
            "Fluffs up and 'claims territory'",
            "Proudly displays 'chicken dominance'",
            "Performs a 'chicken emperor strut'",
            "Flaps wings like a 'chicken legend'",
            "Doubles in size with 'chicken mightiness'",
            "Struts with a 'chicken dictator' demeanor",
            "Commands with 'chicken sovereignty'",
            "Preening with 'chicken grandeur'",
            "Does a 'chicken victory procession'",
            "Pokes beak at the heavens with might",
            "Waddles with 'chicken majesty'",
            "Performs a 'chicken superhero takeoff'",
            "Flaps wings with 'chicken distinction'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken authority' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken dominance'",
            "Crows with 'chicken supremacy'",
            "Stands tall like a 'chicken emperor'",
            "Fluffs up and 'claims the realm'",
            "Proudly displays 'chicken superiority'",
            "Performs a 'chicken king's procession'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken grandeur'",
            "Struts with 'chicken rulership'",
            "Commands with 'chicken eminence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory spectacle'",
            "Pokes beak at the cosmos with authority",
            "Waddles with 'chicken magnificence'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken sovereignty'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken leadership' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken authority'",
            "Crows with 'chicken sovereignty'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the universe'",
            "Proudly displays 'chicken leadership'",
            "Performs a 'chicken emperor's grand parade'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken eminence'",
            "Struts with 'chicken dominance'",
            "Commands with 'chicken supremacy'",
            "Preening with 'chicken grandeur'",
            "Does a 'chicken victory triumph'",
            "Pokes beak at the galaxy with might",
            "Waddles with 'chicken majesty'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken distinction'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken brilliance' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken grandiosity'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the cosmos'",
            "Proudly displays 'chicken eminence'",
            "Performs a 'chicken emperor's grand procession'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken majesty'",
            "Struts with 'chicken grandeur'",
            "Commands with 'chicken magnificence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory extravaganza'",
            "Pokes beak at the galaxy with authority",
            "Waddles with 'chicken superiority'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken sovereignty'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken greatness' dramatically",
            "Paces with 'chicken nobility'",
            "Struts in slow motion with 'chicken authority'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the cosmos'",
            "Proudly displays 'chicken eminence'",
            "Performs a 'chicken emperor's grand parade'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken majesty'",
            "Struts with 'chicken grandeur'",
            "Commands with 'chicken magnificence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory triumph'",
            "Pokes beak at the galaxy with might",
            "Waddles with 'chicken opulence'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken distinction'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken brilliance' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken grandiosity'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the universe'",
            "Proudly displays 'chicken leadership'",
            "Performs a 'chicken emperor's grand procession'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken eminence'",
            "Struts with 'chicken dominance'",
            "Commands with 'chicken supremacy'",
            "Preening with 'chicken grandeur'",
            "Does a 'chicken victory extravaganza'",
            "Pokes beak at the galaxy with authority",
            "Waddles with 'chicken superiority'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken sovereignty'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken greatness' dramatically",
            "Paces with 'chicken nobility'",
            "Struts in slow motion with 'chicken authority'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the cosmos'",
            "Proudly displays 'chicken eminence'",
            "Performs a 'chicken emperor's grand parade'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken majesty'",
            "Struts with 'chicken grandeur'",
            "Commands with 'chicken magnificence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory triumph'",
            "Pokes beak at the galaxy with might",
            "Waddles with 'chicken opulence'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken distinction'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken brilliance' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken grandiosity'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the universe'",
            "Proudly displays 'chicken leadership'",
            "Performs a 'chicken emperor's grand procession'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken eminence'",
            "Struts with 'chicken dominance'",
            "Commands with 'chicken supremacy'",
            "Preening with 'chicken grandeur'",
            "Does a 'chicken victory extravaganza'",
            "Pokes beak at the galaxy with authority",
            "Waddles with 'chicken superiority'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken sovereignty'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken greatness' dramatically",
            "Paces with 'chicken nobility'",
            "Struts in slow motion with 'chicken authority'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the cosmos'",
            "Proudly displays 'chicken eminence'",
            "Performs a 'chicken emperor's grand parade'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken majesty'",
            "Struts with 'chicken grandeur'",
            "Commands with 'chicken magnificence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory triumph'",
            "Pokes beak at the galaxy with might",
            "Waddles with 'chicken opulence'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken distinction'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken brilliance' dramatically",
            "Paces with 'chicken rulership'",
            "Struts in slow motion with 'chicken grandiosity'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the universe'",
            "Proudly displays 'chicken leadership'",
            "Performs a 'chicken emperor's grand procession'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken eminence'",
            "Struts with 'chicken dominance'",
            "Commands with 'chicken supremacy'",
            "Preening with 'chicken grandeur'",
            "Does a 'chicken victory extravaganza'",
            "Pokes beak at the galaxy with authority",
            "Waddles with 'chicken superiority'",
            "Performs a 'chicken superhero ascent'",
            "Flaps wings with 'chicken sovereignty'",
            "Hops around with 'chicken elegance'",
            "Scatters 'chicken greatness' dramatically",
            "Paces with 'chicken nobility'",
            "Struts in slow motion with 'chicken authority'",
            "Crows with 'chicken excellence'",
            "Stands tall like a 'chicken king'",
            "Fluffs up and 'claims the cosmos'",
            "Proudly displays 'chicken eminence'",
            "Performs a 'chicken emperor's grand parade'",
            "Flaps wings like a 'chicken ruler'",
            "Doubles in size with 'chicken majesty'",
            "Struts with 'chicken grandeur'",
            "Commands with 'chicken magnificence'",
            "Preening with 'chicken regality'",
            "Does a 'chicken victory triumph'"
        }
        local speak = {
            "Why did the chicken cross the road? To show off its swagger!",
            "I'm the cock of the walk!",
            "I've got the beak that can't be beat!",
            "Cluck yeah, I'm fabulous!",
            "I'm eggstraordinary!",
            "Feathers, fluff, and fun – that's my motto!",
            "Cock-a-doodle-do it like a pro!",
            "You don't need a weather vane when I'm around!",
            "I'm a-peck-tacular!",
            "Feeling clucky today?",
            "I'm not a spring chicken, I'm a fluff chicken!",
            "Bawk-tastic!",
            "I'm the top of the pecking order!",
            "This coop isn't big enough for my ego!",
            "Egg-cuse me, I'm busy being awesome!",
            "I'm on a feather-brained adventure!",
            "I'm eggstremely good at being a chicken.",
            "Let's wing it and see what happens!",
            "What's a chicken's favorite instrument? The egg-cordion!",
            "Cluck if you're fabulous!",
            "I'm egg-cited for a great day!",
            "Fluff yeah, I'm the boss!",
            "I'm the feathered fashionista of the coop!",
            "Why did the chicken apply for a job? To make some clucking money!",
            "Feeling a little beak-nificent today!",
            "I've got the eggstreme skills!",
            "I'm not chicken – I'm just strategic in my approach!",
            "Ready to ruffle some feathers!",
            "Egg-xercise is for the birds – and that's me!",
            "What do you call a chicken who tells jokes? A comedi-hen!",
            "I'm egg-cellent at what I do!",
            "Why did the chicken sit on the clock? It wanted to be an egg-timer!",
            "My feathers are always on point!",
            "Egg-spect the unexpected with me!",
            "What do you call a chicken at the North Pole? Lost!",
            "I'm no chicken – I'm an adventurer!",
            "Bawk-bawk-bawk your boat gently down the stream!",
            "Who's the coolest chicken in town? Yours truly!",
            "Egg-static to meet you!",
            "Why did the chicken get a library card? Because it wanted to check out some 'hen-cyclopedias'!",
            "I'm no featherweight – I'm a heavyweight in awesomeness!",
            "Got any egg-citing plans for the day?",
            "I'm egg-stremely optimistic about life!",
            "What do you call a chicken that tells good stories? A 'yolk'-teller!",
            "Egg-spert at making your day better!",
            "Chicken puns are egg-squisite!",
            "I'm not a chicken – I'm a daredevil of the coop!",
            "Why did the chicken go to the seance? To talk to the other side of the road!",
            "Ready to cluck around and have some fun?",
            "I'm the real peck-tator here!",
            "What did the chicken say to the duck? 'You quack me up!'",
            "Egg-sperience life to the fullest!",
            "Why did the chicken start a band? Because it had the drumsticks!",
            "I'm no ordinary chicken – I'm a cluckstermind!",
            "Egg-cuse me, I need to spread my wings and fly!",
            "I'm not chicken – I'm egg-stremely courageous!",
            "Egg-xpect the unexpected!",
            "Why did the chicken go to the doctor? It had 'poultry' in motion!",
            "Life is too short to be cooped up!",
            "I'm the ultimate peck-nologist!",
            "Egg-citing adventures await!",
            "Why did the chicken go to the circus? It wanted to see the 'egg-siting' acrobatics!",
            "I'm egg-tremely talented!",
            "Egg-speriment with happiness!",
            "Why did the chicken join the band? Because it had the drumsticks!",
            "Ready to rule the roost!",
            "I'm no spring chicken, but I've got the moves!",
            "I'm egg-static to be me!",
            "Why did the chicken go to the art gallery? To see the 'egg-squisite' paintings!",
            "What do you call a chicken that loves pop music? A 'peck'-star!",
            "Egg-spect me to be egg-ceptional!",
            "Why did the chicken start a gardening club? It wanted to 'cultivate' some egg-squisite flowers!",
            "I'm egg-stremely fabulous!",
            "Egg-spress yourself and have a clucking good time!",
            "Why did the chicken cross the playground? To get to the other slide!",
            "I'm egg-ceptional in every way!",
            "I'm not just any chicken – I'm the clucking best!",
            "Why did the chicken start a dance party? Because it had the 'chick'-moves!",
            "Egg-spect the egg-traordinary with me!",
            "Why did the chicken become a scientist? To study 'egg-sperimental' physics!",
            "I'm egg-citing and I know it!",
            "Egg-speriment with new things every day!",
            "Why did the chicken join a comedy club? To become an 'egg-squisite' stand-up comedian!",
            "I'm egg-stremely punny!",
            "What did one chicken say to the other chicken at the dance party? 'Let's do the 'chicken' dance!'",
            "Egg-spect the unexpected and embrace it!",
            "Why did the chicken join the orchestra? Because it wanted to play the 'egg-squisite' violin!",
            "I'm egg-stremely talented and ready to cluck about it!",
            "Egg-sperience the joy of being silly!",
            "Why did the chicken go to the art class? To brush up on its 'egg-spressive' painting skills!",
            "I'm not just an ordinary chicken – I'm egg-straordinary!",
            "Why did the chicken go to the farm fashion show? To strut its 'egg-squisite' feathers on the runway!",
            "Egg-spect me to be egg-stra awesome!",
            "Why did the chicken go to the comedy club? To become an 'egg-squisite' stand-up comedian!",
            "I'm egg-stremely punny and ready to cluck you up!",
            "Egg-splore new horizons with me!",
            "Why did the chicken start a dance-off? Because it had the 'egg-citing' moves!",
            "I'm no ordinary chicken – I'm the cluckstermind of the coop!",
            "Egg-spect the egg-ceptional!",
            "Why did the chicken go to the talent show? To showcase its 'egg-straordinary' talents!",
            "I'm egg-stremely egg-sceptional!",
            "Egg-spand your horizons and embrace your inner chicken!",
            "Why did the chicken become a painter? To create 'egg-squisite' works of art!",
            "I'm egg-stremely artistic and ready to cluck-tivate your creativity!",
            "Egg-spress yourself and let your feathers shine!",
            "Why did the chicken go to the garden party? To admire the 'egg-squisite' flowers!",
            "I'm egg-tremely fabulous and egg-cited to be me!",
            "Why did the chicken go to the comedy show? To have an 'egg-squisite' time laughing!",
            "I'm egg-silarating in every way!",
            "Egg-sperience the joy of laughter and silliness!",
            "Why did the chicken go to the costume party? To show off its 'egg-traordinary' outfits!",
            "I'm not just any chicken – I'm egg-stremely stylish!",
            "Why did the chicken go to the music festival? To dance to the 'egg-citing' tunes!",
            "Egg-spect me to be egg-citing!",
            "Why did the chicken become a chef? To create 'egg-quisite' culinary delights!",
            "I'm egg-stremely egg-celent at cooking!"            
        }
        local speak_win = {
            "I clucked my way to victory!",
            "They didn't stand a chance against this beak!",
            "Feathers, meet glory. Glory, meet feathers!",
            "Who's the top chick now? Me!",
            "I'm the peck-tator of this coop!",
            "Cluck yeah, I'm the champion!",
            "I winged it and won!",
            "The pecking order has been established!",
            "Bow down to the feathered conqueror!",
            "I'm the coop's undefeated champion!",
            "I've egg-ceeded all expectations!",
            "Who's the cluckin' boss? Yours truly!",
            "Chicken power, baby!",
            "Victory is my favorite seasoning!",
            "I'm the feathered legend of this battle!",
            "Bawk-bawk-booyah!",
            "My beak is mightier than their swords!",
            "They got egg-stremely defeated!",
            "I clucked them into submission!",
            "This victory is for all my feathered friends!",
            "Egg-cellent battle, don't you think?",
            "The coop is safe under my watch!",
            "Cluckin' A, I'm good at this!",
            "Feathered and fearless!",
            "I told them I'm no chicken!",
            "Feathered victory is the best victory!",
            "They should've known better than to cross me!",
            "I'm the rooster with the most-er!",
            "Who needs a sword when you've got a beak like mine?",
            "No fowl play here, just pure victory!",
            "I'm the winged warrior they can't defeat!",
            "Cluck-tastic battle moves!",
            "I'm the beak-nificent champion!",
            "No coop is complete without a victor like me!",
            "They're just chicken feed to me!",
            "This is what 'egg-ceptional' looks like!",
            "Victory is my middle name, literally!",
            "They got a taste of my pecking order!",
            "The beak is mightier than the sword!",
            "I'm the real 'cluck'tator here!",
            "No yolk, I'm the winner!",
            "I'm the 'egg-stra' special one!",
            "Feathered and fabulous – that's me!",
            "Who needs claws when you've got talons like mine?",
            "I'm the egg-stremely victorious one!",
            "They didn't stand a clucking chance!",
            "I'm the egg-squisite winner of the battle!",
            "This victory is my crowning achievement!",
            "Cluckin' fantastic, if you ask me!",
            "I'm the 'egg-salted' champion!",
            "They couldn't handle my clucking awesomeness!",
            "I clucked my way to the top!",
            "I'm the peck-tacular victor!",
            "Feathered and ferocious!",
            "They thought they could out-cluck me, but nope!",
            "My feathers are ruffled, but I'm victorious!",
            "I'm the grand poobah of the coop!",
            "Feathered and fearless – that's me!",
            "They're in the presence of cluck-tastic greatness!",
            "I'm the 'egg-stremely' best in the coop!",
            "The coop is safe under my watchful eye!",
            "I'm the cock of the walk and the king of the coop!",
            "No one can peck on me!",
            "This is the 'egg-squisite' taste of victory!",
            "Who needs claws when you've got talons like mine?",
            "I'm the egg-stremely victorious one!",
            "They didn't stand a clucking chance!",
            "I'm the egg-squisite winner of the battle!",
            "This victory is my crowning achievement!",
            "Cluckin' fantastic, if you ask me!",
            "I'm the 'egg-salted' champion!",
            "They couldn't handle my clucking awesomeness!",
            "I clucked my way to the top!",
            "I'm the peck-tacular victor!",
            "Feathered and ferocious!",
            "They thought they could out-cluck me, but nope!",
            "My feathers are ruffled, but I'm victorious!",
            "I'm the grand poobah of the coop!",
            "Feathered and fearless!",
            "They're in the presence of cluck-tastic greatness!",
            "I'm the 'egg-stremely' best in the coop!",
            "The coop is safe under my watchful eye!",
            "I'm the cock of the walk and the king of the coop!",
            "No one can peck on me!",
            "This is the 'egg-squisite' taste of victory!",
            "Feathers, meet glory. Glory, meet feathers!",
            "Who's the top chick now? Me!",
            "I'm the peck-tator of this coop!",
            "Cluck yeah, I'm the champion!",
            "I winged it and won!",
            "The pecking order has been established!",
            "Bow down to the feathered conqueror!",
            "I'm the coop's undefeated champion!",
            "I've egg-ceeded all expectations!",
            "Who's the cluckin' boss? Yours truly!",
            "Chicken power, baby!",
            "Victory is my favorite seasoning!",
            "I'm the feathered legend of this battle!",
            "Bawk-bawk-booyah!",
            "My beak is mightier than their swords!",
            "They got egg-stremely defeated!",
            "I clucked them into submission!",
            "This victory is for all my feathered friends!",
            "Egg-cellent battle, don't you think?",
            "The coop is safe under my watch!",
            "Cluckin' A, I'm good at this!",
            "Feathered and fearless!",
            "I told them I'm no chicken!",
            "Feathered victory is the best victory!",
            "They should've known better than to cross me!",
            "I'm the rooster with the most-er!",
            "Who needs a sword when you've got a beak like mine?",
            "No fowl play here, just pure victory!",
            "I'm the winged warrior they can't defeat!",
            "Cluck-tastic battle moves!",
            "I'm the beak-nificent champion!",
            "No coop is complete without a victor like me!",
            "They're just chicken feed to me!",
            "This is what 'egg-ceptional' looks like!",
            "Victory is my middle name, literally!",
            "They got a taste of my pecking order!",
            "The beak is mightier than the sword!",
            "I'm the real 'cluck'tator here!",
            "No yolk, I'm the winner!",
            "I'm the 'egg-stra' special one!",
            "Feathered and fabulous – that's me!",
            "Who needs claws when you've got talons like mine?",
            "I'm the egg-stremely victorious one!",
            "They didn't stand a clucking chance!",
            "I'm the egg-squisite winner of the battle!",
            "This victory is my crowning achievement!",
            "Cluckin' fantastic, if you ask me!",
            "I'm the 'egg-salted' champion!",
            "They couldn't handle my clucking awesomeness!",
            "I clucked my way to the top!",
            "I'm the peck-tacular victor!",
            "Feathered and ferocious!",
            "They thought they could out-cluck me, but nope!",
            "My feathers are ruffled, but I'm victorious!",
            "I'm the grand poobah of the coop!",
            "Feathered and fearless!",
            "They're in the presence of cluck-tastic greatness!",
            "I'm the 'egg-stremely' best in the coop!",
            "The coop is safe under my watch!",
            "I'm the cock of the walk and the king of the coop!",
            "No one can peck on me!",
            "This is the 'egg-squisite' taste of victory!",
            "Who needs claws when you've got talons like mine?",
            "I'm the egg-stremely victorious one!",
            "They didn't stand a clucking chance!",
            "I'm the egg-squisite winner of the battle!",
            "This victory is my crowning achievement!",
            "Cluckin' fantastic, if you ask me!",
            "I'm the 'egg-salted' champion!",
            "They couldn't handle my clucking awesomeness!",
            "I clucked my way to the top!",
            "I'm the peck-tacular victor!",
            "Feathered and ferocious!",
            "They thought they could out-cluck me, but nope!",
            "My feathers are ruffled, but I'm victorious!",
            "I'm the grand poobah of the coop!",
            "Feathered and fearless!",
            "They're in the presence of cluck-tastic greatness!",
            "I'm the 'egg-stremely' best in the coop!",
            "The coop is safe under my watch!",
            "I'm the cock of the walk and the king of the coop!",
            "No one can peck on me!",
            "This is the 'egg-squisite' taste of victory!",
            "I clucked my way to the top!",
            "They didn't stand a chance against this beak!",
            "Feathers, meet glory. Glory, meet feathers!",
            "Who's the top chick now? Me!",
            "I'm the peck-tator of this coop!",
            "Cluck yeah, I'm the champion!",
            "I winged it and won!",
            "The pecking order has been established!",
            "Bow down to the feathered conqueror!",
            "I'm the coop's undefeated champion!",
            "I've egg-ceeded all expectations!",
            "Who's the cluckin' boss? Yours truly!",
            "Chicken power, baby!",
            "Victory is my favorite seasoning!",
            "I'm the feathered legend of this battle!",
            "Bawk-bawk-booyah!",
            "My beak is mightier than their swords!",
            "They got egg-stremely defeated!",
            "I clucked them into submission!",
            "This victory is for all my feathered friends!",
            "Egg-cellent battle, don't you think?",
            "The coop is safe under my watch!",
            "Cluckin' A, I'm good at this!",
            "Feathered and fearless!",
            "I told them I'm no chicken!",
            "Feathered victory is the best victory!",
            "They should've known better than to cross me!",
            "I'm the rooster with the most-er!",
            "Who needs a sword when you've got a beak like mine?",
            "No fowl play here, just pure victory!",
            "I'm the winged warrior they can't defeat!",
            "Cluck-tastic battle moves!",
            "I'm the beak-nificent champion!",
            "No coop is complete without a victor like me!",
            "They're just chicken feed to me!"
        }
        local speak_dead = {
            "I wish I could have laid more golden eggs.",
            "Did I truly appreciate the taste of fresh grains?",
            "I miss the sound of rain on the coop's roof.",
            "My feathers were soft; I wish I could've enjoyed them more.",
            "I wonder if my chicks grew up well without me.",
            "The farmer's kids were kind; I wish I'd let them pet me more.",
            "I should've challenged the rooster for the top perch.",
            "Why did I always run away from the scarecrow? It wasn't that scary.",
            "I never got to taste watermelon, and now I never will.",
            "I hope the humans enjoyed my clucking as much as I did.",
            "The taste of fresh grass was divine.",
            "I should've strutted my stuff more during our morning parade.",
            "The dust baths were pure bliss; I should've taken more of them.",
            "I'll never know what's on the other side of the rainbow.",
            "I should've made amends with the duck next door.",
            "The world beyond the coop was tantalizingly mysterious.",
            "I could've been a clucking sensation on social media!",
            "My feathers were like a work of art, and I didn't admire them enough.",
            "I never did figure out why they called it 'chicken scratch.'",
            "Did I ever truly find my favorite pebble to peck?",
            "The worms I caught tasted better than any fast food.",
            "I'll never know what it's like to fly high in the sky.",
            "The wind beneath my wings, I wish I felt it more often.",
            "I wonder if the pig really was my friend or just after my feed.",
            "I should've told the rooster to stop crowing so early in the morning.",
            "Did the other chickens think I was clucking strange?",
            "I should've sung more duets with the nightingales.",
            "I missed out on the thrill of a real egg hunt.",
            "The fox that got away - I should've been more cautious.",
            "I'll never get to taste the sweet, sweet corn again.",
            "The fluffy clouds were calling me; I wish I'd gone with them.",
            "Why didn't I ever learn to read the farm newspaper?",
            "The gossip at the water cooler was always interesting.",
            "I should've joined the 'Chicken Club' for social gatherings.",
            "I wish I could've danced in the rain more often.",
            "The early bird may get the worm, but did I get enough worms?",
            "I hope the cow remembers me as a good friend.",
            "The scarecrow had the best posture; I should've asked for tips.",
            "I should've taught the younger chicks about the joys of dust baths.",
            "The smell of freshly baked bread always made my beak water.",
            "I never got to see the world from the top of the haystack.",
            "The humans had so many secrets; I wish I'd eavesdropped more.",
            "I should've taken more 'selfies' with the sunflowers.",
            "The breeze in my feathers was pure bliss.",
            "I should've embraced the 'pecking order' and climbed to the top.",
            "The ladybug I befriended was a good listener; I wish I'd told her more stories.",
            "I never got to meet the famous 'Chicken Little.'",
            "I wonder if the barn cat would've been my friend if I'd tried harder.",
            "The taste of fresh strawberries, just out of reach...",
            "I should've tried yoga; my downward chicken pose could've been epic.",
            "I hope my eggs were always sunny-side up.",
            "I should've enjoyed the sunshine more and worried less about shade.",
            "The garden was my own private jungle, but I rarely explored it.",
            "I wish I'd sung more lullabies to my eggs.",
            "I hope the farm dog remembers our games of chase.",
            "I should've spoken to the wise old owl for advice more often.",
            "The sunrise over the fields was breathtaking; I should've seen more of them.",
            "I wonder what the duck pond was like; I was always too chicken to go near it.",
            "I should've honed my clucking skills to become a farmyard superstar.",
            "The red barn was a symbol of home; I wish I'd appreciated it more.",
            "I hope the wind carries my clucks far and wide.",
            "I should've stayed up past my bedtime and counted the stars.",
            "The rainbows were like bridges to a magical world; I wish I'd crossed them.",
            "I'll never know what it's like to perch on a branch and watch the world go by.",
            "I wish I'd befriended the songbirds and learned their melodies.",
            "I should've embraced the 'pecking order' and enjoyed the view from the top.",
            "The scarecrow might've been a better conversationalist than I thought.",
            "I hope the sparrows remember me as a fellow feathered friend.",
            "I should've explored the garden for hidden treasures.",
            "The grass was greener on the other side; I should've gone there more often.",
            "I'll never experience the thrill of scratching up hidden gems from the dirt.",
            "I wish I'd witnessed more sunsets with the love of my life.",
            "I should've shared my wisdom with the young chicks.",
            "The feeling of the wind ruffling my feathers was a true delight.",
            "I should've formed a 'Cluck Choir' to serenade the farmyard.",
            "The moonlit nights were full of mystery and wonder; I wish I'd reveled in them.",
            "I hope the wind carries my clucks to distant lands.",
            "I should've stayed up late to watch the stars with the owls.",
            "The fox in the distance, I should've been more vigilant.",
            "I wish I'd traveled the world on chicken wings.",
            "I should've done more 'beak-tapping' with my barnyard friends.",
            "The humans' laughter was infectious; I wish I'd joined in more often.",
            "I'll never know what it's like to chase my own shadow.",
            "I wish I'd learned to play the harmonica like the old farmhand.",
            "I should've told the rabbits to stop raiding the vegetable patch.",
            "The scent of the apple orchard was a sweet temptation I rarely indulged in.",
            "I hope the toad remembers our talks by the garden pond.",
            "I should've danced more often in the golden hayfields.",
            "The butterflies were like flying flowers; I wish I'd admired them more.",
            "I'll never know what it's like to catch a glimpse of a shooting star.",
            "I wish I'd tasted the sweet nectar of blooming flowers.",
            "I should've attended more 'Farmyard Feasts' and shared stories around the trough.",
            "The starlit nights were an open book of dreams; I wish I'd read more pages.",
            "I hope the winds of heaven are as gentle as the summer breeze.",
            "I should've spent more time with the wise old oak tree.",
            "The golden grains of wheat were like hidden treasures in the fields.",
            "I wish I'd watched the fireflies dance in the twilight.",
            "I should've joined the mice in their moonlit feasts in the barn.",
            "The taste of fresh water from the trough was a simple joy I often ignored.",
            "I'll never know the feeling of swimming in the duck pond with my feathered friends.",
            "I wish I'd listened more closely to the secrets of the forest.",
            "I should've joined the rooster's morning symphony and added my own notes.",
            "The warmth of the sun on my feathers was a blessing I took for granted.",
            "I hope my clucks reached the hearts of the farmyard animals.",
            "I should've taken more time to enjoy the cool breeze under the shade tree.",
            "The farm was my kingdom, and I should've explored it like a true ruler.",
            "I wish I'd befriended the bees and learned the art of making honey.",
            "I should've explored the barn's hidden corners and discovered its mysteries.",
            "The taste of juicy watermelon on a hot summer day was a distant dream.",
            "I hope the farm remains a sanctuary for all my barnyard friends."
        }
        if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        PlaySound(OracleHUD_PB_PetSoundsGetSoundKitId(646))
        return comment
    end
end
