if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s675 = function(db) 
    db.content.petComments.s675 = function(db, type)
        local comment = nil
        local collection = nil
        if (type == nil) then
            type = "speak"
        end
        local emote = {
            "scampers through the shadows, nimble and unnoticed.",
            "squeaks softly, communicating with fellow rodents.",
            "sniffs the air, detecting the scent of potential food.",
            "pokes its nose into a small crevice, exploring the unknown.",
            "chirps excitedly, expressing its curiosity.",
            "nimbly climbs a vertical surface, displaying agility.",
            "pauses to groom its fur with meticulous care.",
            "chases its tail in playful circles, a dance of amusement.",
            "nudges a small object with its nose, testing its surroundings.",
            "scurries along a narrow ledge with balance and precision.",
            "chatters its teeth, a sign of excitement or agitation.",
            "hops from one paw to another, displaying bursts of energy.",
            "snuggles against another rat, seeking companionship.",
            "squeezes through a tight space, showcasing flexibility.",
            "stands on hind legs, surveying the surroundings with alertness.",
            "shakes off imaginary water, mimicking a grooming routine.",
            "sniffs at a flower or plant, exploring nature's scents.",
            "curiously inspects a passing insect, considering it as prey.",
            "chases a dust mote with swift and playful movements.",
            "nibbles on a small object, testing its teeth and jaws.",
            "scampers in a zigzag pattern, testing its reflexes.",
            "pounces on a small shadow, showcasing hunting instincts.",
            "snuggles into a warm patch of sunlight, seeking warmth.",
            "wiggles its ears in response to distant sounds.",
            "sits up on hind legs, appearing alert and watchful.",
            "pokes its head out from a hiding spot, observing the world.",
            "scampers around in a circle, creating a small whirlwind of motion.",
            "shivers and fluffs its fur in response to a breeze.",
            "sniffs at a discarded piece of cloth, checking for interesting scents.",
            "licks its tiny paws, grooming away the remnants of a meal.",
            "scampers up a vertical surface to reach a higher vantage point.",
            "paws at the ground, pretending to bury or uncover something.",
            "nibbles on a leaf or small piece of vegetation, testing its taste.",
            "chirps softly, exchanging greetings with other rodents.",
            "squeaks loudly, alerting nearby creatures to its presence.",
            "pokes its nose into a hole, exploring potential hiding spots.",
            "balances on a narrow beam or ledge, showcasing agility.",
            "sniffs at the ground, searching for hidden crumbs or treats.",
            "rolls onto its back and wriggles, displaying contentment.",
            "scampers in and out of shadows, playing a game of hide-and-seek.",
            "stands still for a moment, appearing to listen intently.",
            "nuzzles against a familiar object or companion, seeking comfort.",
            "hops from one paw to another in a joyful display of energy.",
            "scurries to a sunny spot, basking in the warmth of sunlight.",
            "squeaks in protest, expressing displeasure or annoyance.",
            "twitches its whiskers, showing signs of excitement or curiosity.",
            "scampers in a straight line, moving with purpose.",
            "sniffs at a passing breeze, detecting scents carried on the wind.",
            "sits up and scratches behind its ear with a hind leg.",
            "chases a tiny reflection or glint of light with keen interest.",
            "hops onto a higher surface to observe the surroundings.",
            "snuggles against a fellow rat, demonstrating camaraderie.",
            "squeaks softly while grooming itself, a sign of contentment.",
            "scurries in and out of small openings, exploring hidden nooks.",
            "nibbles on a twig or small piece of wood, testing its gnawing ability.",
            "scampers alongside a wall or ledge, hugging the shadows.",
            "stands on its hind legs and twitches its nose, appearing curious.",
            "paws at the ground in a digging motion, mimicking burrowing behavior.",
            "sniffs at its surroundings, checking for changes or potential dangers.",
            "pokes its head out from behind an object, observing cautiously.",
            "chirps excitedly while scampering, expressing joy.",
            "squeaks softly as it discovers a hidden stash of crumbs.",
            "twitches its tail with a quick and rhythmic motion.",
            "sniffs at a passing human, observing with cautious interest.",
            "scurries in a circle before settling down, creating a small nest.",
            "stands on hind legs and stretches, showing off its flexibility.",
            "paws at the ground in a rhythmic pattern, a unique rodent dance.",
            "snuggles into the folds of discarded cloth, seeking warmth.",
            "nibbles on a small pebble or object, testing its curiosity.",
            "scampers playfully, engaging in a game of rodent tag.",
            "squeaks in delight, displaying a sense of happiness.",
            "pokes its nose into a crack or crevice, exploring hidden spaces.",
            "balances on its hind legs, looking as if it's standing tall.",
            "sniffs at a fellow rat, exchanging familiar scents.",
            "paws at its own reflection, displaying curiosity.",
            "scampers through a puddle, splashing playfully.",
            "hops onto a higher surface and surveys the area with keen eyes.",
            "snuggles against a warm object, seeking comfort and companionship.",
            "squeaks softly while grooming another rat, expressing affection.",
            "scurries alongside a wall, utilizing the terrain for cover.",
            "sniffs at a piece of discarded food, testing its freshness.",
            "paws at the ground in a digging motion, as if creating a small burrow.",
            "balances on a narrow surface, displaying impressive coordination.",
            "snuggles into a small nook or corner, creating a cozy resting spot.",
            "chirps softly while nibbling on a small object, expressing satisfaction."
        }
        local emote_summon = {
            "stirs from a cozy nest of discarded papers and cloth.",
            "yawns, revealing tiny teeth as it stretches its legs.",
            "blinks sleepily, adjusting to the daylight filtering through the cityscape.",
            "rubs its eyes with tiny paws, shaking off the remnants of rodent dreams.",
            "snuggles briefly into a warm patch of sunlight.",
            "twitches its whiskers in the morning breeze.",
            "emerges from a hidden nook with a sleepy demeanor.",
            "shakes off imaginary sleep dust from its fur.",
            "stumbles a bit, still half in the realm of rodent dreams.",
            "sniffs the air, detecting the scents of the awakening city.",
            "grooms its fur meticulously, preparing for the day ahead.",
            "chirps softly, communicating with other rodents in the vicinity.",
            "nuzzles against a familiar object, seeking comfort.",
            "stretches each tiny leg one by one.",
            "squeaks softly in greeting to the waking world.",
            "pokes its head out from a cozy hideout.",
            "sniffs for crumbs left by night vendors.",
            "glances around, assessing the safety of its surroundings.",
            "curiously investigates a nearby object with cautious steps.",
            "shivers as it adjusts to the morning chill.",
            "licks its tiny paws, grooming away the remnants of sleep.",
            "scampers in a small circle to shake off drowsiness.",
            "chatters its teeth, a sign of morning excitement.",
            "sniffs the ground, checking for any interesting scents.",
            "wiggles its ears as it becomes fully awake.",
            "scurries to a higher vantage point to survey the waking city.",
            "cuddles briefly with another rat, sharing warmth.",
            "sniffs at its surroundings, detecting changes since it fell asleep.",
            "sits up on its hind legs, surveying the world with alertness.",
            "nibbles on a small piece of food stored for breakfast.",
            "chases its tail in a playful display of morning energy.",
            "glances at the sunrise with curious eyes.",
            "stamps its tiny feet in a rhythmic pattern, a morning dance.",
            "snuggles into the folds of a discarded cloth for a moment of warmth.",
            "washes its face with meticulous licks.",
            "squeezes through a small opening, venturing out into the world.",
            "scampers in a zigzag pattern, testing its agility.",
            "sniffs at the remnants of last night's meals for potential breakfast.",
            "nudges a fellow rat, exchanging morning greetings.",
            "glances at the city skyline, taking in the sights of the waking metropolis.",
            "pauses to observe a passing human with cautious interest.",
            "squeaks with excitement, announcing its presence to the world.",
            "pounces playfully on a small object, a burst of morning energy.",
            "rubs its tiny face against a familiar surface, marking its territory.",
            "scampers up a vertical surface with nimble agility.",
            "sniffs at a flower, enjoying the morning scents.",
            "sits up on its hind legs and scans the surroundings with curiosity.",
            "shakes off imaginary water, mimicking a morning grooming routine.",
            "nibbles on a leaf or small piece of vegetation.",
            "scampers to a sunny spot, basking in the warmth of the morning sun.",
            "curiously inspects a passing insect, considering it as potential breakfast.",
            "squeaks softly as it discovers a hidden stash of crumbs.",
            "hops from one paw to another in a miniature dance of morning joy.",
            "sniffs at a discarded piece of cloth, checking for interesting scents.",
            "shivers and fluffs its fur, adjusting to the temperature change.",
            "scurries in a zigzag pattern, testing its reflexes.",
            "scratches its ear with a hind leg, showing signs of morning wakefulness.",
            "nibbles on a small twig or piece of wood, testing its teeth.",
            "curiously investigates a new object with cautious steps.",
            "snuggles against another rat for warmth and companionship.",
            "chases its own tail in a playful display of morning energy.",
            "sniffs the air for the familiar scents of fellow rodents.",
            "washes its face with meticulous licks, preparing for the day ahead.",
            "pauses to groom its tail with tiny, careful licks.",
            "chirps softly, communicating with other rats in the vicinity.",
            "curiously explores a new corner with cautious steps.",
            "stamps its tiny feet in a rhythmic pattern, a morning dance.",
            "sniffs at the remnants of last night's meals for potential breakfast.",
            "nudges a fellow rat, exchanging morning greetings.",
            "glances at the city skyline, taking in the sights of the waking metropolis.",
            "pauses to observe a passing human with cautious interest.",
            "squeaks with excitement, announcing its presence to the world.",
            "pounces playfully on a small object, a burst of morning energy.",
            "rubs its tiny face against a familiar surface, marking its territory.",
            "scampers up a vertical surface with nimble agility.",
            "sniffs at a flower, enjoying the morning scents.",
            "sits up on its hind legs and scans the surroundings with curiosity.",
            "shakes off imaginary water, mimicking a morning grooming routine.",
            "nibbles on a leaf or small piece of vegetation.",
            "scampers to a sunny spot, basking in the warmth of the morning sun.",
            "curiously inspects a passing insect, considering it as potential breakfast.",
            "squeaks softly as it discovers a hidden stash of crumbs.",
            "hops from one paw to another in a miniature dance of morning joy.",
            "sniffs at a discarded piece of cloth, checking for interesting scents.",
            "shivers and fluffs its fur, adjusting to the temperature change.",
            "scurries in a zigzag pattern, testing its reflexes.",
            "scratches its ear with a hind leg, showing signs of morning wakefulness.",
            "nibbles on a small twig or piece of wood, testing its teeth.",
            "curiously investigates a new object with cautious steps.",
            "snuggles against another rat for warmth and companionship.",
            "chases its own tail in a playful display of morning energy.",
            "sniffs the air for the familiar scents of fellow rodents.",
            "washes its face with meticulous licks, preparing for the day ahead.",
            "pauses to groom its tail with tiny, careful licks."
        }
  
        local speak = {
            "In the shadows, my tiny eyes gleam with curiosity.",
            "As I scamper through Stormwind, let the city walls echo with my tiny footsteps.",
            "In the cheese-scented breeze, my whiskers tingle with the aromas of adventure.",
            "As I explore the alleys, let the moonlight be my guiding star.",
            "In the nooks and crannies of the city, my tiny heart beats with the rhythm of life.",
            "As I nibble on crumbs of destiny, let the cosmic tapestry weave tales of rodent valor.",
            "In the moonlit silence, my fur becomes a canvas painted with the hues of exploration.",
            "As I navigate the city maze, let the stars be my companions in the night.",
            "In the cheese-laden dreams, my tiny paws leave imprints on the fabric of Stormwind.",
            "As I stand on my hind legs, let the city acknowledge its smallest adventurer.",
            "In the cheese-hued twilight, my whiskers quiver with the anticipation of discovery.",
            "As I nibble on the crumbs of fate, let the constellations map out my rodent journey.",
            "In the quiet corners, my tiny silhouette dances with the shadows of curiosity.",
            "As I scamper through the streets, let the cityscape be my playground of exploration.",
            "In the cheese-sprinkled zephyr, my tiny heart beats with the thrill of the unknown.",
            "As I stand on the precipice of discovery, let the moonlight illuminate my path.",
            "In the cosmic ballet, my fur becomes stardust in the tapestry of rodent existence.",
            "As I nibble on the cheese of destiny, let the city walls resonate with my tiny tales.",
            "In the contemplative silence, my whiskers twitch with the thoughts of rodent philosophy.",
            "As I traverse the cityscape, let the night be my companion on this grand adventure.",
            "In the cheese-scented meadows, my tiny eyes twinkle with the magic of exploration.",
            "As I nibble on the crumbs of enlightenment, let the stars be my celestial teachers.",
            "In the moonlit serenade, my squeaks become a melody of rodent whimsy.",
            "As I scamper through the shadows, let the echoes of my tiny adventures fill the air.",
            "In the cheese-laden breeze, my fur becomes a tapestry of dreams woven with hope.",
            "As I stand on my hind legs, let the moonlight cast my shadow on the city walls.",
            "In the cosmic cheese wheel, my heart beats with the rhythm of rodent life.",
            "As I nibble on the cheese of contemplation, let the city acknowledge its philosophical rodent.",
            "In the quietude of the night, my tiny heart resonates with the symphony of existence.",
            "As I explore the byways, let the cityscape be my canvas of rodent artistry.",
            "In the cheese-sprinkled moonlight, my tiny silhouette pirouettes with rodent grace.",
            "As I nibble on the crumbs of wisdom, let the stars be my celestial advisors.",
            "In the moonlit serenity, my whiskers quiver with the tranquility of rodent meditation.",
            "As I scamper through the cityscape, let the echoes of my tiny squeaks be heard.",
            "In the cheese-hued dreams, my fur becomes a pillow for the slumber of rodent musings.",
            "As I stand on my hind legs, let the city walls be witnesses to my upright contemplation.",
            "In the cosmic cheese wheel, my heart beats with the rhythm of rodent life.",
            "As I nibble on the cheese of contemplation, let the city acknowledge its philosophical rodent.",
            "In the quietude of the night, my tiny heart resonates with the symphony of existence.",
            "As I explore the byways, let the cityscape be my canvas of rodent artistry.",
            "In the cheese-sprinkled moonlight, my tiny silhouette pirouettes with rodent grace.",
            "As I nibble on the crumbs of wisdom, let the stars be my celestial advisors.",
            "In the moonlit serenity, my whiskers quiver with the tranquility of rodent meditation.",
            "As I scamper through the cityscape, let the echoes of my tiny squeaks be heard.",
            "In the cheese-hued dreams, my fur becomes a pillow for the slumber of rodent musings.",
            "As I stand on my hind legs, let the city walls be witnesses to my upright contemplation.",
            "In the cheese-laden corridors, my tiny eyes sparkle with the reflections of adventure.",
            "As I traverse the cityscape, let the night be my companion on this grand adventure.",
            "In the cheese-scented meadows, my tiny eyes twinkle with the magic of exploration.",
            "As I nibble on the crumbs of enlightenment, let the stars be my celestial teachers.",
            "In the moonlit serenade, my squeaks become a melody of rodent whimsy.",
            "As I scamper through the shadows, let the echoes of my tiny adventures fill the air.",
            "In the cheese-laden breeze, my fur becomes a tapestry of dreams woven with hope.",
            "As I stand on my hind legs, let the moonlight cast my shadow on the city walls.",
            "In the cosmic cheese wheel, my heart beats with the rhythm of rodent life.",
            "As I nibble on the cheese of contemplation, let the city acknowledge its philosophical rodent.",
            "In the quietude of the night, my tiny heart resonates with the symphony of existence.",
            "As I explore the byways, let the cityscape be my canvas of rodent artistry.",
            "In the cheese-sprinkled moonlight, my tiny silhouette pirouettes with rodent grace.",
            "As I nibble on the crumbs of wisdom, let the stars be my celestial advisors.",
            "In the moonlit serenity, my whiskers quiver with the tranquility of rodent meditation.",
            "As I scamper through the cityscape, let the echoes of my tiny squeaks be heard.",
            "In the cheese-hued dreams, my fur becomes a pillow for the slumber of rodent musings.",
            "As I stand on my hind legs, let the city walls be witnesses to my upright contemplation.",
            "In the cosmic cheese wheel, my heart beats with the rhythm of rodent life.",
            "As I nibble on the cheese of contemplation, let the city acknowledge its philosophical rodent.",
            "In the quietude of the night, my tiny heart resonates with the symphony of existence.",
            "As I explore the byways, let the cityscape be my canvas of rodent artistry.",
            "In the cheese-sprinkled moonlight, my tiny silhouette pirouettes with rodent grace.",
            "As I nibble on the crumbs of wisdom, let the stars be my celestial advisors.",
            "In the moonlit serenity, my whiskers quiver with the tranquility of rodent meditation.",
            "As I scamper through the cityscape, let the echoes of my tiny squeaks be heard.",
            "In the cheese-hued dreams, my fur becomes a pillow for the slumber of rodent musings.",
            "As I stand on my hind legs, let the city walls be witnesses to my upright contemplation."
        }
          local speak_win = {
            "In the shadows, my triumphant squeaks resonate like a victorious symphony.",
            "As I scamper through the aftermath, let the echoes of my triumph fill the alleys.",
            "In the celebratory dance, my tiny paws leave imprints of conquest on the cobblestones.",
            "As I bask in the glory of victory, let the city walls echo with the cheers of rodents.",
            "In the cheese-scented breeze, my whiskers tingle with the sweet taste of conquest.",
            "As I stand atop my victorious perch, let the moonlight illuminate my triumphant silhouette.",
            "In the victory parade, my fur becomes a tapestry of achievements woven with pride.",
            "As I nibble on the spoils of battle, let the crumbs of triumph be my feast.",
            "In the dance of victory, my tail wags with the rhythm of triumph and joy.",
            "As I scamper through the celebratory confetti, let the city acknowledge my epic saga.",
            "In the cheese-laden air, my triumphant squeaks herald the dawn of a new era.",
            "As I raise my tiny head in triumph, let the stars twinkle in admiration.",
            "In the victory march, my paws leave a trail of glory for future generations of rodents.",
            "As I nibble on the cheese of conquest, let the city walls bear witness to my greatness.",
            "In the moonlit celebration, my fur becomes a shimmering cloak of victory.",
            "As I ascend to my throne of triumph, let the heavens shower me with celestial cheese.",
            "In the victorious shadows, my tiny eyes gleam with the spark of accomplishment.",
            "As I stand atop the cheese mountain, let the echoes of my triumph reverberate through Stormwind.",
            "In the cheese-scented zephyr, my triumphant squeaks become a melody of triumph.",
            "As I revel in victory, let the city streets become a stage for my heroic exploits.",
            "In the cheese-hued glow, my triumphant silhouette dances in the moonlight.",
            "As I nibble on the spoils of war, let the celestial fromage be my reward.",
            "In the victorious silence, my whiskers twitch with the satisfaction of a triumphant rodent.",
            "As I scamper through the celebration, let the moon be a spotlight on my glorious conquest.",
            "In the cheese-sprinkled victory, my spirit soars like a rodent king.",
            "As I bask in the afterglow of triumph, let the walls of Stormwind bear witness to my epic tale.",
            "In the triumphant moonlight, my fur glistens with the stardust of conquest.",
            "As I raise my tiny flag of victory, let the cosmos salute the prowess of a rodent champion.",
            "In the victorious meadows, my triumphant squeaks become a chorus of celebration.",
            "As I nibble on the cheese of glory, let the echoes of my triumph ripple through the night.",
            "In the victorious mosaic, my tiny paw prints create a masterpiece of valor.",
            "As I ascend to the cheese-filled heavens, let the stars be my loyal subjects.",
            "In the aftermath of triumph, my tail swirls with the energy of a conquering rodent.",
            "As I bask in the glory of conquest, let the city walls be adorned with tales of my heroism.",
            "In the cheese-scented aftermath, my whiskers tingle with the euphoria of victory.",
            "As I stand atop the mountain of triumph, let the moonlight crown me the rodent king.",
            "In the victorious aftermath, my fur becomes a celestial cloak of honor.",
            "As I nibble on the cheese of legends, let the heavens applaud my epic saga.",
            "In the triumphant tapestry, my silhouette becomes a defining thread in the fabric of Stormwind.",
            "As I revel in the triumph, let the echoes of my squeaks be a rallying cry for rodentkind.",
            "In the cheese-laden breeze, my triumphant squeaks become whispers of valor.",
            "As I scamper through the celebratory moonlight, let the city acknowledge its rodent champion.",
            "In the victorious aftermath, my tiny eyes twinkle with the brilliance of a conquering hero.",
            "As I nibble on the cheese of immortality, let the cosmic rodents join in my celebration.",
            "In the triumphant shadows, my fur becomes a canvas painted with strokes of victory.",
            "As I stand on the podium of conquest, let the stars be my adoring audience.",
            "In the cheese-sprinkled celebration, my triumphant silhouette dances in the moonlit spotlight.",
            "As I ascend to the cheese-filled throne, let the heavens bow to the rodent sovereign.",
            "In the victorious night, my tiny heart beats with the rhythm of a triumphant warrior.",
            "As I nibble on the spoils of epic battles, let the echoes of my triumph resonate through time.",
            "In the cheese-hued twilight, my triumphant squeaks become a serenade to the city.",
            "As I bask in the glory of rodent valor, let the constellations spell my name in the skies.",
            "In the triumphant silence, my whiskers quiver with the satisfaction of a victorious rodent.",
            "As I scamper through the victorious streets, let the moonlight be the spotlight on my achievements.",
            "In the cheese-scented aftermath, my triumphant silhouette casts a heroic shadow.",
            "As I nibble on the cheese of destiny, let the stars bear witness to my epic journey.",
            "In the triumphant embrace of shadows, my tiny heart swells with the pride of a victorious warrior.",
            "As I stand atop the mountain of cheese, let the celestial beings applaud my rodent triumph.",
            "In the victorious aftermath, my fur becomes a tapestry woven with the threads of glory.",
            "As I revel in the triumph, let the moonlight be the stage for my rodent ballet.",
            "In the cheese-scented breeze, my triumphant squeaks become a chorus of celebration.",
            "As I scamper through the victorious meadows, let the city walls be adorned with tales of my heroism.",
            "In the triumphant mosaic, my silhouette becomes a defining piece in the grand design of Stormwind.",
            "As I nibble on the cheese of immortality, let the cosmic rodents join in my celebration.",
            "In the triumphant shadows, my fur becomes a canvas painted with strokes of victory.",
            "As I stand on the podium of conquest, let the stars be my adoring audience.",
            "In the cheese-sprinkled celebration, my triumphant silhouette dances in the moonlit spotlight.",
            "As I ascend to the cheese-filled throne, let the heavens bow to the rodent sovereign.",
            "In the victorious night, my tiny heart beats with the rhythm of a triumphant warrior.",
            "As I nibble on the spoils of epic battles, let the echoes of my triumph resonate through time.",
            "In the cheese-hued twilight, my triumphant squeaks become a serenade to the city.",
            "As I bask in the glory of rodent valor, let the constellations spell my name in the skies.",
            "In the triumphant silence, my whiskers quiver with the satisfaction of a victorious rodent.",
            "As I scamper through the victorious streets, let the moonlight be the spotlight on my achievements.",
            "In the cheese-scented aftermath, my triumphant silhouette casts a heroic shadow.",
            "As I nibble on the cheese of destiny, let the stars bear witness to my epic journey.",
            "In the triumphant embrace of shadows, my tiny heart swells with the pride of a victorious warrior.",
            "As I stand atop the mountain of cheese, let the celestial beings applaud my rodent triumph.",
            "In the victorious aftermath, my fur becomes a tapestry woven with the threads of glory.",
            "As I revel in the triumph, let the moonlight be the stage for my rodent ballet."
        }
        local speak_dead = {
            "In the shadows, my tiny heart weeps for the end of my journey.",
            "As I scurry into the afterlife, may the cheese of memories linger.",
            "In the alleys of Stormwind, my squeaks become echoes of the past.",
            "As my whiskers still, let the city streets remember my footsteps.",
            "In the maze of life, my tiny paws leave behind the prints of nostalgia.",
            "As I nibble on the celestial cheese, let the moonlight be my guide.",
            "In the quiet corners, my fur becomes stardust in the cosmic ballet.",
            "As I burrow into the beyond, may the crumbs of joy mark my passage.",
            "In the cheese-laden dreams, my spirit dances with other ethereal rodents.",
            "As my tail curls for the last time, let the wind carry my farewell.",
            "In the cheese-scented breeze, my squeaks serenade the night.",
            "As I scamper into the twilight, may the memories be as warm as a nest.",
            "In the nooks and crannies of memory, my tiny heart leaves a lasting imprint.",
            "As my tiny eyes close, let the stars twinkle with the light of fond remembrance.",
            "In the cheesiest realms, my spirit nibbles on the eternal delights.",
            "As I nibble on the celestial cheese, let the moonlight be my guide.",
            "In the quiet corners, my fur becomes stardust in the cosmic ballet.",
            "As I burrow into the beyond, may the crumbs of joy mark my passage.",
            "In the cheese-laden dreams, my spirit dances with other ethereal rodents.",
            "As my tail curls for the last time, let the wind carry my farewell.",
            "In the cheese-scented breeze, my squeaks serenade the night.",
            "As I scamper into the twilight, may the memories be as warm as a nest.",
            "In the nooks and crannies of memory, my tiny heart leaves a lasting imprint.",
            "As my tiny eyes close, let the stars twinkle with the light of fond remembrance.",
            "In the cheesiest realms, my spirit nibbles on the eternal delights.",
            "As my tiny paws find rest, let the echoes of my scurrying play on.",
            "In the cheese halls of the afterlife, my whiskers twitch with joy.",
            "As I nibble on the cosmic cheese, let the constellations be my feast.",
            "In the tapestry of rodent tales, my story weaves into the lore of Stormwind.",
            "As I join the celestial cheese wheel, may the angels nibble in merriment.",
            "In the fond memories, my furry silhouette dances in the moonlight.",
            "As my squeaks fade, let the silence be a canvas for my final mural.",
            "In the heart of Stormwind, my spirit scampers with the wind of eternal nights.",
            "As I gnaw on the ethereal cheese, let the afterlife be a feast of delights.",
            "In the cheesy meadows beyond, my tiny spirit frolics in perpetual joy.",
            "As I leave the earthly cheese, let the heavens shower me with crumbs of peace.",
            "In the whispers of cheese-loving spirits, my tiny voice harmonizes.",
            "As I nibble on celestial crumbs, let the starlight be my everlasting snack.",
            "In the fond recollections, my tail wags with the rhythm of joyful nostalgia.",
            "As my tiny soul ascends, let the moon be my lantern in the nocturnal beyond.",
            "In the cosmic cheese wheel, my spirit finds everlasting delight.",
            "As I join the cheese constellation, may the universe echo with my tiny laughter.",
            "In the fromage heavens, my heart beats to the rhythm of everlasting joy.",
            "As my tiny whiskers touch the celestial cheddar, let the galaxies applaud.",
            "In the symphony of cheese, my melody serenades the cosmic rodents.",
            "As I nibble on the ethereal Gouda, let the afterlife be a banquet of flavors.",
            "In the halls of fromage eternity, my spirit nibbles on the cheese of cosmic delight.",
            "As I scurry into the celestial burrow, let the stars be my witnesses.",
            "In the cheesy meadows of the beyond, my spirit leaps with eternal glee.",
            "As my tiny paws leave the earthly soil, let the heavens be my soft bedding.",
            "In the heart of cheese constellations, my spirit twinkles with everlasting mirth.",
            "As I nibble on the ethereal brie, let the clouds be pillows for my tiny rest.",
            "In the celestial cheese wheel, my essence merges with the flavor of infinity.",
            "As I join the cosmic nibblers, may the universe resound with my tiny chorus.",
            "In the crannies of cheese dimensions, my laughter echoes in perpetuity.",
            "As my tiny silhouette fades, let the night embrace the memory of my scamper.",
            "In the cheese-scented zephyr, my spirit pirouettes with cosmic delight.",
            "As I nibble on the starry cheddar, let the galaxies applaud my final feast.",
            "In the cosmic burrow, my spirit nestles in the warmth of celestial curds.",
            "As I scamper into the afterlife, may the moonlight guide my nocturnal journey.",
            "In the cheese-hued realms, my spirit paints the skies with hues of joy.",
            "As my fur becomes stardust, let the heavens be a vast, twinkling tapestry.",
            "In the fromage eternity, my spirit nibbles on the cheese of perpetual bliss.",
            "As I nibble on the ethereal Gruyère, let the afterlife be a banquet of textures.",
            "In the symphony of cheese, my melody serenades the cosmic rodents.",
            "As I nibble on the ethereal cheddar, let the afterlife be a banquet of flavors.",
            "In the halls of fromage eternity, my spirit nibbles on the cheese of cosmic delight.",
            "As I scurry into the celestial burrow, let the stars be my witnesses.",
            "In the cheesy meadows of the beyond, my spirit leaps with eternal glee.",
            "As my tiny paws leave the earthly soil, let the heavens be my soft bedding.",
            "In the heart of cheese constellations, my spirit twinkles with everlasting mirth.",
            "As I nibble on the ethereal brie, let the clouds be pillows for my tiny rest.",
            "In the celestial cheese wheel, my essence merges with the flavor of infinity.",
            "As I join the cosmic nibblers, may the universe resound with my tiny chorus.",
            "In the crannies of cheese dimensions, my laughter echoes in perpetuity.",
            "As my tiny silhouette fades, let the night embrace the memory of my scamper.",
            "In the cheese-scented zephyr, my spirit pirouettes with cosmic delight.",
            "As I nibble on the starry cheddar, let the galaxies applaud my final feast.",
            "In the cosmic burrow, my spirit nestles in the warmth of celestial curds.",
            "As I scamper into the afterlife, may the moonlight guide my nocturnal journey.",
            "In the cheese-hued realms, my spirit paints the skies with hues of joy.",
            "As my fur becomes stardust, let the heavens be a vast, twinkling tapestry.",
            "In the fromage eternity, my spirit nibbles on the cheese of perpetual bliss.",
            "As I nibble on the ethereal Gruyère, let the afterlife be a banquet of textures.",
            "In the symphony of cheese, my melody serenades the cosmic rodents."
        }
          if (type:lower() == "speak") then
            collection = speak
        elseif (type:lower() == "emote") then
            collection = emote
        elseif (type:lower() == "speak_win") then
            collection = speak_win
        elseif (type:lower() == "emote_summon") then
            collection = emote_summon
        elseif (type:lower() == "speak_dead") then
            collection = speak_dead
        end
        local comment = "Has nothing interesting to say"
        if (collection ~= nil and OracleHUD_TableGetLength(collection) > 0) then
            comment = collection[math.random(1, OracleHUD_TableGetLength(collection))]
        end
        return comment
    end
end
