if (ORACLEHUD_PB_DB_UPDATE == nil) then
    ORACLEHUD_PB_DB_UPDATE = {}
end
ORACLEHUD_PB_DB_UPDATE.s72 = function(db) 
    db.content.petComments.s72 = function(db)
        local phrases = {
            "Brr, it's chilly out here!",
            "Is that a snowflake on my nose?",
            "I love hopping through fresh snow.",
            "Winter wonderland, here I am!",
            "Can I borrow your mittens?",
            "Snowflakes are my confetti.",
            "I'm the fluffiest snowshoe bunny around.",
            "Let's build a snowshoe bunny family!",
            "Winter is my favorite season.",
            "I'm a snowflake collector.",
            "Can we have a snowball fight?",
            "Bundled up and ready for adventure.",
            "Frosty whiskers, don't care!",
            "Snow tunnels are my secret hideouts.",
            "I'm the master of snowshoe camouflage.",
            "Snowflakes are nature's glitter.",
            "Let's go snowshoeing, shall we?",
            "Cold paws, warm heart!",
            "I'm the snow angel champion.",
            "Hot cocoa by the fire, please!",
            "Winter's my time to shine.",
            "Snowy landscapes make me happy.",
            "Let's sled down that hill!",
            "Fluffy tail, fluffy heart.",
            "Frosty mornings are magical.",
            "Snowy adventures are the best.",
            "Snowy days are for burrowing.",
            "Let's catch snowflakes on our tongues.",
            "Cold noses and cozy burrows.",
            "I'm a snowshoe rabbit enthusiast.",
            "Snowy kisses are the sweetest.",
            "Hopping through a winter wonderland.",
            "Snowball fights make me giggle.",
            "Let's make snowshoe rabbit angels!",
            "Cold cheeks and warm burrows.",
            "I'm a snowflake collector, you know.",
            "Icicles make for great decorations.",
            "Snowy trails, endless discoveries.",
            "Snowy burrows are my cozy retreats.",
            "I'm a snowflake connoisseur.",
            "Snowflakes make the world glisten.",
            "Let's have a snowflake fashion show!",
            "Cold paws, but a warm, fuzzy heart.",
            "Ice skating on frozen ponds is a blast!",
            "Snowy peaks are my favorite spots.",
            "Snowy adventures are pure joy!",
            "Snow-covered branches are my artwork.",
            "Snowy days call for snowball fights.",
            "Let's make snowshoe rabbit crowns!",
            "Fluffy tails leave tracks in the snow.",
            "Cold noses and toasty burrows.",
            "I'm a snowflake enthusiast, no doubt.",
            "Snowflakes bring magic to the world.",
            "Let's have a snowflake party!",
            "Snowy nights are for stargazing.",
            "Snowy whiskers, what a delight!",
            "Icicle chandeliers are magnificent.",
            "Snowy trails lead to new discoveries.",
            "Snowfall is like nature's lullaby.",
            "I'm a snowshoe rabbit explorer.",
            "Let's build a snowshoe rabbit igloo!",
            "Snowy valleys are my wonderland.",
            "Snowy days are for snowy cuddles.",
            "I'm a snowflake aficionado.",
            "Snowflakes are like frozen dreams.",
            "Let's sled down the slopes!",
            "Fluffy paws leave prints in the snow.",
            "Cold mornings and warm snuggles.",
            "Icicles are nature's decorations.",
            "Snowy meadows are my sanctuary.",
            "Snowy escapades are full of surprises.",
            "Snow-covered landscapes are enchanting.",
            "Let's have a snowflake parade!",
            "Cold noses, warm bunny hearts.",
            "Ice skating on frozen lakes is amazing!",
            "Snowy days are for snowy adventures.",
            "I'm a snowflake explorer extraordinaire.",
            "Snowflakes are like frozen kisses.",
            "Let's go snowshoeing, want to join?",
            "Snowy hills are made for hopping.",
            "Snowy fields are a blank canvas.",
            "Let's make snowflake crowns and dance!",
            "Cold paws, warm burrow comforts.",
            "Icicle ornaments are splendid.",
            "Snowy trails lead to new horizons.",
            "Snowfall is like a gentle lullaby.",
            "I'm a snowshoe rabbit in a winter wonderland."
        }
        return phrases[math.random(1, OracleHUD_TableGetLength(phrases))]
    end
end
