--- @class OracleHUD_PB_DB		Main database for OracleHUD Pet Battles.
--- @field debug	boolean		All code must execute their debugging prints.
--- @field modules	any			Namespace for services and panels to save variables.
--- @field options	any			Namespace for interface options to save variables.
--- @field content  any?